### ISSUE TITLE
Monitoring: Add redirections for child posts/pages

### ISSUE THREAD

**Issue by strarsis** [johngodley/redirection#1617] opened 2019-03-29 15:23 UTC
### Summary

When hierarchical posts/pages are monitored, redirections for 
child posts/pages URLs that contain the parent URL should also be created.

### Actual Behavior

Only a redirection for the (parent) post/page is created, none for its child posts/pages.

### Steps to reproduce

1. Create a page.
2. Add several sub-pages to that page, ensure their permalinks contain 
the parent slug or are otherwise influenced by parent post/page.
3. Ensure that this post/page is monitored by Redirection plugin.
4. Change URL of parent post/page.
5. Notice that Redirection created a new redirection for 
the parent post/page, but none for the child posts/pages.

### Environment

- Chrome (recent)
- WordPress 5.1.1
- Redirection 4.1

**Comment by laupow** [comment] 2019-04-01 22:06
@johngodley I was going to a new issue but I'll add a second report instead, because I think it's the same request. 👍 


**Expected Behavior:**
Updating a child slug after its parent slug was edited doesn't break redirects

**Actual Behavior:**
Changing child slugs breaks after a parent slug has been changed

**Why this is a problem:**
People change slugs over time. It's a matter of time before the child/parent/child sequence happens on a site that's actively maintained. URLs hardcoded in content will work for a bit, but then break unexpectedly.

**Steps to Reproduce:**
*Test command: `curl -L http://local.local/parent/child/ -v -o /dev/null`*

1) Turn on Page Monitoring
1) Add a new Parent page with slug=parent
1) Add a new Child Page  with slug=child and parent=parent
1) On Parent page, insert a link to the Child page in content
	> So there's HTML like `Link to <a href="http://local.local/parent/child/">Child</a>`
1) Update Child slug, setting slug=child-edited
	> Test: GET /parent/child/ == 301 to /parent/child-edited/ == 200
1) Update Parent slug, setting slug=parent-edited
	> Test: GET /parent/child/ == 301 to /parent/child-edited/ == 301 to /parent-edited/child-edited/ == 200
1) Update Child slug, setting slug=child-future-update
	> Test: GET /parent/child/ == 301 to /parent/child-edited/ == 404

Export of Redirection DB:
```text
source,target,regex,type,code,match,hits,title
"/parent/child/","/parent/child-edited/","0","url","301","url","9",""
"/parent/","/parent-edited/","0","url","301","url","0",""
"/parent-edited/child-edited/","/parent-edited/child-future-update/","0","url","301","url","0",""
```

Environment: WordPress 5.1.1 + Redirection 4.1.1. Fresh Install. No Multisite.

**Comment by johngodley** [comment] 2022-07-13 06:26
Moving to #3349

**Closed by johngodley** 2022-07-13 06:26 UTC
Labels: enhancement
