### ISSUE TITLE
Redirection Upgrade database Error

### ISSUE THREAD

**Issue by zoneandonly** [johngodley/redirection#2523] opened 2020-10-27 21:13 UTC
All plugins off except Redirection
Active theme 2020

```
Plugin: 4.9
WordPress: 5.5.1 (single)
PHP: 7.4.11
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
JavaScript: https://www.knowdebt.org/wp-content/plugins/redirection/redirection.js?ver=4.9-c383de96c0b7e38459253ead4f6e9b10
REST API: https://www.knowdebt.org/wp-json/
Query: ?page=redirection.php

Action: https://www.knowdebt.org/wp-json/redirection/v1/plugin/database/ POST
Code: 403 Forbidden

Error: JSON Parse error: Unrecognized token '<' (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>
```

**Comment by johngodley** [comment] 2020-10-28 14:20
Your REST API is being blocked, possibly by some security software on your server. Are you running anything that might do this, such as a firewall?

**Comment by zoneandonly** [comment] 2020-10-30 14:57
no firewall. Just built-in security software (Mac).

**Comment by johngodley** [comment] 2020-10-30 15:00
I'm referring to your website, not your computer. You can see the 403 permission error above, which your website is returning. This is often caused by a plugin, or something in your .htaccess file.

**Comment by zoneandonly** [comment] 2020-11-02 14:19
The server is a Mac with Homebrew. 
I've tested it with all plugins off, using default theme.
Could you give me a hint as to what to look for in .htaccess file? I've looked at it, nothing obvious to me.

**Comment by johngodley** [comment] 2020-11-08 17:45
Can you post it here?

**Comment by johngodley** [comment] 2020-11-14 10:20
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-14 10:20 UTC
