### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by davidhealey** [johngodley/redirection#2484] opened 2020-10-14 20:14 UTC
```
Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.3.23
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
JavaScript: https://xtant-audio.com/wp-content/plugins/redirection/redirection.js
REST API: https://xtant-audio.com/wp-json/

Error: Unexpected token < in JSON at position 4 (SyntaxError)
Action: redirection/v1/redirect/?orderby=id GET
Code: 403 Access Forbidden
Raw:     <!DOCTYPE html>
    <html style="height: 100%;">
    <head>
        <meta charset="UTF-8">
        <title>403 Access Forbidden</title>
        <style>
            @media screen and (max-width: 800px) {
                body > div > div > div div {
                    display: block !important;
                    padding-right: 0 !important;
                }

                body {
                    text-align: center !important;
                }
            }
        </style>
    </head>
    <body style="height: 90%;">
    <div style="display: flex; align-items: center; justify-content: center; height: 90%;">
        <div style="background-color: #eee; width: 70%; border: solid 3px #ddd; padding: 1.5em 3em 3em 3em; font-family: Arial, Helvetica, sans-serif;">
            <div style="display: table-row;">
                <div style="display: table-cell; font-size: 150px; color: red; vertical-align: top; padding-right: 50px;">
                    &#9995;
                </div>
                <div style="display: table-cell; vertical-align: top;">
                    <h1 style="margin-top: 0;">We're sorry, you are not allowed to proceed</h1>
                    <p>Your request looks suspiciously similar to automated requests from spam posting software or it has been denied by a security policy configured by the website administrator.</p>
                    <p>If you believe you should be able to perform this request, please let us know.</p>
                    <p style="margin-top: 2em;">
                    <pre style="color: #777">RID: 3BFFTUVOA1XS0ZHZDICMN8JL</pre>
                    </p>
                </div>
            </div>
        </div>
    </div>
    </body>
    </html>
	
```

**Comment by johngodley** [comment] 2020-10-14 21:06
The problem is shown in the message above:

`Your request looks suspiciously similar to automated requests from spam posting software or it has been denied by a security policy configured by the website administrator. If you believe you should be able to perform this request, please let us know.`

**Comment by davidhealey** [comment] 2020-10-14 21:08
I see the problem. What is the solution? :)

**Comment by johngodley** [comment] 2020-10-14 21:14
I couldn't really say. It's not caused by the Redirection, and is likely another plugin, or some kind of security system. You can see it yourself here:

https://xtant-audio.com/wp-json/

**Comment by davidhealey** [comment] 2020-10-14 21:21
I don't understand, why is redirection trying to access wp-json? That file/directory doesn't exist on my server.

**Comment by johngodley** [comment] 2020-10-14 21:27
It is your WordPress REST API, a fundamental part of WordPress. It doesn’t need to exist as a directory. Check your site health to see a similar report from WordPress itself

**Comment by davidhealey** [comment] 2020-10-14 21:28
Ah ok, I'll try that, thanks

**Comment by johngodley** [comment] 2020-10-17 14:05
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-10-17 14:05 UTC
