### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by abvwpdev** [johngodley/redirection#1314] opened 2018-11-30 14:09 UTC
```
Plugin: 3.6.3
WordPress: 4.9.8 (single)
PHP: 7.2.10-0ubuntu0.18.04.1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
JavaScript: https://www.momjunction.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.momjunction.com/wp-api/

Error: Missing parameter(s): items (rest_missing_callback_param)
Action: redirection/v1/bulk/redirect/disable/?orderby=id&filter=%2Farticles%2Fhealthy-meals-for-breastfeeding-moms_00383677%2F&per_page=50 POST
Params: {"items":"173"}
Code: 400 Bad Request
Raw: {"code":"rest_missing_callback_param","message":"Missing parameter(s): items","data":{"status":400,"params":["items"]}}
```

**Comment by johngodley** [comment] 2018-12-02 17:47
What are you doing when this occurs?

**Comment by abvwpdev** [comment] 2018-12-03 05:55
This occurs when i try to edit/disable the redirection, While adding redirection it shows added but its actually not adding them.

**Comment by abvwpdev** [comment] 2018-12-04 06:39
> What are you doing when this occurs?

This occurs when i try to edit/disable the redirection, While adding redirection it shows added but its actually not adding them.

**Comment by johngodley** [comment] 2018-12-09 15:09
Can you add a screenshot of what you are doing when this happens? I'm not able to reproduce it

**Comment by johngodley** [comment] 2018-12-15 19:34
Closing for now, please reopen with more information

**Closed by johngodley** 2018-12-15 19:34 UTC
Labels: need-feedback
