### ISSUE TITLE
Problem starting Redirection 4.4.2

### ISSUE THREAD

**Issue by crackscoop** [johngodley/redirection#2044] opened 2019-10-27 06:28 UTC
Plugin: 4.4.2
WordPress: 5.2.4 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
JavaScript: https://crackscoop.com/wp-content/plugins/redirection/redirection.js
REST API: https://crackscoop.com/wp-json/

**Comment by johngodley** [comment] 2019-10-27 10:44
Please open your browser's developer console and see if any other error information is shown. This is likely caused by another plugin

**Comment by johngodley** [comment] 2019-11-03 09:14
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-11-03 09:14 UTC
Labels: need-feedback
