### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by deepti4666** [johngodley/redirection#2958] opened 2021-06-24 13:29 UTC
```
Plugin: 5.1.1 4.2
WordPress: 5.7.2 (single)
PHP: 7.4.20
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
JavaScript: /wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: /wp-json/
Query: ?page=redirection.php

Error: Failed to fetch
```

**Comment by johngodley** [comment] 2021-07-04 11:27
This is probably caused by a security plugin.

**Comment by johngodley** [comment] 2021-07-17 06:06
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-07-17 06:06 UTC
Labels: need-feedback
