### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by suratno123** [johngodley/redirection#2633] opened 2020-12-10 13:07 UTC
Plugin: 4.9.2
WordPress: 5.6 (single)
PHP: 7.3.23

**Comment by johngodley** [comment] 2020-12-12 12:26
This is almost certainly caused by another plugin. Please follow the onscreen instructions and check your browser's developer console.

Closing for now, please reopen with more information.

**Closed by johngodley** 2020-12-12 12:26 UTC
