### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by juliavaldez** [johngodley/redirection#1756] opened 2019-05-14 13:07 UTC
```
Plugin: 4.2.3
WordPress: 5.1.1 (single)
PHP: 7.2.16-1+0~20190307202206.17+jessie~1.gbpa7be82
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
JavaScript: https://freeeup.com/wp-content/plugins/redirection/redirection.js
REST API: https://freeeup.com/wp-json/

Error: Unable to add new redirect (41): Disk full (/tmp/#sql_5bf_0.MAI); waiting for someone to free some space... (errno: 28 "No space left on device")
Raw: {"code":"redirect","message":"Unable to add new redirect","data":{"status":400,"error_code":41,"wpdb":"Disk full (\/tmp\/#sql_5bf_0.MAI); waiting for someone to free some space... (errno: 28 \"No space left on device\")"}}
```

**Comment by johngodley** [comment] 2019-05-14 13:19
The problem is shown in the message:

` Unable to add new redirect (41): Disk full (/tmp/#sql_5bf_0.MAI); waiting for someone to free some space... (errno: 28 "No space left on device")`

**Comment by johngodley** [comment] 2019-05-18 12:15
Closing for now, please reopen with more details.

**Closed by johngodley** 2019-05-18 12:15 UTC
Labels: need-feedback
