### ISSUE TITLE
Problem starting Redirection 4.8 

### ISSUE THREAD

**Issue by benseenaweb** [johngodley/redirection#2465] opened 2020-09-26 10:04 UTC
Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.3.20
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15
JavaScript: https://benseena.com/wp-content/plugins/redirection/redirection.js
REST API: https://benseena.com/wp-json/

This issues happened after we had to delete some files on my site.

**Comment by johngodley** [comment] 2020-09-26 11:28
This is almost certainly caused by another plugin. You should follow the onscreen instructions, look in your developer console, or try disabling other plugins  to see.

**Comment by johngodley** [comment] 2020-10-03 13:56
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-10-03 13:56 UTC
