### ISSUE TITLE
Redirection Error - by Mian Salman

### ISSUE THREAD

**Issue by skdevelopers** [johngodley/redirection#3210] opened 2022-01-19 12:24 UTC
```
Plugin: 5.2.1 4.2
WordPress: 5.8.3 (single)
PHP: 7.3.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
JavaScript: https://alinaquintana.com/it/wp-content/plugins/redirection/redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575
REST API: https://alinaquintana.com/it/wp-json/
Query: ?page=redirection.php&sub=site
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    at Mu (https://alinaquintana.com/it/wp-content/plugins/redirection/redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:461442)
    at p
    at div
    at zu (https://alinaquintana.com/it/wp-content/plugins/redirection/redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:461567)
    at _d (https://alinaquintana.com/it/wp-content/plugins/redirection/redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:556368)
    at div
    at a (https://alinaquintana.com/it/wp-content/plugins/redirection/redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:499702)
    at https://alinaquintana.com/it/wp-content/plugins/redirection/redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:746953
    at f (https://alinaquintana.com/it/wp-content/plugins/redirection/redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:376891)
    at Fe (https://alinaquintana.com/it/wp-content/plugins/redirection/redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:374814)
    at t_
```

**Comment by johngodley** [comment] 2022-01-19 12:25
What are you doing when this happens?

**Comment by skdevelopers** [comment] 2022-01-19 12:31
refreshing redirect

**Comment by skdevelopers** [comment] 2022-01-19 12:33
now I have just select option remove trailing slash and then it also showing this error?

**Comment by johngodley** [comment] 2022-01-19 17:46
I am unable to reproduce this problem. Do you have other plugins running? Could they be affecting things?

**Comment by johngodley** [comment] 2022-02-05 13:28
Closing for now, please reopen with more information.

**Closed by johngodley** 2022-02-05 13:28 UTC
