### ISSUE TITLE
Problem starting Redirection 4.8

### ISSUE THREAD

**Issue by travisrr** [johngodley/redirection#2428] opened 2020-08-25 19:35 UTC
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.3.20
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
JavaScript: http://blog.accelerlist.com/wp-content/plugins/redirection/redirection.js
REST API: http://blog.accelerlist.com/wp-json/

**Comment by johngodley** [comment] 2020-08-25 20:50
The error is most likely caused by another plugin. If you open your browser's developer console it might give more clues.

**Comment by johngodley** [comment] 2020-08-31 16:48
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-08-31 16:48 UTC
