### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by alexandresgf** [johngodley/redirection#1518] opened 2019-03-02 00:48 UTC
```
Plugin: 3.7.3
WordPress: 5.1 (single)
PHP: 5.6.30-7+deb.sury.org~trusty+1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
JavaScript: http://localhost/app/plugins/redirection/redirection.js
REST API: /wp-json/

Error: Unexpected token N in JSON at position 1
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 404 Not Found
Raw: 
Notice: rest_enabled is <strong>deprecated</strong> since version 4.7.0! Use rest_authentication_errors instead. The REST API can no longer be completely disabled, the rest_authentication_errors filter can be used to restrict access to the API, instead. in /var/www/web/wp/wp-includes/functions.php on line 4605
{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment] 2019-03-02 07:53
The problem is shown in the message:

`Notice: rest_enabled is <strong>deprecated</strong> since version 4.7.0! Use rest_authentication_errors instead. The REST API can no longer be completely disabled, the rest_authentication_errors filter can be used to restrict access to the API, instead. in /var/www/web/wp/wp-includes/functions.php on line 4605`

Something is outputting that and breaking your REST API. You'll need to stop  it happening.

**Comment by johngodley** [comment] 2019-03-08 19:29
Closing for now, please reopen with more details

**Closed by johngodley** 2019-03-08 19:29 UTC
Labels: need-feedback
