### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by roboweaver** [johngodley/redirection#718] opened 2018-02-01 19:42 UTC
Updating the plugin causes this error. 

Was working prior to this update.
```
Plugin: 3.1.1
WordPress: 4.9.2 (single)
PHP: 7.1.7
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
REST API: https://workfront.local/wp-json/

Error: No route was found matching the URL and request method
Action: redirection/v1/redirect/27263/ POST
Params: {"id":27263,"url":"test3","title":"","regex":false,"match_type":"url","action_type":"url","position":7,"group_id":47,"action_code":301,"action_data":{"url":"test3"}}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment] 2018-02-02 18:52
Does this only happen when updating a redirect? Does it happen for other actions?

**Comment by roboweaver** [comment] 2018-02-03 02:05
Appears that it is also happening for adding redirects as the UX says the
insert happens, but no row shows up.

Changes also don’t show up in the DB

**Comment by johngodley** [comment] 2018-02-03 15:27
I think there is something on your server that is blocking the POST requests, but I'm unsure what. Are you running any kind of security plugins, or have any kind of proxy setup that may be doing this?

I am confused by adding a redirect shows no error, but doesn't do anything. Are you comfortable using your browsers developer console? If so, could you look at the request in the 'network' tab when you try and add a redirect, and tell me what the response is?

**Comment by roboweaver** [comment] 2018-02-05 20:04
So here's a screencast of it failing, along with the HAR from the session.

I didn't see any obvious errors, but not sure what I'd need to look at.

https://screencast.com/t/AT081kdPMCH

Note the workfront.local.oldplugin.har was a successful add, where the row
actually shows up. The second HAR also includes information from me trying
to find the rows that didn't get inserted.

Rob Weaver, PMP
Phone: (925) 456-4762
Email: rob@accuweaver.com
IM: rob.weaver@mac.com (AIM)
Twitter: accuweaver
Web site: http://www.linkedin.com/in/robweaver

**Comment by johngodley** [comment] 2018-02-06 08:26
Thanks. I dont think the HAR files made it through - Github may have filtered them out

**Comment by roboweaver** [comment] 2018-02-08 15:28
OK, I uploaded them to a repo at https://github.com/roboweaver/redirectionhar

Let me know if you need any additional debugging.

**Comment by johngodley** [comment] 2018-02-11 09:16
Thanks. Looking at that I can see that the POST requests are being redirected, which causes the data to be discarded, and so the POST fails. The redirect is probably caused by a trailing slash redirect you might have on your site.

I added a fix for this in the 3.2 beta here:

https://github.com/johngodley/redirection/releases/tag/3.2-beta

If you can try that out and let me know if it helps.

**Comment by roboweaver** [comment] 2018-02-11 14:52
Yes we have a global redirect to add trailing slashes on our site (was an
SEO decision made long ago, I think by a flip of the coin between going
with and without a trailing slash).

Thanks, I will give that a try.

Rob Weaver, PMP
Phone: (925) 456-4762
Email: rob@accuweaver.com
IM: rob.weaver@mac.com (AIM)
Twitter: accuweaver
Web site: http://www.linkedin.com/in/robweaver

**Comment by johngodley** [comment] 2018-02-17 20:09
I'll close this for now, please reopen if you still have a problem

**Closed by johngodley** 2018-02-17 20:09 UTC
