### ISSUE TITLE
Problem starting Redirection 5.3.0

### ISSUE THREAD

**Issue by aajimenezg** [johngodley/redirection#3363] opened 2022-07-22 21:51 UTC
Plugin: 5.3.0 4.2
WordPress: 6.0.1 (single)
PHP: 7.4.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
JavaScript: https://www.cmmendel.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff
REST API: https://www.cmmendel.com/wp-json/

**Comment by johngodley** [comment] 2022-07-23 04:40
As the error message should state, this is probably caused by another plugin.

**Comment by johngodley** [comment] 2022-07-28 18:33
Closing for now, please reopen with more details.

**Closed by johngodley** 2022-07-28 18:33 UTC
