### ISSUE TITLE
Problem starting Redirection 5.0.1 -- Can't update database

### ISSUE THREAD

**Issue by deznatkingcole** [johngodley/redirection#2742] opened 2021-02-04 01:16 UTC
```
Uncaught SyntaxError: Unexpected token '}' https://alifeforseniors.com/wp-content/plugins/auto-advance-for-gravity-forms/js/aafg_script.js?ver=44 134,Uncaught SyntaxError: Unexpected token '}' https://alifeforseniors.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3 2,Uncaught SyntaxError: Unexpected token '}' https://alifeforseniors.com/wp-content/themes/Avada/assets/admin/js/avada-admin-notices.js?ver=7.2.1 45,Uncaught SyntaxError: Unexpected token '}' https://alifeforseniors.com/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-patcher-admin-menu-notices.js?ver=3.2.1 1
```

Plugin: 5.0.1
WordPress: 5.6.1 (single)
PHP: 7.3.26
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
JavaScript: https://alifeforseniors.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://alifeforseniors.com/wp-json/

**Comment by johngodley** [comment] 2021-02-04 06:40
The problem is shown in the message you posted:

```
Unexpected token '}' https://alifeforseniors.com/wp-content/plugins/auto-advance-for-gravity-forms/js/aafg_script.js?ver=44
Unexpected token '}' https://alifeforseniors.com/wp-content/themes/Avada/assets/admin/js/avada-admin-notices.js?ver=7.2.1
Unexpected token '}' https://alifeforseniors.com/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-patcher-admin-menu-notices.js?ver=3.2.1 1
```
You seem to have many problems.

**Comment by johngodley** [comment] 2021-03-27 13:03
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-27 13:03 UTC
