### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Samilyjones** [johngodley/redirection#1311] opened 2018-11-29 12:44 UTC
The plugin has not been working for two weeks. You enter the redirection, it says that it has been saved but in reality it is not like that.

**Comment by johngodley** [comment] 2018-11-29 13:11
Are you using any caching software?

**Comment by Samilyjones** [comment] 2018-11-29 17:19
Yes. W3 Total Cache.

**Comment by johngodley** [comment] 2018-11-29 17:38
Ok, can you try clearing your cache or disabling it to see if it's caching the REST API?

**Comment by Samilyjones** [comment] 2018-11-29 17:47
I have tried both but the error keeps happening. It says that the redirection has been saved but it does not appear later.

**Comment by johngodley** [comment] 2018-12-09 14:44
I am unable to reproduce this. If it is possible to access your site and test it out myself then I can be contacted at https://redirection.me/contact/

**Comment by johngodley** [comment] 2018-12-27 15:49
Closing for now, please reopen with more details.

**Closed by johngodley** 2018-12-27 15:49 UTC
