### ISSUE TITLE
Redirection donest work on mobile

### ISSUE THREAD

**Issue by Evcindexcom** [johngodley/redirection#235] opened 2017-07-08 15:36 UTC
Hello
I have tried redirect plugin, it works fine on desktop but I found out it doesnt work on mobile website, Can you tell me how to fix it

**Comment by johngodley** [comment] 2017-07-08 18:24
The plugin makes no differentiation between desktop and mobile. Can you explain further how you've used the plugin and what you are experiencing?

**Comment by Evcindexcom** [comment] 2017-07-08 22:12
Try this link on desktop and mobile device 
http://www.evcindex.com/loc/%D8%B3%D9%85%D9%88%D8%AD%D8%A9/

**Comment by johngodley** [comment] 2017-07-09 07:13
That works the same on both desktop and mobile.

```
curl -v http://www.evcindex.com/loc/%D8%B3%D9%85%D9%88%D8%AD%D8%A9/                                                                                                                     
*   Trying 108.167.183.46...
* TCP_NODELAY set
* Connected to www.evcindex.com (108.167.183.46) port 80 (#0)
> GET /loc/%D8%B3%D9%85%D9%88%D8%AD%D8%A9/ HTTP/1.1
> Host: www.evcindex.com
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.12.0
< Date: Sun, 09 Jul 2017 06:16:49 GMT
< Content-Type: text/html; charset="UTF-8"
< Content-Length: 0
< Connection: keep-alive
< Vary: Cookie,Accept-Encoding
< Location: http://www.evcindex.com/loc/%d8%b9%d9%8a%d8%a7%d8%af%d8%a9-%d8%a8%d9%8a%d8%b7%d8%b1%d9%8a%d8%a9-%d9%81%d9%8a-%d8%b3%d9%85%d9%88%d8%ad%d8%a9/
```

If you are experiencing a difference then it is likely caused by a cached redirect. Clearing your browser cache should make this better.

**Comment by johngodley** [comment] 2017-07-22 11:52
Closing for now, please reopen if you still have problems

**Closed by johngodley** 2017-07-22 11:52 UTC
