### ISSUE TITLE
Cannot write titles for any redirections since v5.2

### ISSUE THREAD

**Issue by robbie-hunt** [johngodley/redirection#3204] opened 2022-01-16 13:00 UTC
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I am trying to add a title to my redirection entry.

### Actual Behavior

Anything I type into the title field doesn't appear, as if the field isn't actually taking input. This is still the case when I add the redirection and then try to edit it, to add the title - the field doesn't take any input. This is also the case for redirections with titles, I cannot edit the title.

### Steps to reproduce

- Either click "Add new" button to add a new redirection, or click edit on an already existing redirection.
- Press the cog icon to be presented with more settings, such as a title.
- Try to type in the title field.

### Environment

Brave browser v1.34.80, WordPress v5.8.3, Redirection v5.2

**Comment by ulfemsoy** [comment] 2022-01-19 08:11
I'm experiencing the same issue. Please fix.
The Title field is read-only when adding new entries, or changing existing.

**Comment by Estes-GG** [comment] 2022-01-19 22:40
I am having the same issue where the Title Field will not allow inputs or updates.

**Comment by rospencers** [comment] 2022-01-20 04:02
I repro this in Chrome Version 97.0.4692.71 / WIndows 10

Developer toolbar console reports the following JS error when attempting to enter text in that field:

`redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2 
Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at a.value (redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:700369)
    at redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:698411
    at onChange (redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:674869)
    at Object.qe (redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:198137)
    at Qe (redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:198291)
    at redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:216494
    at Cr (redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:216588)
    at jr (redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:217002)
    at redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:222638
    at Fe (redirection.js?ver=5.2.1-362a7b508b55b6394c903b3b4622d575:2:297930) `

**Comment by small-fork** [comment] 2022-01-21 16:43
I had created a ticket for this issue before realizing this ticket existed. I closed mine and figured I'd add my info on this ticket instead:

### Summary

Since the recent update to version 5.2.1, I'm finding I'm unable to type anything in the optional "Title" field of the plugin. I can type in all other fields, but when attempting to enter a title, I cannot. 

### Actual Behavior

While I can insert my cursor into the Title field, typing does not result in anything populating the field. This is also the case if I Edit a previous redirection that has a title. I'm unable to edit the title, though I can put my cursor into the field.

### Steps to reproduce

Attempt to add anything into the title field.

### Environment

Redirection version 5.2.1
WordPress 5.8.3
Tried on Chrome Version 97.0.4692.71 (Official Build) (x86_64)
Tried on Vivaldi 5.0.2497.43 (Stable channel) (x86_64)
Tried on Firefox 96.0.2

--

Thank you!

**Comment by johngodley** [comment] 2022-01-22 08:19
Fixed in version 5.2.2

**Closed by johngodley** 2022-01-22 08:19 UTC
