### ISSUE TITLE
I can't finish the configuration of the plugin redirection

### ISSUE THREAD

**Issue by Holdencfield** [johngodley/redirection#3367] opened 2022-07-25 01:49 UTC
To help track down issues, follow this template. If you can provide screenshots that will help.

*Replace this template with your own data!*

### Summary

I'm trying to activate the plugin, finishing configuring it but I can't finish getting past the basic configuration.

### actual behavior

After finishing the basic configuration in the plugin, I click the continue button and nothing else appears, the wordpress menu continues to work but no more plugin configurations appear, only the background remains.

### Steps to play

I enter the redirection welcome, start configuration, click on the options and click on continue, then nothing, nothing else appears, the API menu does not appear

### Ambient

Google Chrome browser, Chrome version 103.0.5060.134
Wordpress version 6.0.1 and redirect version 5.3.0

![image](https://user-images.githubusercontent.com/109931067/180677745-682612ac-7b4c-47ab-8fa6-ee506e3a18d0.jpg)

![image(1)](https://user-images.githubusercontent.com/109931067/180677757-cc845a20-108a-409c-9ddb-917d4f045bf2.jpg)

**Comment by johngodley** [comment] 2022-07-26 07:30
I'm unable to reproduce this. Are there any errors in your browser's developer console?

**Comment by Holdencfield** [comment] 2022-07-26 18:45
Good afternoon John, thanks for answering.

The hosting and the page is new so I don't see it possible that they are
errors, I also tried deactivating all the plugins but the result was the
same, I don't know if the problem is the API REST

I am looking forward to your response

**Comment by johngodley** [comment] 2022-07-26 19:47
Your hosting being new won't affect errors appearing in your browser's developer console.

You can find details here: https://redirection.me/support/reporting-bugs/

**Comment by mauricioxpl** [comment] 2022-07-28 22:43
I had the same error and checking on console there's an issue with redirection.js (attached). What worked for me was to install version 5.2. So I guess there's something wrong with version 5.3

<img width="776" alt="Screen Shot 2022-07-28 at 17 41 08" src="https://user-images.githubusercontent.com/18059852/181649245-c945c81c-7428-40b0-a9a3-f54c2cd4e60d.png">
s

**Comment by johngodley** [comment] 2022-07-29 05:00
> So I guess there's something wrong with version 5.3

Installing 5.2 doesn't help solve the problem though, and it doesn't occur for everyone.

**Comment by johngodley** [comment] 2022-07-29 06:27
Based on the screenshots above it seems the problem is caused by the Spanish language file.

**Comment by johngodley** [comment] 2022-07-29 08:24
This should now be fixed in version 5.3.1

**Closed by johngodley** 2022-07-29 08:24 UTC

**Comment by Holdencfield** [comment] 2022-07-29 15:23
It's true, the problem has already been fixed! thank you very much for your
help
