### ISSUE TITLE
Problem starting Redirection 2.10.1

### ISSUE THREAD

**Issue by brandonrh** [johngodley/redirection#613] opened 2018-01-10 15:55 UTC
Plugin: 2.10.1
WordPress: 4.9.1
PHP: 7.1.11-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by johngodley** [comment] 2018-01-11 17:47
Can you open your browser's developer console and see if any errors are shown?

**Comment by brandonrh** [comment] 2018-01-11 18:27
No issues in the console. I can also visit redirection.js in the browser.

**Comment by johngodley** [comment] 2018-01-14 15:12
The error is shown when Redirection is unable to load. As the error message states, this is usually caused by another plugin interfering with Redirection. If you haven't already you can try temporarily disabling other plugins and see if that has any effect.

It may also be caused by an incomplete plugin installation. The error page will show the URL to `redirection.js`, which you can check exists. I have seen in some cases that this file is corrupted, so if you paste the URL here I can check.

**Comment by johngodley** [comment] 2018-02-17 10:17
Version 3.2 was released so I'm going to close this for now. If the problem still persists can you reopen or create a new issue

**Closed by johngodley** 2018-02-17 10:17 UTC
