### ISSUE TITLE
JSON.parse: unexpected character at line 1 column 1 of the JSON data ---> Servererror 500 on VERSION 5.3

### ISSUE THREAD

**Issue by stefanvr82** [johngodley/redirection#3378] opened 2022-08-02 08:14 UTC
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)

### Summary

today redirection plugin got automatically updated and there is now a error 500 on every page despite homepage of my wordpress installation 

server protokoll log contains:
AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration 
error. Use 'LimitInternalRecursion' to increase the limit if necessary.

### Actual Behavior

500 Servererror on every relative urls 

### Steps to reproduce

install Version 5.3 and try it ... 

### Environment

wordpress uptodate, plugin version 5.3 (with 5.2 it worked flawelessly)

**Comment by johngodley** [comment] 2022-08-02 08:28
This is specific to your site. Look for redirects causing an infinite loop and remove them. 

Use https://redirection.me/support/disable-redirection/ to disable redirects

**Comment by stefanvr82** [comment] 2022-08-02 08:29
it was fine before now its not ... only thing changed was the automatic update. what changed?

**Comment by johngodley** [comment] 2022-08-02 08:32
The plug-in is working fine for other people. I don’t know what has happened to your site but you can follow the above steps to find out

**Comment by stefanvr82** [comment] 2022-08-02 08:36
i monitor every change on the the plugins and site itself ... there is only your hidden auto update feature that changed the your plugin REDIRECTION despite me having the "automatic update function" built into wordpress switched to "OFF" ... so actually the only thing that changed was your plugin updating to version 5.3 ... thats it. im glad it works for "other" people ...but for me thats not helpfull at all.

**Comment by johngodley** [comment] 2022-08-02 08:54
There is no hidden update feature in the plug-in and it has no ability to update itself. Have you followed my instructions?

**Comment by stefanvr82** [comment] 2022-08-02 08:56
<img width="1113" alt="Bildschirmfoto 2022-08-02 um 10 56 08" src="https://user-images.githubusercontent.com/84027435/182335173-81d835e6-86c6-4a57-852e-6015729707a4.png">

**Comment by stefanvr82** [comment] 2022-08-02 09:03
i checked again ... auto update was actually ON ... my mistake sorry. 

i rolled back the complete instance to the state before the update from Version 5.2.3 to Version 5.3.1 ... now im running version 5.2.3 and the website performs fine. its clearly a problem with a change in version 5.3.1 (or anything in between) thats redirect causing the issue.

**Comment by stefanvr82** [comment] 2022-08-02 09:05
i will dig deeper now. if i find the problem i will update this issue ... for now i cant update to version 5.3.1 ...

**Comment by stefanvr82** [comment] 2022-08-02 09:47
ok, update: i had 4 plugins to be updated... plus redirection plugin... i narrowed it down one by one ... updated all 4 ... now its only redirection plugin thats due to update from version 5.2.3 to 5.3.1 ... i WONT do that as we know from above that this causes Server Error 500 do to a different way of parsing redirection urls ... i made a copy of version 5.2.3 folder and compared it to the version 5.3.1 folder ... there are few changes i cant quite get but u truely changed things relating to redirect behaviour and json file management... on one point it even says " The Value to set JSON" whats also a problem showing by using the standard rest api ... see files attached ... 

so we still have this issues: 


### Plugin Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError) 
### Server Error: AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration
### error. Use 'LimitInternalRecursion' to increase the limit if necessary
 
![Bildschirmfoto 2022-08-02 um 11 44 13](https://user-images.githubusercontent.com/84027435/182345717-80d070d7-a4b4-4d4e-927f-19e0ab8a61af.png)

![Bildschirmfoto 2022-08-02 um 11 30 13](https://user-images.githubusercontent.com/84027435/182345745-6d40f334-33e6-4ffa-803c-a8c678c20e1e.png)

<img width="1068" alt="Bildschirmfoto 2022-08-02 um 09 32 31" src="https://user-images.githubusercontent.com/84027435/182345779-db7b992d-c849-49f9-8271-4ab1770dc374.png">

maybe i missed some release notes of what i have to change to the site so please update me and tell me what to do. with 5.2.3 its running great ...

**Comment by johngodley** [comment] 2022-08-02 15:15
I am aware of the changes in the plugin, and none of them are related to a JSON error. That is caused by the 500 error.

If you can follow my original instructions then it might be possible to investigate further. I mentioned that it works for other people to indicate that there is not a general problem with the plugin, and no one else has reported this issue. This suggests the problem is specific to your site.

**Comment by stefanvr82** [comment] 2022-09-06 06:59
... is there a option to trace all redirects made to see in detail what the system does?

**Comment by johngodley** [comment] 2022-09-06 07:02
Going back to what I originally asked, can you follow https://redirection.me/support/disable-redirection/ to disable redirects. Then we can work backwards and see what is happening.

**Comment by stefanvr82** [comment] 2022-09-06 07:04
i can login i dont need to deactivate your plugin. this issue is specific on all pages "below" wordpress base url ... if i click on any internal link besides homepage its showing me error 500.

**Comment by stefanvr82** [comment] 2022-09-06 07:05
if i roll back to yesterday its fine... it seams there is a storrage or some kind of quota limit which - after its full - triggers this error. it works for days and then i have to reset. im so lost...

**Comment by johngodley** [comment] 2022-09-06 07:11
It would really help if you can just follow my instructions. Please, it would make this so much easier and allow me to actually help. I'm not asking you to do this for no reason, and it means I can cross off some things.

**Comment by stefanvr82** [comment] 2022-09-06 07:18
i understand that. i dont want to annoy you ... and if this sounds like that im sorry english is not my main language as u already might have guessed. :) 

this is a live website translated in 9 languages with active users trying to buy something and i cant just deactivate randomly and lose them at checkout page. if i deactivate the plugin the error is gone ... but i cant see how that can help me  ... i need the redirects to guide users to the correct named urls ... also for seo and many other reasons... 

i try to understand the issue ... and if there would be a list or trace of what actually happens if i open a specific url that would make the bugfixing much easier ... 

i tried all three api options... all are showing the json issue if the site is broken ...  and now after some seconds there is no issue and everything is fine. the json error is gone...

**Comment by stefanvr82** [comment] 2022-09-06 07:22
the fact, that the error is poping up randomly and is active for some time and then disapears again rly bothers me. are there any limits/ pools or quota like things that need to be flushed regulary? maybe at server side ... some apache redirection stuff? ... i ask my hosting provider and shared all information also with him ... he is looking into it ... 

also im running premium wp rocket caching plugin ... i always clear cache and rebuilt preloaded pages after i change anything in you redirection plugin. could be that the process to refill the cache is taking a long time due to many pages... and there is a conflict with wp rocket?

**Comment by johngodley** [comment] 2022-09-06 07:55
You would only need to disable the plugin temporarily and it means we can find out if having the plugin running is causing a problem, or something it is redirecting.

Caches often cause temporary problems, as do language plugins. You have both so it's a good bet that one of them might be involved. What you have described does not sound like it is caused by Redirection.

**Comment by stefanvr82** [comment] 2022-09-06 07:59
deactivating it in wordpress plugin folder is not the same as using the redirection-deactivate.txt?

**Comment by johngodley** [comment] 2022-09-06 08:05
No it is not.

**Comment by stefanvr82** [comment] 2022-09-06 08:25
i added the txt and now? as the error is not there anymore how does that help?

**Comment by johngodley** [comment] 2022-09-06 08:26
You will need to do it when the error is there.

**Comment by stefanvr82** [comment] 2022-09-06 08:28
makes sense ... so i wait until the system is down again... 

question: is there a way to trace all steps taken to get from url1 -> url2 and SEE all redirects that occured?

**Comment by johngodley** [comment] 2022-09-06 08:37
The redirect checker will do that:

https://redirect.li/http/

**Comment by stefanvr82** [comment] 2022-09-06 08:45
ok, i did that on one random url ... its green but shows: 

Problems were detected with this header

    Duplicate header. There is another header with this name and this may cause problems.

**Comment by stefanvr82** [comment] 2022-09-06 08:45
can i send u private messages here? so i can give u the url i refering too? dont want to share that public.

**Comment by stefanvr82** [comment] 2022-09-06 08:50
[Vary](https://redirect.li/http/headers/vary/)
 **Accept-Encoding**
 Indicates that different content may be provided to different clients, depending on the vary header.

        Headers
            Accept-Encoding

Problems were detected with this header

    Duplicate header. There is another header with this name and this may cause problems.

**Comment by johngodley** [comment] 2022-09-06 08:52
Duplicate headers are not going to cause this problem. My contact details are in the plugin on the support page.

**Comment by johngodley** [comment] 2022-12-03 11:14
Closing for now please reopen with more details.

**Closed as completed by johngodley** 2022-12-03 11:14 UTC
