### ISSUE TITLE
Breaks site commenting

### ISSUE THREAD

**Issue by lifelightweb** [johngodley/redirection#733] opened 2018-02-05 19:15 UTC
### Summary

In wordpress version 4.9.2, when this plugin is activated, comments DO NOT work.  The comment is never logged/saved from the front end.  I tested every plugin before determining it was this one.

### Actual Behavior

see above

### Steps to reproduce

You can demonstrate the issue on my website, http://www.heiditown.com BUT only after I re-enable the plugin.  Right now it is disabled.  Please contact me for site access to demonstrate.

### Environment

Tested all browsers -- action same in all, chrome, opera, i.e., firefox.

**Comment by johngodley** [comment] 2018-02-05 19:44
I'm not able to reproduce a problem with comments, and there's no similar report. Do you have a redirect that may be interfering with the WordPress comments function? That could be a likely cause

I can certainly take a look

**Comment by lifelightweb** [comment] 2018-02-06 16:01
Send me your private email address as I will set you up with a user.  I don’t want to post that on the forum for github, however for security reasons.

 

Debra

**Comment by johngodley** [comment] 2018-02-06 18:04
My email is on the support page of the plugin, or you can use https://redirection.me/contact/ - thanks!

**Comment by johngodley** [comment] 2018-02-17 15:55
Closing for now, please reopen with more details

**Closed by johngodley** 2018-02-17 15:55 UTC
