### ISSUE TITLE
Redirection Error - Cant delete redirect 

### ISSUE THREAD

**Issue by 101sam** [johngodley/redirection#3115] opened 2021-10-31 18:37 UTC
Redirection Error - Cant delete redirect 
We try to drop tables,
We try to delete plugin
Every time we re-install it same redirects coming back

```
Plugin: 5.1.3 4.2
WordPress: 5.8.1 (single)
PHP: 7.4.24
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
JavaScript: https://kidsontheyard.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://kidsontheyard.com/wp-json/
Query: ?page=redirection.php

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}
```

**Comment by johngodley** [comment] 2021-10-31 18:39
This is caused by an aggressive cache on your site. You should exclude your REST API /wp-json/ from your cache

**Comment by 101sam** [comment] 2021-10-31 18:45
We disabled all cache - still same problem

**Comment by johngodley** [comment] 2021-10-31 18:52
This is caused by a cache on your site. There is no other reason for it to happen. You may have multiple caches, and there may be caches you are unaware of.

If you delete the plugin and remove then tables then it is absolutely a cache issue.

**Comment by 101sam** [comment] 2021-10-31 18:53
OK we will remove all tables, give it 24 hours and see again

**Comment by johngodley** [comment] 2021-12-22 10:56
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-12-22 10:56 UTC
