### ISSUE TITLE
Problem starting Redirection 3.7.2

### ISSUE THREAD

**Issue by brianpcombs** [johngodley/redirection#1429] opened 2019-01-28 15:38 UTC
Plugin: 3.7.2
WordPress: 5.0.3 (single)
PHP: 7.2.14
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15
JavaScript: http://www.my3bc.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.my3bc.com/wp-json/

**Comment by brianpcombs** [comment] 2019-02-04 16:18
![screen shot 2019-02-04 at 10 15 47 am](https://user-images.githubusercontent.com/29441179/52221152-2be95d00-2866-11e9-8704-29b3effc296f.png)
![screen shot 2019-02-04 at 10 15 58 am](https://user-images.githubusercontent.com/29441179/52221153-2c81f380-2866-11e9-82f6-29e0301aff5b.png)

Let me know if this answers your questions, please.

**Comment by johngodley** [comment] 2019-02-04 16:22
It does. You can see that there are a big bunch of files that cannot be loaded, and I imagine this is affecting lots of plugins.

One of these files is Redirection:

http://www.my3bc.com/wp-content/plugins/redirection/redirection.js

You will need to fix whatever the problem is.

**Comment by johngodley** [comment] 2019-02-15 19:20
Closing for now, please reopen with more details

**Closed by johngodley** 2019-02-15 19:20 UTC
Labels: need-feedback
