### ISSUE TITLE
Problem starting Redirection 5.2.3

### ISSUE THREAD

**Issue by SharonGSH** [johngodley/redirection#3313] opened 2022-06-10 09:39 UTC
Plugin: 5.2.3 4.2
WordPress: 6.0 (single)
PHP: 8.0.18
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
JavaScript: https://www.pgeon.delivery/my/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://www.pgeon.delivery/my/en/wp-json/

**Comment by johngodley** [comment] 2022-06-18 11:56
The error page should contain more details. This is caused by something else running on your site, such as another plugin.

**Comment by johngodley** [comment] 2022-06-25 10:12
Closing for now, please reopen with more information

**Closed by johngodley** 2022-06-25 10:12 UTC
