### ISSUE TITLE
After plugin update rewrite_rules in wp_options are empty

### ISSUE THREAD

**Issue by burdyga** [johngodley/redirection#1807] opened 2019-06-10 06:59 UTC
Last few versions of plugin break my website. I just update plugin and see just home page at any link i clicked. Then I tried find a problem and i found it. It was cleared rewrite_rules option in wp-option table. I wrote the value from backup and site came to live.

I use last wordpress, custom theme.

**Comment by johngodley** [comment] 2019-06-10 07:07
There is nothing in the plugin that affects rewrite_rules, and no reports from anyone else of anything similar:

https://github.com/johngodley/redirection/search?q=rewrite_rules&unscoped_q=rewrite_rules

I would be very surprised if this problem was directly caused by the plugin.

Are you running anything else that might affect your rewrite rules?

**Comment by burdyga** [comment] 2019-06-10 07:10
I didn't update anything else. And I had JSON errors  and REST API like guys from other issue reports.

**Comment by johngodley** [comment] 2019-06-10 07:15
Ok, but the other reports are not because of rewrite_rules, and their websites are not broken.

What version did you update from and to? For the majority of updates nothing happens in the plugin at all. It is WordPress itself that performs the update.

**Comment by burdyga** [comment] 2019-06-10 07:29
I don't know what was a caused. Your plugin or Wordpress's update engine. I just find the broken place for my website. Maybe this info will help someone.

I updated from 4.2.3 to 4.3.1

**Comment by johngodley** [comment] 2019-06-10 08:18
The plugin doesn't change anything between 4.2.3 and 4.3.1.

The upgrade is handled by WordPress, and the plugin has no ability to change rewrite_rules (the above link shows that it doesn't exist in the code). In fact, at no point in the entire history of the plugin has it had this ability, and no one has ever reported this problem before.

I don't want to come across as dismissive, but the chance this is the plugin is very very small. It is much more likely that something else on your site (another plugin, your theme, WordPress etc) changed the rewrite rules. Why this might coincide with updating Redirection I don't know - maybe it's something that happens as a part of the plugin update process, maybe it's just coincidence.

I appreciate you reporting this, however I would suggest you investigate further. I will close this for now, but if you find a way to reproduce the problem, and find conclusively that it is Redirection, please reopen.

**Closed** 2019-06-14 05:35 UTC
