### ISSUE TITLE
Clearing cache to upgrade database not working

### ISSUE THREAD

**Issue by laurenmb** [johngodley/redirection#1596] opened 2019-03-25 15:31 UTC
I logged into our Wordpress admin area today to update plugins and noticed Redirection was prompting me to upgrade our database. Asked to clear the browser cache then reload the page, which did not do anything.

From here I have:
-Cleared browser cache
-Cleared server cache via Flywheel
-Cleared W3 Total Cache file
^Tried reloading the Redirection page after all these and still did not change

-Disabled any sort of caching or optimization plugin (W3 Total Cache, PageSpeed Ninja, Speed Booster Pack, WP-Optimize)
-Cleared server and browser cache again
^Reloaded the Redirection upgrade page and still can't upgrade

Not sure what else I can try to get it to upgrade. Here is the info displayed on the upgrade page:

Plugin: 4.1.1
WordPress: 5.1.1 (single)
PHP: 7.2.16-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
JavaScript: https://techvera.com/wp-content/plugins/redirection/redirection.js
REST API: https://techvera.com/wp-json/
Buster: 3.7.3 === 4.1.1

false

**Comment by johngodley** [comment] 2019-03-26 07:51
You can see the version that is being loaded: `3.7.3`

That's the old version. I don't know why it is appearing on your site, but it is definitely caused by a cache. If you try adding something random to the Redirection URL like `&v=1` then it might help

**Comment by johngodley** [comment] 2019-03-30 14:16
Closing for now, please reopen with more details

**Closed by johngodley** 2019-03-30 14:16 UTC
