### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by lillyskywalker** [johngodley/redirection#3168] opened 2021-12-14 09:16 UTC
```
Plugin: 5.1.3 4.2
WordPress: 5.8.2 (single)
PHP: 7.4.15
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
JavaScript: https://www.artsite.com.au/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://www.artsite.com.au/wp-json/
Query: ?page=redirection.php

Action: https://www.artsite.com.au/wp-json/redirection/v1/plugin/data/ POST
Code: 500 Internal Server Error

Error: JSON Parse error: Unrecognized token '<' (SyntaxError)
Raw: <HTML> <HEAD> <TITLE>500-internal server error</TITLE> </HEAD><BODY> <H1> Error occurred: 500 - internal server error</H1><HR><ADDRESS> Apache Server at: d1166753-44534.myweb.iinethosting.net.au</ADDRESS></BODY> </HTML>
```
<img width="1905" alt="Screen Shot 2021-12-14 at 8 10 03 pm" src="https://user-images.githubusercontent.com/96031450/145968191-e7d9a656-359c-4513-8405-cdf958b4c543.png">

Hi I have a redirect that is going to the wrong place and is causing a loop - I tried to delete the redirect but it did not work so deleted de-activated plugin then reactivated and this happened?
I dont know how to find the misdirection it says too many redirects but I can manually edit if I cannot fix it any other way if you tell me where the deleted redirects are stored?

**Comment by johngodley** [comment] 2021-12-22 11:46
The error is not caused by a redirect. You seem to have fixed it now so I will close this issue.

**Closed by johngodley** 2021-12-22 11:46 UTC
