### ISSUE TITLE
Problem starting Redirection 4.6.2

### ISSUE THREAD

**Issue by ldfreeman3** [johngodley/redirection#2178] opened 2020-02-14 03:39 UTC
Plugin: 4.6.2
WordPress: 5.3.2 (single)
PHP: 5.6.38
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
JavaScript: http://trustedlegalteam.com/wp-content/plugins/redirection/redirection.js
REST API: http://trustedlegalteam.com/wp-json/

**Comment by johngodley** [comment] 2020-02-14 08:06
Can you open your browser's developer console and see if more information is shown? This is almost certainly caused by another plugin.

**Comment by johngodley** [comment] 2020-02-16 16:25
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-02-16 16:25 UTC
