### ISSUE TITLE
Problem starting Redirection 4.9

### ISSUE THREAD

**Issue by karol-preiskorn** [johngodley/redirection#2520] opened 2020-10-27 12:39 UTC
Plugin: 4.9
WordPress: 5.5.1 (single)
PHP: 7.3.14
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
JavaScript: https://www.ultimasolution.pl/wp-content/plugins/redirection/redirection.js?ver=4.9-c383de96c0b7e38459253ead4f6e9b10
REST API: https://www.ultimasolution.pl/wp-json/

**Comment by johngodley** [comment] 2020-10-27 12:40
Please open your browser's developer console and see what information is shown. This is almost certainly caused by another plugin.

**Comment by johngodley** [comment] 2020-11-08 17:37
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-08 17:37 UTC
