### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by websmartcoder** [johngodley/redirection#1673] opened 2019-04-15 17:09 UTC
```
Plugin: 4.1.1
WordPress: 5.1.1 (single)
PHP: 7.2.17
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://starletoverseas.com/wp-content/plugins/redirection/redirection.js
REST API: https://starletoverseas.com/wp-json/

Error: Unexpected token T in JSON at position 0
Raw: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

Error: Unexpected token T in JSON at position 0
Raw: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

**Comment by johngodley** [comment] 2019-04-15 17:16
The problem is shown above. Your WordPress REST API is not working:

https://starletoverseas.com/wp-json/

**Comment by johngodley** [comment] 2019-04-19 12:38
Closing for now, please reopen with more information

**Closed by johngodley** 2019-04-19 12:38 UTC
Labels: need-feedback
