### ISSUE TITLE
Problem starting Redirection 5.3.5

### ISSUE THREAD

**Issue by imnotemjay** [johngodley/redirection#3475] opened 2022-11-19 02:37 UTC
```
Uncaught SyntaxError: Unexpected identifier 'use' http://mheljaybuenaflor.local/wp-content/plugins/redirection/redirection.js 2
```

Plugin: 5.3.5 4.2
WordPress: 6.1.1 (single)
PHP: 8.1.9
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
JavaScript: http://mheljaybuenaflor.local/wp-content/plugins/redirection/redirection.js?ver=5.3.5-f0dac5b2b3267cd737c1a679e4c1fac3
REST API: http://mheljaybuenaflor.local/wp-json/

**Comment by johngodley** [comment] 2022-11-19 07:31
This is probably caused by another plugin on your site.

**Comment by johngodley** [comment] 2022-11-26 12:31
Closing for now, please reopen with more information.

**Closed as completed by johngodley** 2022-11-26 12:31 UTC
