### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by pradjadj** [johngodley/redirection#1500] opened 2019-02-23 18:18 UTC
```
Plugin: 4.0
WordPress: 5.1 (single)
PHP: 7.2.12
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
JavaScript: http://japanesemusicid.com/wp-content/plugins/redirection/redirection.js
REST API: http://japanesemusicid.com/wp-json/

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```

**Comment by johngodley** [comment] 2019-02-23 18:19
Are you running any kind of security plugin?

https://redirection.me/support/problems/rest-api/

**Comment by pradjadj** [comment] 2019-02-23 18:32
I think, I don't use security plugin..

I just updated my wordpress to 5.1 and it happened like that

**Comment by johngodley** [comment] 2019-02-23 19:51
Ok. Something on your server is blocking your WordPress REST API. This is typically caused by security software. Please investigate your setup - something is blocking Redirection.

**Comment by johngodley** [comment] 2019-03-02 11:29
Closing for now, please reopen with more details

**Closed by johngodley** 2019-03-02 11:29 UTC
Labels: need-feedback
