### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by jerepaajanen** [johngodley/redirection#2236] opened 2020-04-04 10:35 UTC
```
Plugin: 4.7.1
WordPress: 5.4 (single)
PHP: 7.2.29
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
JavaScript: https://kaikuhealth.com/wp-content/plugins/redirection/redirection.js
REST API: https://kaikuhealth.com/wp-json/

Error: Unexpected token < in JSON at position 4 (SyntaxError)
Action: redirection/v1/redirect/?orderby=id&per_page=200 GET
Code: 403 Access Forbidden
Raw:     <!DOCTYPE html>
    <html style="height: 100%;">
    <head>
        <meta charset="UTF-8">
        <title>403 Access Forbidden</title>
        <style>
            @media screen and (max-width: 800px) {
                body > div > div > div div {
                    display: block !important;
                    padding-right: 0 !important;
                }

                body {
                    text-align: center !important;
                }
            }
        </style>
    </head>
    <body style="height: 90%;">
    <div style="display: flex; align-items: center; justify-content: center; height: 90%;">
        <div style="background-color: #eee; width: 70%; border: solid 3px #ddd; padding: 1.5em 3em 3em 3em; font-family: Arial, Helvetica, sans-serif;">
            <div style="display: table-row;">
                <div style="display: table-cell; font-size: 150px; color: red; vertical-align: top; padding-right: 50px;">
                    &#9995;
                </div>
                <div style="display: table-cell; vertical-align: top;">
                    <h1 style="margin-top: 0;">We're sorry, you are not allowed to proceed</h1>
                    <p>Your request looks suspiciously similar to automated requests from spam posting software or it has been denied by a security policy configured by the website administrator.</p>
                    <p>If you believe you should be able to perform this request, please let us know.</p>
                    <p style="margin-top: 2em;">
                    <pre style="color: #777">RID: VCBMWIEEZ5HGSWDQN708LJQL</pre>
                    </p>
                </div>
            </div>
        </div>
    </div>
    </body>
    </html>
	
```

**Comment by johngodley** [comment] 2020-04-04 10:56
The problem is shown above - https://kaikuhealth.com/wp-json/ is returning a 403 error. I think this is caused by WP Cerber.

**Comment by johngodley** [comment] 2020-04-10 13:07
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-04-10 13:07 UTC
