### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by ravismakwana** [johngodley/redirection#2702] opened 2021-01-16 10:13 UTC
Plugin: 4.9.2
WordPress: 5.6 (single)
PHP: 7.4.14
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
JavaScript: https://www.allgenericpills.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.allgenericpills.com/wp-json/

**Comment by johngodley** [comment] 2021-01-16 12:22
Please follow the onscreen instructions. This is likely caused by another plugin.

**Comment by johngodley** [comment] 2021-01-25 07:57
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-01-25 07:57 UTC
