### ISSUE TITLE
Redirection connectio break

### ISSUE THREAD

**Issue by MMWEBdev123** [johngodley/redirection#3554] opened 2023-02-17 09:46 UTC
Hello, 
I have had the redirection set up from the example page: www.123.com/ to  www.123.com/hello, all worse fine now, but once every other day it just stops working and stays in www.123.com and then my client is very frustrated telling me that the page is not working. 
Is it possible to fix the break somehow?

My settings are: Exact match in any order, ignore cash and ignore slash 

I am using Chrome, version of WordPress 6.1.1, and Redirection plugin Version 5.3.9 | By John Godley.

**Comment by johngodley** [comment] 2023-02-17 09:47
What example page?

Any sporadic behaviour will be caused by a cache on the site.

**Comment by MMWEBdev123** [comment] 2023-02-17 10:50
This

> What example page?
> 
> Any sporadic behaviour will be caused by a cache on the site.

This is the page: https://teamfor.lv/ I redirected it to https://teamfor.lv/neizmantotais-potencials/

Now it works, but at least 20x times a week it does not redirect https://teamfor.lv/  to  https://teamfor.lv/neizmantotais-potencials/


It is not only me who has the problem it is other web visitors.

**Comment by johngodley** [comment] 2023-02-17 10:52
Ok, as I said, you should investigate any caches you have. That URL is not being redirected by Redirection either.

**Comment by johngodley** [comment] 2023-03-04 13:57
Closing for now please reopen with more details.

**Closed as completed by johngodley** 2023-03-04 13:57 UTC
