### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Kayden0407** [johngodley/redirection#2345] opened 2020-06-16 06:44 UTC
```
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.1.31
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4173.0 Safari/537.36
JavaScript: https://service.fruittybob.com/wp-content/plugins/redirection/redirection.js
REST API: https://service.fruittybob.com/wp-json/

Error: Briefly unavailable for scheduled maintenance. Check back in a minute. (wp_die)
Action: redirection/v1/group/ GET
Code: 503 Service Unavailable
Raw: {"code":"wp_die","message":"Briefly unavailable for scheduled maintenance. Check back in a minute.","data":{"status":503},"additional_errors":[]}
```

**Comment by johngodley** [comment] 2020-06-16 06:45
The problem is shown above:

`Briefly unavailable for scheduled maintenance. Check back in a minute. (wp_die)`

**Comment by johngodley** [comment] 2020-06-29 05:32
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-06-29 05:32 UTC
