### ISSUE TITLE
Duplicate entry should not be allowed

### ISSUE THREAD

**Issue by maamirh** [johngodley/redirection#3409] opened 2022-09-09 10:03 UTC
Duplicate entry should not be allowed. I just export a CSV file and found there were a number of duplicate entries. There should be a check when adding URL to confirm whether the URL exists before or not.

![image](https://user-images.githubusercontent.com/46965638/189325573-1ab73d64-b316-4d6c-9907-1386074ce8f8.png)

**Comment by johngodley** [comment] 2022-09-09 10:49
Closing as a duplicate of #82

**Closed as completed by johngodley** 2022-09-09 10:49 UTC
