### ISSUE TITLE
Redirection Error: "Something went wrong"

### ISSUE THREAD

**Issue by BGerling** [johngodley/redirection#2486] opened 2020-10-15 15:05 UTC
Since I upgraded from WP 5.4.2 to WP 5.5.1, when I try to add a new URL redirect, I get this error message: 

```
Something went wrong 🙁
Redirection is not working. Try clearing your browser cache and reloading this page.  If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.
If that doesn't help, open your browser's error console and create a new issue with the details.
Please mention redirect, and explain what you were doing at the time

Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.3.23-he.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.123 Safari/537.36
JavaScript: https://www.customersite-xyz.de/mgh/wp-cnt/plugins/redirection/redirection.js
REST API: https://www.customersite-xyz.de/mgh/wp-json/
Buster: 4.8 === 4.8

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    in div
    in a
    in p
    in div
    in StrictMode
    in a
    in p
    in StrictMode
    in G
    in Kb
```
(I am actually using the Vivaldi Browser, latest version)

On reloading the redirection plugin, I see the newly created entry in the list, but it does not work on the live site.

An identical message appears when I delete that newly created entry, and on reloading, it disappears from the list as expected. 

I am not using a page caching plugin, but cleared the Autoptimize cache. And it does not matter if the REST API is set to restriced or not in my security plugin: the error message is the same.  (So far the restricted REST API was never an issue)

What else can I try?

**Comment by johngodley** [comment] 2020-10-15 16:27
I'm not able to reproduce this. What other plugins do you have running? Are the above URLs real or made up? I'm curious about the `wp-cnt`

**Comment by BGerling** [comment] 2020-10-16 09:54
The customersite-xyz.de is made up, the /mgh/ subdirectory contains the site that has the problem, "wp-cnt" is real and instead of the usual "wp-content". There are many plugins on this site (it has been around for 8 years already) but before upgrading to WP 5.5.1 (only very recently) this problem has not occurred.

-----Ursprüngliche Nachricht-----
Von: John <notifications@github.com> 
Gesendet: Donnerstag, 15. Oktober 2020 18:28
An: johngodley/redirection <redirection@noreply.github.com>
Cc: BGerling <info@start-studio.net>; Author <author@noreply.github.com>
Betreff: Re: [johngodley/redirection] Redirection Error: "Something went wrong" (#2486)

I'm not able to reproduce this. What other plugins do you have running? Are the above URLs real or made up? I'm curious about the wp-cnt

**Comment by johngodley** [comment] 2020-10-16 12:19
Are you using any browser extensions, maybe translation ones?

**Comment by BGerling** [comment] 2020-10-16 14:29
I am using WordPress in the "German_formal" language version (does that make a difference in WP 5.5.1?). Oh ... I am disallowing anything "Gutenberg".

**Comment by johngodley** [comment] 2020-10-17 09:06
Does this apply to your situation? https://github.com/johngodley/redirection/issues/2487

**Comment by BGerling** [comment] 2020-10-17 15:28
I don't think so. The WP german_formal version does not change the contents.

**Comment by johngodley** [comment] 2020-10-17 15:39
That may be so, but what I'm asking is if a browser extension like Google translate may be affecting the page.

**Comment by BGerling** [comment] 2020-10-17 16:16
No, I don't use google translate extension (I rather opt-out google etc., and block adds, pop-ups etc.) or anything translation related in my browser extensions (I will try with a notebook tomorrow and see if there is a difference, but also on that device there are no translation related browser extensions.)

**Comment by johngodley** [comment] 2020-10-17 16:22
Are there any extensions at all? The error is almost certainly caused by something specific to your browser

**Comment by BGerling** [comment] 2020-10-17 21:38
Yes, 30+ extensions on my usual browser.

**Comment by johngodley** [comment] 2020-10-18 06:19
Wow, that's a lot. I suspect one of those is causing the problem.

**Comment by johngodley** [comment] 2020-10-24 18:41
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-10-24 18:41 UTC

**Comment by BGerling** [comment] 2020-10-24 19:35
Hello John, good evening! 

sorry for discontinuing my checking. My Dad was in a severe condition. As of this moment, after a several more WordPress plugins received updates during the last week, Redirection is working with WP 5.5.1 for me now on several sites, not just the one I mentioned at the start of this thread. Thanks for your patience! You can  close the thread now. All is fine for WP 5.5.1
