### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by missionyogurt** [johngodley/redirection#2773] opened 2021-02-18 22:13 UTC
```
Plugin: 5.0.1
WordPress: 5.6.1 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
JavaScript: http://www.dia-food.com/wp/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: http://www.dia-food.com/?rest_route=/
Query: ?page=redirection.php

Action: http://www.dia-food.com/?rest_route=/redirection/v1/redirect/&orderby=id GET
Code: 500 Internal Server Error

Error: Internal Server Error (500)
```

**Comment by johngodley** [comment] 2021-03-27 12:58
Your site is returning a 500 error. This may be caused by a security plugin or site misconfiguration

**Comment by johngodley** [comment] 2021-03-31 19:12
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-31 19:12 UTC
Labels: need-feedback
