### ISSUE TITLE
broken redirections

### ISSUE THREAD

**Issue by zfliou** [johngodley/redirection#3239] opened 2022-02-18 16:31 UTC
Hello,

I'm contacting you because I have a question about redirects. 

To give you some context, we have an old blog which is https://blog.my-oxford.com/fr/ and which is still online for the moment.
Some of the posts on our current blog are from the old blog, so we have set up redirects so that the links from the posts on the old blog redirect to the new blog. 
Everything was working fine until now, but for a few weeks we have noticed a bug in the redirections. 
To give you an example, this article in Spanish with the url https://blog.my-oxford.com/es/structured-note-taking/ should redirect to https://www.scribzee.com/es/tomar-notas-de-forma-estructurada/ but the redirection url that appears is this one: https://blog.my-oxford.com/es/eshttps:/www.scribzee.com/structured-note-taking-for-students/ 

So we end up with a 404 error, and I don't understand why the language appears in the url next to the https...

Thank you for your help :)

**Comment by johngodley** [comment] 2022-02-18 17:34
You have 357 redirects. Is it possible another one is being used?

**Comment by johngodley** [comment] 2022-02-18 19:06
Also I see you are using qtrans. This often creates redirect issues.

**Comment by zfliou** [comment] 2022-02-22 08:54
Hello, 

Thank you so much for your help ! To be sure to understand well, we have this issue because of qTranslate plugin that's right ?

**Comment by johngodley** [comment] 2022-02-23 10:48
I can't say what the cause is, just that something else is happening outside of Redirection.

**Comment by johngodley** [comment] 2022-02-26 14:29
Closing for now, please reopen with more information.

**Closed by johngodley** 2022-02-26 14:29 UTC
