### ISSUE TITLE
Redirection Error - duplicate

### ISSUE THREAD

**Issue by Gensan1995** [johngodley/redirection#3569] opened 2023-03-10 09:05 UTC
Hello, I'm trying to use the app, but in the last days we receive this error and we can't understand why. Last week it worked and now it doesn't. We didn't change anything in our site. 

Can you help us? 

<img width="1527" alt="Screenshot 2023-03-10 alle 10 02 59" src="https://user-images.githubusercontent.com/127485907/224272617-0c96fb58-b07b-4a66-8531-4335e2e76284.png">

**Comment by johngodley** [comment] 2023-03-10 10:38
The problem is shown in the error - a duplicate entry. I'm not sure why that would happen but it may indicate a problem with your database, or maybe you have caching enabled that is causing issues.

**Comment by johngodley** [comment] 2023-04-15 13:35
Closing for now, please reopen with more details.

**Closed as completed by johngodley** 2023-04-15 13:35 UTC
