### ISSUE TITLE
Disable associated redirect?

### ISSUE THREAD

**Issue by gsjlusky** [johngodley/redirection#3541] opened 2023-01-28 00:49 UTC
When using URL Monitor Changes, is there a way to disable create associated redirect?  If I try to leave the box blank, it gets filled in with '/', and appears to create a duplicate redirect entry.

**Comment by thunderdw** [comment] 2023-03-23 20:34
This started happening in v5.3.7 due to this commit after the logic to only sanitize the associated redirect value if the value wasn't empty was removed, since the function to sanitize a URL ensures a URL at the start of the value it returns.. I'm assuming this isn't the intended behavior? I can make a PR to restore that logic.

https://github.com/johngodley/redirection/commit/2d89b4702fb2d86420321616f4de135d74ca30b3#diff-03f15b1fc2b15d80272040930cb996e076590b464bb42687726aed7199be8e29L119-R121

**Comment by johngodley** [comment] 2023-04-15 13:37
Closing as fixed, thanks!

**Closed as completed by johngodley** 2023-04-15 13:37 UTC
