### ISSUE TITLE
Problem starting Redirection 4.3.1

### ISSUE THREAD

**Issue by BhenChod1221** [johngodley/redirection#1861] opened 2019-06-29 08:10 UTC
Plugin: 4.3.1
WordPress: 5.2.2 (single)
PHP: 7.3.6
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
JavaScript: https://www.mangazuki.online/wp-content/plugins/redirection/redirection.js
REST API: https://www.mangazuki.online/wp-json/

**Comment by johngodley** [comment] 2019-07-13 16:30
Can you open your browser's developer console and see if any other information is shown? This is probably caused by another plugin.

**Comment by johngodley** [comment] 2019-07-21 08:25
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-07-21 08:25 UTC
Labels: need-feedback
