### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by itsmeanish** [johngodley/redirection#1357] opened 2018-12-18 14:10 UTC
Plugin stopped working after the WordPress update. I just updated WordPress from 4.9.5 to 4.9.8. It is working proper in my localhost as the project is configured in apche, but the issue that I'm getting in my staging server, which is configured with nginx. Please guide me to fix the issue as I'm stuck here with my redirections. 

```
Plugin: 3.6.3
WordPress: 4.9.8 (single)
PHP: 5.4.45
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:64.0) Gecko/20100101 Firefox/64.0
JavaScript: https://uat1.lendingkart.com/wp-content/plugins/redirection/redirection.js
REST API: https://uat1.lendingkart.com/wp-json/

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Action: redirection/v1/group/ GET
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Action: redirection/v1/redirect/?orderby=id GET
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3928086/50159757-77b76580-02fd-11e9-931c-1883c967454c.png">

**Comment by johngodley** [comment] 2018-12-18 15:32
The problem is described in the message:

`{"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}`

Your REST API is forbidding Redirection from doing anything. You can find more info about this here:

https://redirection.me/support/problems/rest-api/

**Comment by johngodley** [comment] 2018-12-27 15:47
Closing for now, please reopen with more details.

**Closed by johngodley** 2018-12-27 15:47 UTC
