### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Thaurgamblersclub** [johngodley/redirection#3171] opened 2021-12-18 12:07 UTC
Hi Guys! I am getting this error again I don't understand why is happening all the time I add a redirection :( can you please help me?

Plugin: 5.1.3 4.2
WordPress: 5.8.2 (single)
PHP: 7.4.26
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
JavaScript: https://thaurcasinogamblersclub.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://thaurcasinogamblersclub.com/wp-json/
Query: ?page=redirection.php

Error: undefined
```

**Comment by johngodley** [comment] 2021-12-22 11:01
Dupe of #3167

**Closed by johngodley** 2021-12-22 11:01 UTC
