### ISSUE TITLE
Does not work with Timber plugin

### ISSUE THREAD

**Issue by moazam1** [johngodley/redirection#726] opened 2018-02-04 02:54 UTC
Hi I am using Timber plugin in my theme. I have activate routes in my theme that uses timber. I get following error when I view any page:

Plugin: 3.1.1
WordPress: 4.9.2 (single)
PHP: 7.1.9
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
REST API: xxx

Error: Unexpected token < in JSON at position 0

Error: Unexpected token < in JSON at position 0

When I deactivate Timber plugin everything works fine. Any suggestion how to solve this issue?

**Comment by johngodley** [comment] 2018-02-05 18:45
Are there any other error details? If you are referring to https://wordpress.org/plugins/timber-library/ then I've just tried it and couldn't reproduce a problem, so it might be specific to your theme and it's use of timber.

**Comment by johngodley** [comment] 2018-02-17 20:29
Closing for now, please reopen with more details

**Closed by johngodley** 2018-02-17 20:29 UTC
