### ISSUE TITLE
redirect to homepage

### ISSUE THREAD

**Issue by martinrtr** [johngodley/redirection#1749] opened 2019-05-10 13:20 UTC
A problem so simple the solution MUST be staring me in the face but ...

How do you redirect a URL to the homepage? If I put in the homepage URL it redidrects to https://homepagehttps://homepage

I thought o leace the redirect blank - it won't let me save
I tried just / - this doesn't work

I tried a bunch of other things - I can't gert anything to work

Can you tell me how to do tbis

Thanks
Martin

**Comment by johngodley** [comment] 2019-05-10 13:27
Putting the full URL of your home page or `/` will work. You can use https://redirect.li/http/ to check a redirect without it being affected by your browser cache.

**Comment by martinrtr** [comment] 2019-05-10 13:32
Hi John - thanks for the swift reply - I tried both of your suggestions and neither work.

here's what I set up:
redirect from: /littleshopof-products/
redirect to: https://littleshopof.co.uk/

Here's the error message:
Expected: 301 to https://littleshopof.co.uk/
Found: 301 to https://littleshopof.co.ukhttps://littleshopof.co.uk/

**Comment by johngodley** [comment] 2019-05-10 13:34
Can you include a screenshot of your redirect?

**Comment by martinrtr** [comment] 2019-05-10 13:36
Here you go:

![Screenshot 2019-05-10 at 14 35 55](https://user-images.githubusercontent.com/1956388/57531287-fb1b3700-7330-11e9-969a-127a67675dc9.png)

**Comment by johngodley** [comment] 2019-05-11 14:49
I am unable to reproduce this using the same source and target. Are you running any plugins that may affect redirects?

**Comment by martinrtr** [comment] 2019-05-13 10:11
Hi John – the weird thing is that all the other re-directs work fine.

Example:

/product-category/little-little-book-of-earrings/page/2/<https://littleshopof.co.uk/product-category/little-little-book-of-earrings/page/2/>
https://littleshopof.co.uk/little-book-of-earrings/

This works great.

I just don’t seem to be able to re-direct to the hm e page

Regards,
Martin

T. 020 8659 1457
M. 07836 213891

martinr@carrdale.com<mailto:martinr@carrdale.com>

82 Peak Hill
London SE26 4LQ

[signature_610445186]<https://www.carrdale.com/>

www.carrdale.com<https://www.carrdale.com/>


[signature_2137657060]
http://www.linkedin.com/in/martinrobertscarrdale


This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed.

If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail.

Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.



I am unable to reproduce this using the same source and target. Are you running any plugins that may affect redirects?

**Comment by johngodley** [comment] 2019-05-13 11:15
Are you using a caching system of any kind?

**Comment by johngodley** [comment] 2019-05-18 12:21
Closing for now, please reopen with  more information

**Closed by johngodley** 2019-05-18 12:21 UTC
