### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by JayHoltslander** [johngodley/redirection#2206] opened 2020-03-09 17:01 UTC
```
Plugin: 4.7
WordPress: 5.3.2 (single)
PHP: 7.3.15
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15
JavaScript: https://www.[REDACTED].ca/wp-content/plugins/redirection/redirection.js
REST API: https://www.[REDACTED].ca/wp-json/

Error: JSON Parse error: Unrecognized token '<' (SyntaxError)
Raw: <br />
<b>Warning</b>:  explode() expects parameter 2 to be string, array given in <b>/srv/users/serverpilot/apps/[REDACTED]/public/wp-content/plugins/simple-history/loggers/Plugin_Redirection.php</b> on line <b>157</b><br />
{"items":[{"id":1,"name":"Redirections","redirects":177,"module_id":1,"moduleName":"WordPress","enabled":true,"default":true},{"id":2,"name":"Modified Posts","redirects":0,"module_id":1,"moduleName":"WordPress","enabled":true}],"total":2}
```

Error occurred when trying to delete or deactivate a redirection or redirection group.
However upon refreshing the page I see that the deletion happened successfully and the desired item was removed.

**Comment by johngodley** [comment] 2020-03-09 17:02
Error is shown above:

`Warning</b>:  explode() expects parameter 2 to be string, array given in <b>/srv/users/serverpilot/apps/[REDACTED]/public/wp-content/plugins/simple-history/loggers/Plugin_Redirection.php</b> on line <b>157`

Seems to be caused by simple-history

**Comment by johngodley** [comment] 2020-03-21 15:33
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-03-21 15:33 UTC
