### ISSUE TITLE
no redirection when the url link contain a space or %20

### ISSUE THREAD

**Issue by ODYSSEUS13** [johngodley/redirection#427] opened 2017-10-02 17:26 UTC
Hello

### Summary

As you can see in attached file when the **source url contain a space or %20** 

either wheb writing

1°/       /feux/feux%20bouches%20bonifacio/

or
 2°/     /feux/feux bouches bonifacio/ 

**the redirection does'nt work at all.**

### Environment

all browser, wp 4.8.2.  wp statistics Version 12.1.0 

Cordialment
![capture](https://user-images.githubusercontent.com/32463372/31090265-5bf003a0-a7a7-11e7-8439-4c0dc3eee778.JPG)

**Comment by johngodley** [comment] 2017-10-08 14:03
The %20 in the URL isn't the cause of the problem.

When I access http://www.yachter.fr/feux/feux%20fos%20aigle/ I am served a file that does not appear to be in WordPress. If this is the case then it is likely that your server is serving this file before WordPress has chance to run. If you wish to redirect it then you will need to delete the original file

**Comment by johngodley** [comment] 2017-10-14 13:28
Closing for now, please reopen with more details

**Closed by johngodley** 2017-10-14 13:28 UTC
