### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by MichaelPinatton** [johngodley/redirection#3362] opened 2022-07-22 19:39 UTC
```
Plugin: 5.3.0 4.2
WordPress: 6.0.1 (single)
PHP: 7.4.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
JavaScript: https://www.hotel-parc-gemenos.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff
REST API: https://www.hotel-parc-gemenos.com/wp-json/
Query: ?page=redirection.php
ReferenceError: props is not defined

    at Uc (https://www.hotel-parc-gemenos.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:395075)
    at div
    at Gc (https://www.hotel-parc-gemenos.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:397702)
    at Vd (https://www.hotel-parc-gemenos.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:460409)
    at div
    at i (https://www.hotel-parc-gemenos.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:400302)
    at https://www.hotel-parc-gemenos.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:682105
    at c (https://www.hotel-parc-gemenos.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:282543)
    at M (https://www.hotel-parc-gemenos.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:284652)
    at G_
```

**Comment by johngodley** [comment] 2022-07-22 19:47
Can you describe what you are doing when this occurs?

**Comment by johngodley** [comment] 2022-07-22 21:05
Is it any redirect, or some specific details? If specific, can you share what settings you are using?

**Comment by MichaelPinatton** [comment] 2022-07-23 06:39
It's a 301 redirect, from an article to the homepage. Without any more settingd.

<img width="1143" alt="Capture d’écran 2022-07-23 à 08 38 03" src="https://user-images.githubusercontent.com/73756983/180593669-1c76ec0a-c135-4edb-a58c-063a7ef5573a.png">

**Comment by johngodley** [comment] 2022-07-23 09:33
I'm not able to reproduce this and so far you are the only person reporting the problem on this one site. Is there anything different about the site? Do you have different settings elsewhere, or other plugins running?

**Comment by johngodley** [comment] 2022-09-06 12:55
Closing for now please reopen with more details.

**Closed by johngodley** 2022-09-06 12:55 UTC
