### ISSUE TITLE
www redirect error

### ISSUE THREAD

**Issue by olivaxa2** [johngodley/redirection#530] opened 2017-11-14 08:49 UTC
Hello,

With "www" https://www.direct-temporaires.fr let show this error : 

Erreur de la base de données WordPress : [Table 'XXX_XXX.wp_redirection_items' doesn't exist]
SELECT wp_redirection_items.*,wp_redirection_groups.position AS group_pos FROM wp_redirection_items INNER JOIN wp_redirection_groups ON wp_redirection_groups.id=wp_redirection_items.group_id AND wp_redirection_groups.status='enabled' AND wp_redirection_groups.module_id=1 WHERE (wp_redirection_items.regex=1 OR wp_redirection_items.url='/')

I need to redirect it to non www url.

I try to delete your plugin. No changes...

Can you help me ?

Thanks 

Olivier

**Comment by johngodley** [comment] 2017-11-14 09:00
Your Redirection database is incorrectly installed. You can go to the support page in the plugin to fix it.

If you delete the plugin there will be no error messages.

**Comment by olivaxa2** [comment] 2017-11-14 09:36
Hello. 

Thanks for your quick answer.

If I deactivated / deleted plugin. Problem sill here... I don't know why...

**Comment by johngodley** [comment] 2017-11-14 09:38
If you deactivate the plugin it is impossible for the above error message to be caused by Redirection - the plugin isn't running.

Are you caching things?

**Comment by olivaxa2** [comment] 2017-11-14 09:51
I use cloudeflare and WP rocket. I try to purge all cache without success.

"redirection" is deactivating but there is the same problem.

**Comment by johngodley** [comment] 2017-11-14 09:51
Can you delete the plugin from the wp-content/plugins/redirection directory?

**Comment by olivaxa2** [comment] 2017-11-14 09:57
Done

**Comment by johngodley** [comment] 2017-11-14 09:57
Did that fix the problem?

**Comment by johngodley** [comment] 2017-11-14 10:04
Ok, then it's to do with your caching setup. Redirection doesn't exist on your site anymore so it's impossible to be causing any problem. I don't know Cloudflare or WP Rocket, but you'll need to clear whatever needs clearing.

Accessing another page on your site shows that WordPress is working fine:

https://direct-temporaires.fr/a-propos-de-lassurance-moto-temporaire/

Other pages show you have some configuration problems elsewhere: https://direct-temporaires.fr/rx

**Comment by olivaxa2** [comment] 2017-11-14 10:06
Ok Thanks.

I try to find the issue.

**Comment by johngodley** [comment] 2017-11-18 09:59
Closing for now, please reopen with more details

**Closed by johngodley** 2017-11-18 09:59 UTC

**Comment by olivaxa2** [comment] 2018-08-30 08:35
Hello,

I just find that : http://www.gianpa.com/mysql-collation-errors-using-wordpress/

Collation problem. Persit even if plugin is deleted...

Can you find the solution for me please ?

Thanks
