### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by jacekzaw** [johngodley/redirection#3262] opened 2022-03-18 19:59 UTC
```
Plugin: 5.2.3 4.2
WordPress: 5.9.2 (single)
PHP: 7.4.25
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
JavaScript: https://www.altkomsoftware.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://www.altkomsoftware.com/pl/wp-json/
Query: ?page=redirection.php

Action: https://www.altkomsoftware.com/pl/wp-json/redirection/v1/bulk/redirect/delete/?orderby=id&per_page=200 POST
Params: {"items":["3008","3007"]}
Code: 400 Bad Request

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}
```

**Comment by johngodley** [comment] 2022-04-23 13:23
This is likely caused by a cache on your site.

**Comment by johngodley** [comment] 2022-06-04 06:08
Closing for now please reopen with more details.

**Closed by johngodley** 2022-06-04 06:08 UTC
Labels: need-feedback
