### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by nathan-wallace** [johngodley/redirection#2169] opened 2020-02-07 17:53 UTC
I am attempting to install Redirection. wp-json returns data but still can't setup Redirection plugin

```
Plugin: 4.6.2
WordPress: 5.2.4 (single)
PHP: 7.2.24
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
JavaScript: https://###.com/wordpress/wp-content/plugins/redirection/redirection.js
REST API: https://###.com/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment] 2020-02-07 18:05
Are you running a security plugin of any kind?

**Comment by nathan-wallace** [comment] 2020-02-07 18:16
We have a custom security plugin installed, but I did deactivate during troubleshooting.

**Comment by johngodley** [comment] 2020-02-08 15:36
Ok, then I would look to see what the difference is between the two environments. The above error is almost always caused by something stopping access to the REST API.

**Comment by johngodley** [comment] 2020-02-16 16:25
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-02-16 16:25 UTC
