### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by philspokas** [johngodley/redirection#579] opened 2017-12-21 14:32 UTC
```
Plugin: 2.10
WordPress: 4.8.4
PHP: 5.5.38
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

Error: Unexpected token T in JSON at position 0 (undefined)
Action: red_get_group
Params: {"filterBy":"","filter":""}
Code: undefined undefined
Raw: The page cannot be displayed because an internal server error has occurred.
```

**Comment by johngodley** [comment] 2018-01-14 15:17
The error suggests that your server is returning an error. This may be caused by a crash somewhere, or it may be caused by some security software like Wordfence.

**Comment by johngodley** [comment] 2018-01-19 19:21
Closing for now, please reopen with more information

**Closed by johngodley** 2018-01-19 19:21 UTC
