### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Connorwan** [johngodley/redirection#3337] opened 2022-07-07 02:31 UTC
```
Plugin: 5.2.3 4.2
WordPress: 6.0 (single)
PHP: 7.4.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
JavaScript: https://subscription.churacos-thai.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://subscription.churacos-thai.com/wp-json/
Query: ?page=redirection.php
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    at Uu (https://subscription.churacos-thai.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:462360)
    at p
    at div
    at Mu (https://subscription.churacos-thai.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:462485)
    at wp (https://subscription.churacos-thai.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:541382)
    at div
    at a (https://subscription.churacos-thai.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:484680)
    at https://subscription.churacos-thai.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:752964
    at f (https://subscription.churacos-thai.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:376159)
    at Fe (https://subscription.churacos-thai.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:374082)
    at s_
```

**Comment by johngodley** [comment] 2022-07-07 04:50
This is caused by another plugin or a browser extension.

**Comment by johngodley** [comment] 2022-07-13 06:14
Closing for now please reopen with more information.

**Closed by johngodley** 2022-07-13 06:14 UTC
