### ISSUE TITLE
Error in matches/login.php line 46

### ISSUE THREAD

**Issue by ronanfernandes** [johngodley/redirection#571] opened 2017-12-15 12:52 UTC
I have redirection installed for over 4 years.
Last weekend I switched my wp theme and setted WP_DEBUG true to see if anything is happening weardly.
Since then, i'm getting a huge debug.log that increased up to 500Mb.
I've opened that file and saw this error from beggining to end:

PHP Notice:  unserialize(): Error at offset 133 of 137 bytes in / *my domain* /wp-content/plugins/redirection/matches/login.php on line 46

I have no idea of what is causing this.
If that happened inside my own theme or plugin, I would edit the files and try to fix. But third party code we can't touch because it would break on updates.

Could any redirection rule that I added cause this? Or is it some kind of incompatibility with other plugins or even a bug?

Thank you in advance.

**Comment by johngodley** [comment] 2017-12-17 14:53
You could add this above line 46 in the `login.php` file mentioned:

`error_log( $values )`

This will include in the log file the data that is being loaded, and it may help locate where the problem is. You will probably want to disable the `error_log` line once you've got the error and the new data to appear in the log file.

**Comment by johngodley** [comment] 2018-01-05 18:47
Closing for now, please reopen with more information

**Closed by johngodley** 2018-01-05 18:47 UTC
