### ISSUE TITLE
Problem starting Redirection 4.5.1

### ISSUE THREAD

**Issue by Masoud** [johngodley/redirection#2101] opened 2019-12-23 11:57 UTC
```
Uncaught TypeError: Cannot read property 'hasClass' of undefined https://macneed.ir/wp-admin/load-scripts.php?c=0&load%5Bchunk_0%5D=hoverIntent,common,hoverintent-js,admin-bar,svg-painter,wp-hooks,heartbeat,wp-auth-check&ver=5.3.2 250
```

Plugin: 4.5.1
WordPress: 5.3.2 (single)
PHP: 7.3.12-1+0~20191128.49+debian9~1.gbp24559b
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
JavaScript: https://macneed.ir/wp-content/plugins/redirection/redirection.js
REST API: https://macneed.ir/wp-json/

**Comment by johngodley** [comment] 2019-12-23 13:49
The error looks like it's caused by another plugin.

**Comment by johngodley** [comment] 2019-12-30 09:46
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-12-30 09:46 UTC
