### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Techlearner123** [johngodley/redirection#3302] opened 2022-05-24 08:48 UTC
```
Plugin: 5.1.3 4.2
WordPress: 5.9.3 (single)
PHP: 7.4.26
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
JavaScript: https://ajiero.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://ajiero.com/wp-json/
Query: ?page=redirection.php

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}
```

**Comment by johngodley** [comment] 2022-06-04 06:14
This is probably caused by a cache on your site.

**Comment by johngodley** [comment] 2022-06-18 11:57
Closing for now, please reopen with more information.

**Closed by johngodley** 2022-06-18 11:57 UTC
