### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by yarnovanoort** [johngodley/redirection#2601] opened 2020-11-27 09:42 UTC
```
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.4.7
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
JavaScript: https://shop.stonedmarble.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://shop.stonedmarble.com/api/
Query: ?page=redirection.php

Error: Authorization header not found. (jwt_auth_no_auth_header)
Raw: {"success":false,"statusCode":403,"code":"jwt_auth_no_auth_header","message":"Authorization header not found.","data":[]}
```

**Comment by johngodley** [comment] 2020-11-27 09:51
The problem is shown in the message:

`Authorization header not found. (jwt_auth_no_auth_header)`

I don't know what that means, but it is something specific to your site and the plugins you run. Redirection requires a working REST API.

**Comment by johngodley** [comment] 2020-12-12 12:20
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-12-12 12:20 UTC
