### ISSUE TITLE
Json error: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by thevelop** [johngodley/redirection#2218] opened 2020-03-18 15:44 UTC
Hi,

I found an Issue, I can view this in console:

JSON.parse: unexpected character at line 1 column 1 of the JSON data > redirection.js:61:90744

Plugin version: 4.7.1 > Wordpress 5.3.2 single.

Details inside the box:

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 403 Fordibben

Raw: ......

Can you help us, please?

Thanks in advance.

**Comment by johngodley** [comment] 2020-03-18 15:48
Can you post the full details?

**Comment by thevelop** [comment] 2020-03-18 15:55
Yes, I can.

Here you are:


Plugin: 4.7.1
WordPress: 5.3.2 (single)
PHP: 7.2.28
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:74.0) Gecko/20100101 Firefox/74.0
JavaScript: https://oursite/wp-content/plugins/redirection/redirection.js
REST API: https://our
![Captura de pantalla 2020-03-18 a las 16 54 04](https://user-images.githubusercontent.com/10797923/76980248-416df900-6939-11ea-9144-d28901d69ec4.jpg)
![Captura de pantalla 2020-03-18 a las 16 53 57](https://user-images.githubusercontent.com/10797923/76980270-492d9d80-6939-11ea-8fe2-1be450a1b088.jpg)

site/wp-json/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 403 Forbidden
Raw: <!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" >
<title> 403 Forbidden
</title></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">403</h1>
<h2 style="margin-top:20px;font-size: 30px;">Forbidden
</h2>
<p>Access to this resource on the server is denied!</p>
</div></div></body></html>

**Comment by thevelop** [comment] 2020-03-18 15:56
Excuse me:

Plugin: 4.7.1
WordPress: 5.3.2 (single)
PHP: 7.2.28
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:74.0) Gecko/20100101 Firefox/74.0
JavaScript: https://oursite/wp-content/plugins/redirection/redirection.js
REST API: https://oursite/wp-json/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 403 Forbidden
Raw: <!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" >
<title> 403 Forbidden
</title></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">403</h1>
<h2 style="margin-top:20px;font-size: 30px;">Forbidden
</h2>
<p>Access to this resource on the server is denied!</p>
</div></div></body></html>

**Comment by thevelop** [comment] 2020-03-18 15:59
Additionally,

Seems what redirection.js can be corrupted in library:

/** @license React v16.13.0
 * react-is.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.

![Captura de pantalla 2020-03-18 a las 16 57 40](https://user-images.githubusercontent.com/10797923/76980717-d5d85b80-6939-11ea-9c26-0a4592b03106.jpg)

**Comment by johngodley** [comment] 2020-03-18 16:01
Ok, but can you include all the contents inside the error message box and the URLs? They are all in the report because they help. I can't tell if redirection.js is corrupted because I cannot access it. The screenshot doesn't show any corruption

**Comment by thevelop** [comment] 2020-03-18 16:04
I did, so a part is rendered as html.

I attach now a screenshot with code.

Thanks

![Captura de pantalla 2020-03-18 a las 17 02 42](https://user-images.githubusercontent.com/10797923/76981135-6dd64500-693a-11ea-9ef5-f28c47a5971c.jpg)

**Comment by thevelop** [comment] 2020-03-18 16:05
`Plugin: 4.7.1
WordPress: 5.3.2 (single)
PHP: 7.2.28
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:74.0) Gecko/20100101 Firefox/74.0
JavaScript: https://cruyffinstitute.nl/wp-content/plugins/redirection/redirection.js
REST API: https://cruyffinstitute.nl/wp-json/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 403 Forbidden
Raw: <!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" >
<title> 403 Forbidden
</title></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">403</h1>
<h2 style="margin-top:20px;font-size: 30px;">Forbidden
</h2>
<p>Access to this resource on the server is denied!</p>
</div></div></body></html>
`

**Comment by johngodley** [comment] 2020-03-18 16:06
Ok, the problem is shown in the message. Your WordPress REST API is returning a 404 forbidden error. The same happens when I try and access it. This usually indicates you are using a security plugin and it is blocking the API

**Comment by thevelop** [comment] 2020-03-18 16:48
That's ok,

I'm trying tomorrow and writing you later.

Many thanks!

**Comment by johngodley** [comment] 2020-05-02 12:56
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-05-02 12:56 UTC
Labels: need-feedback
