### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by mortocks** [johngodley/redirection#1814] opened 2019-06-12 05:09 UTC
```
Plugin: 4.3.1
WordPress: 4.9.10 (single)
PHP: 5.6.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15
JavaScript: https://wattrealty.com.au/wp-content/plugins/redirection/redirection.js
REST API: https://wattrealty.com.au/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

I know there are lots of posts talking about Cloudflare and Caching but this site has no caching plugins and no Cloudflare. It's a basic cPanel server (with no caching either). A terminal curl command to the urls from my computer work just fine - but when the plugin tries it, the rest_cookie_invalid_nonce errors get thrown. 

curl https://wattrealty.com.au/wp-json/

**Comment by johngodley** [comment] 2019-06-12 05:22
Sure, but it's not the same authenticated request. As the message should say, please logout, clear your browser cache, and login again

**Comment by mortocks** [comment] 2019-06-12 05:36
I've done that - followed all the steps in the basics troubleshooting before the last step which was to raise an issue

**Comment by johngodley** [comment] 2019-06-14 05:51
I am unable to reproduce this problem. If it is possible to access a site where this problem is happening then I can try and track it down. If this is ok then please contact me directly at https://redirection.me/contact/

**Comment by johngodley** [comment] 2019-06-20 17:47
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-06-20 17:47 UTC
Labels: need-feedback
