### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by zoneandonly** [johngodley/redirection#2513] opened 2020-10-26 18:56 UTC
```
Plugin: 4.9
WordPress: 5.5.1 (single)
PHP: 7.4.11
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
JavaScript: https://www.knowdebt.org/wp-content/plugins/redirection/redirection.js?ver=4.9-c383de96c0b7e38459253ead4f6e9b10
REST API: https://www.knowdebt.org/wp-json/
Query: ?page=redirection.php

Action: https://www.knowdebt.org/wp-json/redirection/v1/plugin/database/ POST
Code: 403 Forbidden

Error: JSON Parse error: Unrecognized token '<' (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>
```

**Comment by johngodley** [comment] 2020-10-26 18:57
As shown above, your REST API is returning a 403 forbidden error. This is likely caused by a security plugin.

**Comment by johngodley** [comment] 2020-11-08 17:37
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-08 17:37 UTC
