### ISSUE TITLE
Redirection Error: Failed to Fetch

### ISSUE THREAD

**Issue by hanssurfawhile** [johngodley/redirection#3033] opened 2021-08-27 10:16 UTC
### Summary

Hello, since today I'm facing an issue. The redirection plugin doesn't work anymore, and gives the following error: 

Error: Failed to fetch

URL: https://www.surfawhile.com/wp-json/

GETWorking!

POST TypeError: Failed to fetch

Failed to fetch

Your REST API is showing a deprecated PHP error. Please fix this error.

I tried to update the database (not applicable) and disabled all the plugins without any luck. I have no clue what's going wrong. 

### Environment

Plugin: 5.1.3 4.2
WordPress: 5.8 (multi)
PHP: 7.4.22
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
JavaScript: https://www.surfawhile.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://www.surfawhile.com/wp-json/
Query: ?page=redirection.php

I hope that you could help me out with this issue!

If you have any further questions, please let me know!
![Schermafbeelding 2021-08-27 om 12 16 04](https://user-images.githubusercontent.com/87713192/131112117-34e892b6-4ce0-4bb0-8ecb-13e34270a355.png)
![Schermafbeelding 2021-08-27 om 12 15 42](https://user-images.githubusercontent.com/87713192/131112120-1d72206a-9334-4c47-8240-1385642fe610.png)

**Comment by johngodley** [comment] 2021-09-04 09:12
This is probably caused by Cloudflare. You should exclude your REST API from Cloudflare.

**Comment by johngodley** [comment] 2021-09-18 06:23
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-09-18 06:23 UTC
Labels: need-feedback
