### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Alex7606** [johngodley/redirection#375] opened 2017-09-10 08:27 UTC
```
Plugin: 2.7.3
WordPress: 4.8.1
PHP: 7.0.12
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
Nonce: 47e9b5c528
URL: http://<site>/wp-admin/admin-ajax.php

Error: Unexpected token < in JSON at position 0 (undefined)
Action: red_set_redirect
Params: {"orderBy":"id","filterBy":"","filter":"","id":0,"url":"http://www.nackder.com/8-dresses","title":"","regex":false,"match_type":"url","action_type":"url","group_id":1,"action_code":301,"action_data":"http://www.nackder.com/"}
Code: 405 Not Allowed
Raw: <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.12.1</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

**Comment by johngodley** [comment] 2017-09-19 15:54
Your server returned a `405 not allowed` message. This is probably caused by a firewall or security plugin. You will need to investigate further and let me know the details.

**Comment by johngodley** [comment] 2017-09-30 11:47
Closing for now, please reopen with more information.

**Closed by johngodley** 2017-09-30 11:47 UTC
