### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by pb-kp** [johngodley/redirection#3015] opened 2021-08-11 17:15 UTC
```
Plugin: 5.1.3 4.2
WordPress: 5.8 (single)
PHP: 7.4.21
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:90.0) Gecko/20100101 Firefox/90.0
JavaScript: https://www.iecchateauthierry.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://www.iecchateauthierry.com/wp-json/
Query: ?page=redirection.php

Action: https://www.iecchateauthierry.com/wp-json/redirection/v1/bulk/redirect/delete/?orderby=id POST
Params: {"items":[1]}
Code: 400 Bad Request

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}
```

**Comment by pb-kp** [comment] 2021-08-11 17:15
Plugin: 5.1.3 4.2
WordPress: 5.8 (single)
PHP: 7.4.21
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:90.0) Gecko/20100101 Firefox/90.0
JavaScript: https://www.iecchateauthierry.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://www.iecchateauthierry.com/wp-json/
Query: ?page=redirection.php

Action: https://www.iecchateauthierry.com/wp-json/redirection/v1/bulk/redirect/delete/?orderby=id POST
Params: {"items":[1]}
Code: 400 Bad Request

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}

**Comment by johngodley** [comment] 2021-08-11 17:18
This is caused by an aggressive caching system on your site.

**Comment by johngodley** [comment] 2021-08-22 13:38
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-08-22 13:38 UTC
