### ISSUE TITLE
Problem starting Redirection 3.6.3

### ISSUE THREAD

**Issue by Pedrovinins** [johngodley/redirection#1388] opened 2019-01-08 12:11 UTC
```
Uncaught TypeError: Cannot read property 'feed' of null https://asteq.org/wp-content/plugins/st-gallery-wp/admin/js/script.js?ver=5.0.2 137
```

Plugin: 3.6.3
WordPress: 5.0.2 (single)
PHP: 7.2.13
Browser: Mozilla/5.0 (X11; CrOS x86_64 11151.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.94 Safari/537.36
JavaScript: https://asteq.org/wp-content/plugins/redirection/redirection.js
REST API: https://asteq.org/wp-json/

**Comment by johngodley** [comment] 2019-01-08 13:09
The problem is described in the error message:

`Cannot read property 'feed' of null https://asteq.org/wp-content/plugins/st-gallery-wp/admin/js/script.js`

The plugin st-gallery-wp is causing an error

**Comment by johngodley** [comment] 2019-01-16 17:32
Closing for now please reopen with more information

**Closed by johngodley** 2019-01-16 17:32 UTC
Labels: need-feedback
