### ISSUE TITLE
Problem starting Redirection 5.3.1

### ISSUE THREAD

**Issue by paroliav** [johngodley/redirection#3451] opened 2022-10-31 23:50 UTC
Plugin: 5.3.1 4.2
WordPress: 5.9.5 (multi)
PHP: 7.4.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0
JavaScript: https://blog.campermate.com.au/wp-content/plugins/redirection/redirection.js?ver=5.3.1-861e7f0132a71a1fdb94b8db22f36d35
REST API: https://blog.campermate.com.au/wp-json/

**Comment by johngodley** [comment] 2022-11-01 05:42
As described on the page this is almost certainly caused by another plugin.

**Comment by johngodley** [comment] 2022-11-26 12:33
Closing for now, please reopen with more information.

**Closed as completed by johngodley** 2022-11-26 12:33 UTC
