### ISSUE TITLE
Individual Delete button deletes ALL REDIRECTS!

### ISSUE THREAD

**Issue by erinwitzelRSU** [johngodley/redirection#3805] opened 2024-02-16 20:48 UTC
### Summary

Using the "Delete" button under an individual redirect deletes ALL redirects! This happened to me and a colleague. Very frustrating because I've lost all my redirects, and there were dozens. 

Also, even the "Disable" button under an individual redirect disables ALL redirects, and the "Enable" does the same.

So, it seems something is wrong with JS that's triggering all the buttons instead of just the one clicked.

**This is a pretty destructive bug, please assist!**

https://github.com/johngodley/redirection/assets/110620050/a6d6b19e-d15c-4af4-9027-265f62b6573b

### Environment

Chrome Version 121.0.6167.85, Wordpress 6.4.3, Multisite, Redirection Version 5.4.2,

**Comment by johngodley** [comment] 2024-06-15 06:32
I am unable to reproduce this and it doesn't appear to be affecting other people. Do you have other plugins or browser extensions installed that may be causing this?

**Comment by johngodley** [comment] 2024-11-23 14:27
Closing for now, please reopen with more details.

**Closed as completed by johngodley** 2024-11-23 14:27 UTC
Labels: need-feedback

**Comment by SarahMead** [comment] 2025-08-07 13:40
Hi @johngodley! We are currently also having this issue on our sites as well. When we click 'disabled', it also disables all redirect. What more information would you need to help with this issue?

Edit: when we also edit the redirect it just creates a new duplicate of the redirect instead. Which means now we have 2 redirects for the same slug. We cannot disable or delete it either, without it deleting everything. 

This plugin worked fine before. We have not added any new plugins. The only thing we have changed is doing routine updates to plugins.

**Comment by johngodley** [comment] 2025-08-07 14:15
As before, do you have other plugins or browser extensions installed that may be causing this? The behaviour is not part of the plugin.

**Comment by SarahMead** [comment] 2025-08-07 14:49
@johngodley What is unique about our setup is that we are using WP multisite that is hosted on WPVIP. We have about 12 different sites in our environment. This is helpful in a way because I am able to see if this same issue is also happening on our other sites. It is not. It's centralized to only our main #1 site (from what I can tell currently)

Things to note: Our sites use the same plugins. As a result, I do not see this being much of a conflicting plugin issue as another site with the same plugins has the redirection plugin working normally. This would mean the same for browser extensions since it is not causing an issue on the other sites as well while using the same browser and browser tab. Plus other users on different computers and setups are also running into this issue when using the plugin on site #1.

Do you have another troubleshooting method I can try?

**Comment by johngodley** [comment] 2025-08-09 11:33
Without being able to reproduce the problem myself it's pretty hard to know where to look. Maybe you could open your browser's developer console to the 'network' tab and see what is happening when the problem occurs.
