### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by PeteLikesIt** [johngodley/redirection#1745] opened 2019-05-09 22:10 UTC
```
Plugin: 4.2.3
WordPress: 5.1.1 (single)
PHP: 7.3.5
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
JavaScript: http://songlyricstoday.com/wp-content/plugins/redirection/redirection.js
REST API: http://songlyricstoday.com/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment] 2019-05-11 14:12
Are you running a security plugin?

**Comment by PeteLikesIt** [comment] 2019-05-11 14:51
Hello John,

I wasn't until just a couple of days ago, when I installed Wordfence plugin.
But this *upgrading the database* problem has been long running. I've just
not done anything about it until now.

**Comment by johngodley** [comment] 2019-05-12 07:35
The message is usually indicative of a security plugin blocking Redirection. If it's possible to get access to the site I might be able to find out more

**Comment by johngodley** [comment] 2019-05-18 12:15
Closing for now, please reopen with more details.

**Closed by johngodley** 2019-05-18 12:15 UTC
Labels: need-feedback

**Comment by PeteLikesIt** [comment] 2019-05-19 05:49
Sorry mate, but this used to be a good plugin.
Now it's turned into a pile of shit. I've noticed that other people have
the same issues as I do, on their sites, or so I'm reading on forums ...
and you seem to be in denial about it.

**Comment by johngodley** [comment] 2019-05-19 05:51
Thanks for your kind comments Pete. I am very aware of the problems that a few people have, and these are almost always caused by other software over which I have no control.
