### ISSUE TITLE
Redirection Error - wp-json 502 Bad Gateway

### ISSUE THREAD

**Issue by 65** [johngodley/redirection#2293] opened 2020-05-13 05:13 UTC
### Summary

Attempting to update a redirection rule results in a 503 Gateway Error. 

### Actual Behavior

POST to wp-json breaks 

### Steps to reproduce

Explain the steps involved to reproduce the problem

https://github.com/ampproject/amp-wp plugin at version 1.5.3 causes the issue. 

When AMP plugin is disabled this issue does not occur. 

Edit a redirection, and click to save it. 

```
Plugin: 4.7.2
WordPress: 5.4.1 (single)
PHP: 7.2.30-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
JavaScript: https://www.professionalplanner.com.au/wp-content/plugins/redirection/redirection.js
REST API: https://www.professionalplanner.com.au/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.15.6</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

**Comment by johngodley** [comment] 2020-05-13 07:10
This is caused by your server, or something on your site. Typically it can be a security plugin.

**Comment by johngodley** [comment] 2020-05-13 07:10
Oh, I see you mentioned AMP.

**Comment by johngodley** [comment] 2020-05-23 11:21
Redirection works fine with AMP in my testing. I suspect this is some configuration specific to your site. The error message indicates there is a problem on your REST API

**Comment by johngodley** [comment] 2020-06-06 09:33
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-06-06 09:33 UTC
Labels: need-feedback
