### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by merridennis** [johngodley/redirection#1863] opened 2019-06-30 21:52 UTC
```
Plugin: 4.3.1
WordPress: 5.2.2 (single)
PHP: 7.1.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
JavaScript: https://mastersundaybulletins.com/wp-content/plugins/redirection/redirection.js
REST API: https://mastersundaybulletins.com/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <h1>Error thrown</h1><p>Class name must be a valid object or a string</p>
```

**Comment by johngodley** [comment] 2019-07-13 16:31
As seen in the error, your website is returning this message:

`<h1>Error thrown</h1><p>Class name must be a valid object or a string</p>`

This is caused by something on your website, such as another plugin.

**Comment by johngodley** [comment] 2019-07-21 08:24
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-07-21 08:24 UTC
Labels: need-feedback
