### ISSUE TITLE
Error when changing the HTTP Status Code

### ISSUE THREAD

**Issue by almino** [johngodley/redirection#2089] opened 2019-12-11 21:09 UTC
```
Plugin: 4.5.1
WordPress: 5.3 (multi)
PHP: 7.1.14
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
JavaScript: https://josb.com.br/2020/wp-content/plugins/redirection/redirection.js
REST API: https://josb.com.br/2020/wp-json/

Error: Unexpected token < in JSON at position 404 (SyntaxError)
Raw: {"item":{"id":3,"url":"\/2020\/inscrever","match_url":"\/2020\/inscrever","match_data":{"source":{"flag_query":"exact","flag_case":false,"flag_trailing":false,"flag_regex":false}},"action_code":307,"action_type":"url","action_data":{"url":"https:\/\/sistema.josb.com.br\/evento\/inscrever"},"match_type":"url","title":"","hits":1,"regex":false,"group_id":1,"position":2,"last_access":"-","enabled":true}}<br />
<b>Fatal error</b>:  Call to undefined function use_block_editor_for_post_type() in <b>/home/josbc871/public_html/wordpress/wp-admin/includes/class-wp-screen.php</b> on line <b>329</b><br />

```

**Comment by johngodley** [comment] 2019-12-11 21:50
You can see the error here:

` Call to undefined function use_block_editor_for_post_type() in <b>/home/josbc871/public_html/wordpress/wp-admin/includes/class-wp-screen.php</b> on line <b>329</b><br />`

This is not caused by Redirection.

**Comment by johngodley** [comment] 2019-12-21 17:40
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-12-21 17:40 UTC
