### ISSUE TITLE
false 404 errors logged when using instapages

### ISSUE THREAD

**Issue by dhaddad355** [johngodley/redirection#773] opened 2018-02-13 21:42 UTC
### Summary

Redirection plugin logs an erroneous 404 error when using Instapage landing pages

### Actual Behavior

Instapage (popular landing page platform) allows direct integration to wordpress. When using their plugin it will serve the page from the wordpress site (as opposed to a 301 redirect), this is preferred for SEO. The redirection plugin will log a 404 error (assuming it is because the page does not actually exist in the context of the wordpress site

### Steps to reproduce

-Install instapage plugin
-Configure wordpress to send users to instapage created landing page from some url in wordpress
-Note that although the browser returns 200 and page is displayed redirection plugin logs a 404 error

### Environment

WP 4.9.4
Redirection 3.2
Instapage 3.2.1

### Notes
Available to help test if needed, instapage allows for free accounts as well. A setting to ignore / whitelist certain urls to not generate a 404 log would also be helpful and would not fix the issue but would fix it from displaying.

**Comment by johngodley** [comment] 2020-11-14 10:17
I'm unable to reproduce this. Closing for now, but please reopen with more details.

**Closed by johngodley** 2020-11-14 10:17 UTC
Labels: enhancement
