### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by gayatri89** [johngodley/redirection#2210] opened 2020-03-11 07:12 UTC
```
Plugin: 4.5.1
WordPress: 5.3 (single)
PHP: 7.3.5
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
JavaScript: https://www.cloudninefertility.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.cloudninefertility.com/wp-json/

Error: Unable to add new redirect (211): Operation not allowed when innodb_forced_recovery > 0.
Action: redirection/v1/redirect/ POST
Params: {"id":0,"url":"https://www.cloudninefertility.com/doctors/dr-reeta-biliangady/","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":false,"flag_case":false,"flag_query":"exact"}},"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"https://demo.cloudninefertility.com/dr-reeta-biliangady"}}
Code: 400 Bad Request
Raw: {"code":"redirect_create_failed","message":"Unable to add new redirect","data":{"status":400,"error_code":211,"wpdb":"Operation not allowed when innodb_forced_recovery > 0."}}
```

**Comment by johngodley** [comment] 2020-03-11 07:18
The problem is shown above:

`Operation not allowed when innodb_forced_recovery > 0.`

https://stackoverflow.com/questions/25155777/operation-not-allowed-when-innodb-forced-recovery-0-sqlyog

**Comment by johngodley** [comment] 2020-03-21 15:32
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-03-21 15:33 UTC
