### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by jivygraphics** [johngodley/redirection#1730] opened 2019-05-01 21:04 UTC
```
Plugin: 4.2.3
WordPress: 5.1.1 (single)
PHP: 7.1.28
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://rarebookschool.org/wp-content/plugins/redirection/redirection.js
REST API: /wp-json/

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```

**Comment by johngodley** [comment] 2019-05-04 14:17
Your WordPress REST API is returning an error. THis is probably caused by a security plugin.

**Comment by johngodley** [comment] 2019-05-11 14:06
Closing for now, please reopen with more details

**Closed by johngodley** 2019-05-11 14:06 UTC
Labels: need-feedback
