### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by webcreativus** [johngodley/redirection#2848] opened 2021-03-31 19:06 UTC
```
Plugin: 5.0.1
WordPress: 5.7 (single)
PHP: 7.4.16
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
JavaScript: https://www.godates.co/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: /wp-json/
Query: ?page=redirection.php

Error: No route was found matching the URL and request method. (rest_no_route)
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method.","data":{"status":404}}
```

**Comment by webcreativus** [comment] 2021-03-31 19:30
Disconnected all the plugins, disconnected server security, checked API, json etc, nothing worked

**Comment by johngodley** [comment] 2021-04-01 09:22
You can find more details here: https://redirection.me/support/problems/rest-api/

I note your REST API is also cached by Cloudflare.

**Comment by webcreativus** [comment] 2021-04-01 20:07
Excluded Rest API from Cloudflare caching, didn't help.

**Comment by johngodley** [comment] 2021-04-02 07:46
Your REST API is still going through Cloudflare:

https://redirect.li/http/?url=https%3A%2F%2Fwww.godates.co%2Fwp-json%2F

This error message is almost always caused by some security software, or something like a cache.

**Comment by johngodley** [comment] 2021-05-03 12:12
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-05-03 12:12 UTC
