### ISSUE TITLE
Redirection Plugin Error

### ISSUE THREAD

**Issue by Paulettelette** [johngodley/redirection#3477] opened 2022-11-19 17:37 UTC
```
Plugin: 5.3.5 4.2
WordPress: 5.9.5 (multi)
PHP: 7.4.29
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
JavaScript: https://www.labelleplace.fr/wp-content/plugins/redirection/redirection.js?ver=5.3.5-f0dac5b2b3267cd737c1a679e4c1fac3
REST API: https://www.labelleplace.fr/wp-json/
Query: ?page=redirection.php

Error: Unexpected token '<', "<!DOCTYPE "... is not valid JSON (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
```

**Comment by johngodley** [comment] 2022-11-19 17:41
Your REST API is returning the above error. You will need to fix that.

**Comment by Paulettelette** [comment] 2022-11-19 17:45
Thanks for your answer. I don't know how to manage it, this error is new on my website. Before that, I changed the permalink parameters and I created 404 in every pages of the webiste. I would like to add the plugin Redirection and it looks not working because of this issue... At this point I don't understand anything...

**Comment by Paulettelette** [comment] 2022-11-19 17:49
I disabled every plugins to my website but still have this issue.

**Comment by johngodley** [comment] 2022-11-19 17:50
Sure, I understand it's complicated. However, the error isn't caused by Redirection. Your hosting provider may be able to help you fix the REST API error.

**Comment by Paulettelette** [comment] 2022-11-19 17:51
Thanks a lot. I'll ask to OVH if they're able to help me.

**Comment by johngodley** [comment] 2022-11-26 12:31
Closing for now, please reopen with more information.

**Closed as completed by johngodley** 2022-11-26 12:31 UTC
