### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by ashishstirling** [johngodley/redirection#2619] opened 2020-12-05 10:28 UTC
```
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.2.34
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
JavaScript: https://www.pawsitivesolutions.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.pawsitivesolutions.com/wp-json/
Query: ?page=redirection.php

Error: Unexpected token : in JSON at position 8 (SyntaxError)
Raw: "status":"finish-update","inProgress":false,"complete":100,"reason":"Add extra 404 logging support"
```

**Comment by johngodley** [comment] 2020-12-05 10:31
Your WordPress REST API is broken:

https://www.pawsitivesolutions.com/wp-json/

It is outputting invalid JSON. I imagine this is caused by another plugin.

**Comment by johngodley** [comment] 2020-12-12 12:25
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-12-12 12:25 UTC
