### ISSUE TITLE
Creating "product" also automatically creates redirect...

### ISSUE THREAD

**Issue by cedriccharles4** [johngodley/redirection#196] opened 2017-05-17 17:23 UTC
Hello,

Thank you for your plugin and the time you put in it !

I have the exact same issue than the one describes there : https://wordpress.org/support/topic/redirection-plugin-randomly-creating-301-redirects-for-new-woocommerce-product/#post-9141840

Only when I create "product" (not Woocommerce but the CPT is product).

Thank you in advance !

**Comment by johngodley** [comment] 2017-05-29 15:53
I've been unable to reproduce this problem, either with WooCommerce, or the Ozh Tweet plugin. Can you explain what you do that triggers the redirect to be created, and what the redirect is?

**Comment by cedriccharles4** [comment] 2017-05-30 07:54
Hi @johngodley !

I've found the source of the problem. In fact, every time a visitor created a product, I was hooking to the save_post action and then programmatically edited the permalink with a "update_post_data" action. The last one triggered the redirect to be created. I've changed the way I handle it but it could be great if you can provide a way of programmatically editing a permalink without triggering the redirect to be created.

**Comment by johngodley** [comment] 2017-05-31 06:58
Is there any chance you could make that code available somewhere? I have added something in 2.6.1 that may help, but I'd like to add some tests to make sure it doesn't happen

**Comment by johngodley** [comment] 2017-08-08 05:20
Closing for now

**Closed by johngodley** 2017-08-08 05:20 UTC
