### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by lovik1468** [johngodley/redirection#2281] opened 2020-04-29 07:11 UTC
```
Plugin: 4.7.1
WordPress: 5.4 (single)
PHP: 7.3.13
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
JavaScript: https://www.canncentral.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.canncentral.com/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```
Good afternoon, I get this error when I try to install the res api plugin, it is accessible and working

**Comment by johngodley** [comment] 2020-05-02 12:46
You are likely using a security plugin that is blocking access to the WordPress REST API.

**Comment by lovik1468** [comment] 2020-05-02 13:16
No, not worth it; (

**Comment by lovik1468** [comment] 2020-05-02 13:22
Seriously ???? Did you just close the problem ???? It costs me nothing to block REST

**Comment by johngodley** [comment] 2020-05-02 13:23
Yes, you said it's not worth it so I assumed you didn't want to proceed.

**Comment by lovik1468** [comment] 2020-05-02 13:27
You asked if there is a plugin that can block REST, said no

**Comment by johngodley** [comment] 2020-05-02 13:30
It was a statement not a question. If you are not using a security plugin then something else is blocking your REST API when the plugin tries to access it. This may be other security settings on your server, or maybe even another plugin

**Comment by lovik1468** [comment] 2020-05-02 13:37
You can go to the standard rest request and not one, it will not be blocked

**Comment by johngodley** [comment] 2020-05-02 13:40
Sure, but that doesn't mean it isn't being blocked when making a POST request. I have seen this message many times before and it is always caused by something on the site blocking the request. Sometimes it is a plugin, sometimes it is Sucuri or mod_security etc

**Comment by lovik1468** [comment] 2020-05-02 13:46
Well, I will ask this question to the server administrators and will get back to you on Monday

**Comment by johngodley** [comment] 2020-05-08 07:37
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-05-08 07:37 UTC
Labels: need-feedback
