### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by wikiexir** [johngodley/redirection#1735] opened 2019-05-04 14:46 UTC
```
Plugin: 4.2.3
WordPress: 4.9.10 (single)
PHP: 7.2.11
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
JavaScript: http://enpedia.ir/wp-content/plugins/redirection/redirection.js
REST API: http://enpedia.ir/wp-json/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 503 Service Unavailable
Raw: <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8"><TITLE>503 Service Unavailable</TITLE></HEAD><BODY><H1>503 Service Unavailable</H1></BODY></HTML>
```

**Comment by johngodley** [comment] 2019-05-11 14:15
Your REST API is returning a `503 Service Unavailable` message. This may be caused by a security plugin.

**Comment by johngodley** [comment] 2019-05-18 12:16
Closing for now, please reopen with more details.

**Closed by johngodley** 2019-05-18 12:16 UTC
Labels: need-feedback
