### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by wiremoteam** [johngodley/redirection#2455] opened 2020-09-14 14:39 UTC
```
Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.2.24-0ubuntu0.18.04.4
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0
JavaScript: https://www.hideipvpn.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.hideipvpn.com/wp-json/

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Action: redirection/v1/setting/ GET
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```

**Comment by johngodley** [comment] 2020-09-19 11:33
Your REST API is return a 401 error. This is likely caused by a security plugin.

**Comment by johngodley** [comment] 2020-09-26 15:58
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-09-26 15:58 UTC
Labels: need-feedback
