### ISSUE TITLE
Erroneous 'Cached Redirection detected'

### ISSUE THREAD

**Issue by michaeldouma** [johngodley/redirection#467] opened 2017-10-18 16:02 UTC
After updating to Version 2.8, I can't load the admin page within WP. I get the error: 
  Cached Redirection detected
  Please clear your browser cache and reload this page

Same problem occurs in Mac Chrome, and Mac High Sierra Safari. Also clearing the server varnish cache has no impact.

**Comment by johngodley** [comment] 2017-10-18 16:03
There should be some information beneath this - can you paste it here?

**Comment by michaeldouma** [comment] 2017-10-18 16:05
Cached Redirection detected

Please clear your browser cache and reload this page

**Comment by michaeldouma** [comment] 2017-10-18 16:06
That's all I see. Clearing the cache, and using a private browsing window has no effect.

**Comment by johngodley** [comment] 2017-10-18 16:08
You don't see something like this?

<img width="552" alt="redirection_ _test_ _wordpress" src="https://user-images.githubusercontent.com/1277682/31729442-ed6509bc-b426-11e7-922e-c435e40133c6.png">

**Comment by michaeldouma** [comment] 2017-10-18 16:22
No. Not in either browser.

**Comment by michaeldouma** [comment] 2017-10-18 16:24
Ok, this is weird, but it relates to an older bug we've seen. The problem magically resolved, and the page loads. I did nothing.  Sometimes the URL list disappears. 

Is there some kind of potentially-slow server-side script that runs? Or some table that rebuilds in different ways?

**Comment by johngodley** [comment] 2017-10-18 16:34
It's working now?

I think the problem is caused by some kind of page caching. Cloudflare is particularly problematic.

What is happening is that the version number inside the JavaScript is not matching up to the version number from PHP, and the error is shown as a catch-all.

If it is now working then this kind of confirms that it's a caching thing, somehow. Version 2.8 shows the additional information.

**Comment by johngodley** [comment] 2017-10-19 18:46
Closing for now but please reopen if you have more information

**Closed by johngodley** 2017-10-19 18:46 UTC
