### ISSUE TITLE
Some query params in destination url are being ignored

### ISSUE THREAD

**Issue by awakash** [johngodley/redirection#3305] opened 2022-05-25 19:46 UTC
I'm trying to create a redirect:

`/my-items/cars?topics=234`
to 
`/things?type=colors&term=1999`
I also tried 
`/things?type=colors&amp;term=1999`

I've tried with all 4 settings for query parameters but its seems like anything after the `&` is being ignored: so it ends up only redirecting to `/things?type=colors`

Any ideas what I'm doing wrong?

**Comment by awakash** [comment] 2022-05-25 21:24
Note that this occurs after importing redirects; not by adding them directly via the UI.

**Comment by johngodley** [comment] 2022-05-26 04:39
There is no difference between importing something and typing it in.

I am not able to reproduce this problem, and things after `&` do not appear to be ignored. There must be something else involved, such as a difference in settings.

**Comment by johngodley** [comment] 2022-06-04 06:07
Closing for now please reopen with more details.

**Closed by johngodley** 2022-06-04 06:07 UTC

**Comment by awakash** [comment] 2022-06-06 15:30
In case someone runs into this scenario,  if you have a redirect you want to create like `/my-items/cars?topics=234`, you may have `/my-items/cars` as a redirect as well and if that's the case I changed this redirect to "flag_query": "exact" to fix the issue I was running into.
