### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by nawfeloussedik** [johngodley/redirection#2620] opened 2020-12-05 22:42 UTC
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.3.12
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
JavaScript: https://www.cryochambers.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.cryochambers.com/wp-json/

**Comment by johngodley** [comment] 2020-12-12 12:26
This is almost certainly caused by another plugin. Please follow the onscreen instructions and check your browser's developer console.

Closing for now, please reopen with more information.

**Closed by johngodley** 2020-12-12 12:26 UTC
