### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by steffnomidi** [johngodley/redirection#3365] opened 2022-07-24 08:39 UTC
```
Plugin: 5.3.0 4.2
WordPress: 6.0.1 (single)
PHP: 7.4.28
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
JavaScript: https://tovarishestvo.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff
REST API: https://tovarishestvo.com/wp-json/
Query: ?page=redirection.php
TypeError: Cannot read properties of undefined (reading 'prevOffset')

    at i (https://tovarishestvo.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:650938)
    at c (https://tovarishestvo.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:282543)
    at A_ (https://tovarishestvo.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:678627)
    at Vd (https://tovarishestvo.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:460409)
    at div
    at i (https://tovarishestvo.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:400302)
    at https://tovarishestvo.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:682105
    at c (https://tovarishestvo.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:282543)
    at M (https://tovarishestvo.com/wp-content/plugins/redirection/redirection.js?ver=5.3.0-b1b87cb68e8259adfb21001e200a84ff:2:284652)
    at G_
```

**Comment by johngodley** [comment] 2022-07-24 08:51
What are you doing when this happens? How do I reproduce it?

**Comment by steffnomidi** [comment] 2022-07-24 08:58
I just went to /wp-admin/tools.php?page=redirection.php&sub=io


вс, 24 июл. 2022 г. в 11:52, John ***@***.***>:

**Comment by johngodley** [comment] 2022-07-28 18:34
I'm unable to reproduce the problem. Do you have any other details that might help?

**Comment by johngodley** [comment] 2022-07-29 06:48
I have found this is caused by the Russian language file.

**Comment by johngodley** [comment] 2022-09-06 12:55
Closing for now please reopen with more details.

**Closed by johngodley** 2022-09-06 12:55 UTC
Labels: need-feedback
