### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Dadaismu5** [johngodley/redirection#474] opened 2017-10-20 20:42 UTC
```
Plugin: 2.8
WordPress: 4.8.2
PHP: 5.6.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

Error: No response returned - WordPress did not understand AJAX request
Action: red_get_group
Params: {"filterBy":"","filter":""}
Code: 200 OK
Raw: 0

Error: No response returned - WordPress did not understand AJAX request
Action: red_get_redirect
Params: {"orderBy":"id","filterBy":"","filter":""}
Code: 200 OK
Raw: 0
```

**Comment by johngodley** [comment] 2017-10-21 06:49
Your WordPress is ignoring the request from Redirection. I will guess that this is caused by another plugin. If you disable all other plugins and try it again you will be able to confirm this, and can then re-enable plugins until it stops working.

**Comment by johngodley** [comment] 2017-10-28 11:17
Closing for now, please reopen with more information.

**Closed by johngodley** 2017-10-28 11:17 UTC
