### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Phuonglaithi** [johngodley/redirection#3321] opened 2022-06-21 20:35 UTC
```
Plugin: 5.2.3 4.2
WordPress: 6.0 (single)
PHP: 7.4.29
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
JavaScript: https://hoshi-shop.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://hoshi-shop.com/wp-json/
Query: ?page=redirection.php&sub=options
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    at Uu (https://hoshi-shop.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:462360)
    at p
    at div
    at Mu (https://hoshi-shop.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:462485)
    at wp (https://hoshi-shop.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:541382)
    at div
    at a (https://hoshi-shop.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:484680)
    at https://hoshi-shop.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:752964
    at f (https://hoshi-shop.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:376159)
    at Fe (https://hoshi-shop.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:374082)
    at s_
```

**Comment by johngodley** [comment] 2022-06-21 21:03
This is caused by a browser extension or another plugin.

**Comment by johngodley** [comment] 2022-06-25 10:11
Closing for now, please reopen with more information

**Closed by johngodley** 2022-06-25 10:11 UTC
