### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by bossras** [johngodley/redirection#2603] opened 2020-11-27 14:46 UTC
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.3.23
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0
JavaScript: https://northsidetools.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://northsidetools.com/wp-json/

**Comment by johngodley** [comment] 2020-12-12 12:26
This is almost certainly caused by another plugin. Please follow the onscreen instructions and check your browser's developer console.

Closing for now, please reopen with more information.

**Closed by johngodley** 2020-12-12 12:26 UTC
