### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by maeflower** [johngodley/redirection#2475] opened 2020-10-01 18:11 UTC
```
Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.0.33-29+0~20200514.36+debian9~1.gbp126f6f
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
JavaScript: https://milliforher.com/wp-content/plugins/redirection/redirection.js
REST API: https://milliforher.com/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <!DOCTYPE html><html>  <head>    <title>503 Backend fetch failed</title>  </head>  <body>    <h1>Error 503 Backend fetch failed</h1>    <p>Backend fetch failed</p>    <h3>Guru Meditation:</h3>    <p>XID: 9047492</p>    <hr>    <p>Varnish cache server</p>  </body></html>
```

**Comment by johngodley** [comment] 2020-10-01 18:17
The problem is shown in the error:

`503 Backend fetch failed`

Something happened on your server, and you will need to look at the server error log.

**Comment by johngodley** [comment] 2020-10-11 13:18
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-10-11 13:18 UTC
