### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by sir-zellot** [johngodley/redirection#2959] opened 2021-06-24 16:46 UTC
```
Plugin: 5.0.1
WordPress: 5.7.2 (single)
PHP: 7.4.20
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
JavaScript: https://www.kreativ-wedding.de/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://www.kreativ-wedding.de/wp-json/
Query: ?page=redirection.php&sub=404s

Error: Failed to fetch
```

**Comment by johngodley** [comment] 2021-07-04 11:28
This is probably caused by a security plugin.

**Comment by johngodley** [comment] 2021-07-17 06:06
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-07-17 06:06 UTC
Labels: need-feedback
