### ISSUE TITLE
Problem starting Redirection 5.0.1

### ISSUE THREAD

**Issue by Wouwouw-YB** [johngodley/redirection#2774] opened 2021-02-19 10:56 UTC
```
Uncaught TypeError: (intermediate value)[Symbol.iterator] is not a function https://salonboest.nl/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3 2
```

Plugin: 5.0.1
WordPress: 5.6.1 (single)
PHP: 7.3.25-1+ubuntu18.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
JavaScript: https://salonboest.nl/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://salonboest.nl/wp-json/
-----

- Wordpress API is running
- Deactivated all other plugins
- tried different browsers

**Comment by johngodley** [comment] 2021-03-27 12:56
I am unable to reproduce this. Do you have any other information?

**Comment by johngodley** [comment] 2021-03-31 19:12
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-31 19:12 UTC
Labels: need-feedback
