### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by JimMesser** [johngodley/redirection#1927] opened 2019-08-21 15:21 UTC
When generating or editing a redirect, it won't save the source URL. It leaves it blank. I also tried with all plugins disabled and all all caches cleared. Same problem. Nginx Server.

Plugin: 4.3.3
WordPress: 5.2.2 (single)
PHP: 7.2.21
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
JavaScript: https://www.townofcowpens.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.townofcowpens.com/wp-json/
Buster: 4.3.3 === 4.3.3

TypeError: o.replace is not a function

    in t
    in p
    in div
    in div
    in div
    in t
    in td
    in tr
    in t
    in p
    in tbody
    in Ua
    in table
    in Unknown
    in div
    in t
    in p
    in div
    in t
    in p
    in t
    in Unknown

**Comment by johngodley** [comment] 2019-08-21 16:41
What is the redirect you are trying to create?

**Comment by JimMesser** [comment] 2019-08-21 18:21
https://www.townofcowpens.com/police/
https://www.townofcowpens.com/public-services/

When I attempt to save the redirect, it initially shows the source url, and then it just vanishes right before the success message.

**Comment by johngodley** [comment] 2019-08-25 07:17
I'm not able to reproduce this problem. Would it be possible to login to your site and try it myself? If so please contact me at https://redirection.me/contact/

**Comment by johngodley** [comment] 2019-09-07 14:50
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-09-07 14:50 UTC

**Comment by collinbarrett** [comment] 2019-09-07 18:06
I'm experiencing this as well:
