### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Yogeshjenval** [johngodley/redirection#2351] opened 2020-06-24 13:15 UTC
```
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.2.31
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
JavaScript: https://hindilook.xyz/wp-content/plugins/redirection/redirection.js
REST API: https://hindilook.xyz/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

```

**Comment by johngodley** [comment] 2020-06-29 05:30
Your REST API is returning a 404, probably caused by a security plugin.

**Comment by johngodley** [comment] 2020-07-18 15:23
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-07-18 15:23 UTC
Labels: need-feedback
