### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by donikajons** [johngodley/redirection#3175] opened 2021-12-21 10:00 UTC
```
Plugin: 5.1.3 4.2
WordPress: 5.8.2 (single)
PHP: 8.0.13
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
JavaScript: https://www.articlesupdate.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://www.articlesupdate.com/wp-json/
Query: ?page=redirection.php&sub=404s

Action: https://www.articlesupdate.com/wp-json/redirection/v1/redirect/?orderby=id&direction=desc&per_page=25 POST
Params: {"id":0,"url":["/2021/12/08/pick-your-app-on-the-boulevard-put-it-in-a-automotive/feed/","/category/technology/page/140/","/2021/11/25/meghan-markleaes-pr-team-ae%CB%9Crushingae-royal-to-catch-legend-out-file/feed/","/2021/11/25/james-arthur-weighs-in-on-creating-ae%CB%9Cemilyae-single-for-miscarried-daughter/feed/","/2021/11/24/constancy-obtained-270-million-in-bitcoin-ethereum-donations-this-year/feed/","/2021/11/30/influencer-poses-in-underwear-to-expose-off-her-butt-and-expose-cellulite-is-regular-and-beautiful/feed/","/choosing-a-modern-television-for-a-child.html","/general/kyle-rittenhouse-biden-angry-after-teen-cleared-of-shootings/","/category/dont/","/category/england/","/author/admin/page/648/","/2021/12/03/pet-food-market-research-report-with-swot-analysis-2021-2027/","/2021/12/08/fresh-macbook-professionals-reportedly-having-components-finding-out-some-sd-playing-cards/feed/","/2021/11/25/compensation-for-rain-hit-properties-in-yelahanka-rapidly-karnataka-cm/feed/","/2021/12/11/jessie-j-shares-an-appealing-message-for-miscarriage-victims-ae%CB%9Cim-aching/feed/","/2021/11/27/meghan-markleaes-pr-crew-ae%CB%9Crushingae-royal-to-earn-chronicle-out-represent/feed/","/2021/11/27/james-arthur-weighs-in-on-creating-ae%CB%9Cemilyae-single-for-miscarried-daughter-2/feed/","/11/2021/","/2021/12/09/an-exercise-in-fragmentation-limiting-android-installs-to-tool-units-3/feed/","/weight-loss-diet-for-that-women-with-small-children.html","/2021/11/30/at-present-is-the-final-day-to-gain-hulu-for-ninety-nine%C2%A2-per-month-for-365-days/feed/","/2021/12/10/slash-cannon-shares-ae%CB%9Cpainfulae-message-for-gradual-son-zen-ae%CB%9Cthis-silence-is-deafeningae/feed/","/2021/12/05/microsoft-dwelling-of-business-has-a-original-original-gape/feed/","/2021/11/26/equity-fund-mobilisation-slows-in-october-shows-amfi-files/feed/","/2010/05/14/education-can-sometimes-help-those-with-mental-health-issues/"],"title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":false,"flag_case":false,"flag_query":"exact"},"options":{}},"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"https://www.articlesupdate.com/12/21/2021/home-appliances/handmade-hunting-lnives-what-you-need-to-know/"}}
Code: 403 Forbidden

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Raw: <!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<title> 403 Forbidden
</title></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">403</h1>
<h2 style="margin-top:20px;font-size: 30px;">Forbidden
</h2>
<p>Access to this resource on the server is denied!</p>
</div></div><div style="color:#f0f0f0; font-size:12px;margin:auto;padding:0px 30px 0px 30px;position:relative;clear:both;height:100px;margin-top:-101px;background-color:#474747;border-top: 1px solid rgba(0,0,0,0.15);box-shadow: 0 1px 0 rgba(255, 255, 255, 0.3) inset;">
<br>Proudly powered by  <a style="color:#fff;" href="http://www.litespeedtech.com/error-page">LiteSpeed Web Server</a><p>Please be advised that LiteSpeed Technologies Inc. is not a web hosting company and, as such, has no control over content found on this site.</p></div></body></html>
```

**Comment by johngodley** [comment] 2021-12-21 10:02
You need to fix the error shown above. This is caused by your site.

**Comment by johngodley** [comment] 2022-01-03 19:34
Closing for now, please reopen with more information.

**Closed by johngodley** 2022-01-03 19:34 UTC
