### ISSUE TITLE
Problem starting Redirection 5.1.2

### ISSUE THREAD

**Issue by richjunior** [johngodley/redirection#3562] opened 2023-02-24 19:05 UTC
```
Uncaught TypeError: Cannot read properties of undefined (reading '__') https://www.strawhomes.com/wp-content/plugins/redirection/redirection.js 2
```

Plugin: 5.1.2 4.2
WordPress: 5.4.12 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
JavaScript: https://www.strawhomes.com/wp-content/plugins/redirection/redirection.js?ver=5.1.2-f552e95c1d86a233313e7d65e8888ef5
REST API: https://www.strawhomes.com/wp-json/

**Comment by johngodley** [comment] 2023-03-04 13:56
This may be caused by another plugin. You should follow the onscreen instructions and look at your developer console.

**Comment by johngodley** [comment] 2023-04-15 13:36
Closing for now, please reopen with more details.

**Closed as completed by johngodley** 2023-04-15 13:36 UTC
Labels: need-feedback
