### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by poporu** [johngodley/redirection#1784] opened 2019-05-29 14:39 UTC
```
Plugin: 4.2.3
WordPress: 5.0.3 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
JavaScript: http://www.orchidconnect.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.orchidconnect.com/wp-json/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 500 Internal Server Error
Raw: <html>
</html>
```

**Comment by johngodley** [comment] 2019-06-01 16:34
Your WordPress REST API is returning a 500 error. This is probably caused by a security plugin.

**Comment by johngodley** [comment] 2019-06-07 17:51
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-06-07 17:51 UTC
Labels: need-feedback
