### ISSUE TITLE
Problem passing correct HTTP headers

### ISSUE THREAD

**Issue by jakeherp** [johngodley/redirection#1770] opened 2019-05-22 07:46 UTC
### Summary

We have an advanced use-case where a React site lives in the subfolder of our primary WordPress site. We use the `redirection` plugin to create the redirects for that to bring in the site living on a Netlify hosting plan. The WordPress site is hosted on Pantheon.

The redirect rule looks like this:
```
   Source URL: /agency/?(.*)
   Match: URL only
   When matched: Pass-through
   Target URL: https://xxxxx-agency.netlify.com/$1
   Group: Redirections     Position: 0
```

**EDIT:**
I have now played around with it further, without any success.
Instead of `Match: URL only` I selected `URL and HTTP header`, typing the appropriate MIME types for each file type.
My Regex for this looks like that:

```
Rule      Regex                       MIME Type
====================================================
Pages     \/agency\/?(\S+\/)?         text/html
XML       \/agency\/?(.*).xml$        application/xml
TXT       \/agency\/?(.*).txt$        text/plain
PNG       \/agency\/?(.*).png$        image/png
JPG       \/agency\/?(.*).jp[e]?g$    image/jpeg
GIF       \/agency\/?(.*).gif$        image/gif
WEBP      \/agency\/?(.*).webp$       image/webp
SVG       \/agency\/?(.*).svg$        image/svg+xml
CSS       \/agency\/?(.*).css$        text/css
JS        \/agency\/?(.*).js$         text/javascript
```

Example Redirect Rule for XML:
```
   Source URL: \/agency\/?(.*).xml$
   Match: URL and HTTP header
   HTTP Header: content-type     text/xml     Custom
   When matched: Pass-through
   Matched Target: https://xxxxx-agency.netlify.com/$1
   Unmatched Target: 
   Group: Redirections     Position: 1
```

### Expected Behavior

Files get redirected with their respective content-type passed in the HTTP header.

### Actual Behavior

All files seem to get passed an HTTP header of `content-type: "text/html"`, which is, of course, causing issues with images, sitemap.xml, robots.txt and other files. 

### Environment

WordPress 5.1.1
Redirection 4.2.3

**Comment by johngodley** [comment] 2019-05-26 07:46
This is not really how the passthrough was intended to be used and there is no provision for any kind of MIME detection. Any existing headers are added by your server, not Redirection. All Redirection does it is issue a `wp_remote_fopen ` for the target URL, and everything else is left up to your server configuration. It may be that you can add the MIME types to your server

**Comment by johngodley** [comment] 2019-06-01 16:37
Closing for now, please reopen with more details

**Closed by johngodley** 2019-06-01 16:37 UTC
Labels: need-feedback
