### ISSUE TITLE
[ 5.0-beta-1] Redirection Error

### ISSUE THREAD

**Issue by awakash** [johngodley/redirection#2692] opened 2021-01-11 20:26 UTC
```
Plugin: 5.0-beta-1
WordPress: 5.4.2 (single)
PHP: 7.3.25
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
JavaScript: https://mysite.com/wp-content/plugins/redirection/redirection.js?ver=5.0-beta-1-f11e19d490191e175d6c5523492f9337
REST API: https://mysite.com/wp-json/
Query: ?page=redirection.php

Error: Invalid redirect details (redirect_update_failed)
Raw: {"code":"redirect_update_failed","message":"Invalid redirect details","data":{"status":400,"error_code":323}}
```

**Comment by johngodley** [comment] 2021-01-11 20:32
This is usually caused by caching on your site.

**Comment by johngodley** [comment] 2021-01-17 14:34
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-01-17 14:34 UTC
