### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by valzee** [johngodley/redirection#2768] opened 2021-02-16 23:54 UTC
```
Plugin: 5.0.1
WordPress: 5.6.1 (single)
PHP: 7.3.23
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
JavaScript: https://med-advantage.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://med-advantage.com/wp-json/
Query: ?page=redirection.php

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <br />
<b>Warning</b>:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in <b>/home/medadv/public_html/wp-content/plugins/gravityforms/common.php</b> on line <b>924</b><br />
<br />
<b>Warning</b>:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in <b>/home/medadv/public_html/wp-content/plugins/gravityforms/common.php</b> on line <b>952</b><br />
<br />
<b>Warning</b>:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in <b>/home/medadv/public_html/wp-content/plugins/gravityforms/common.php</b> on line <b>956</b><br />
<br />
<b>Warning</b>:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in <b>/home/medadv/public_html/wp-content/plugins/gravityforms/common.php</b> on line <b>975</b><br />
<br />
<b>Warning</b>:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in <b>/home/medadv/public_html/wp-content/plugins/gravityforms/common.php</b> on line <b>2322</b><br />
<br />
<b>Warning</b>:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in <b>/home/medadv/public_html/wp-content/plugins/gravityforms/common.php</b> on line <b>2328</b><br />
<br />
<b>Warning</b>:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in <b>/home/medadv/public_html/wp-content/plugins/gravityforms/common.php</b> on line <b>2338</b><br />
{"status":"need-update","inProgress":true,"current":"4.1","next":"4.2","time":1613519637.18611907958984375,"manual":["ALTER TABLE `wp_redirection_logs` DROP `module_id`","ALTER TABLE `wp_redirection_logs` DROP `group_id`","ALTER TABLE `wp_redirection_404` ADD `domain` VARCHAR(255) NULL DEFAULT NULL AFTER `url`","ALTER TABLE `wp_redirection_404` ADD `http_code` INT(11) unsigned NOT NULL DEFAULT 0 AFTER `referrer`","ALTER TABLE `wp_redirection_404` ADD `request_method` VARCHAR(10) NULL DEFAULT NULL AFTER `http_code`","ALTER TABLE `wp_redirection_404` ADD `request_data` MEDIUMTEXT NULL DEFAULT NULL AFTER `request_method`","ALTER TABLE `wp_redirection_404` DROP INDEX `url`","ALTER TABLE `wp_redirection_404` CHANGE COLUMN `url` `url` MEDIUMTEXT NOT NULL"],"complete":25,"result":"ok","reason":"Add extra logging support"}
```

**Comment by johngodley** [comment] 2021-02-17 06:36
Please read the error details, it contains all the information about the problem, which appears to be caused by Gravity Forms.

**Comment by johngodley** [comment] 2021-03-27 12:58
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-27 12:58 UTC
