### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by vineet6649** [johngodley/redirection#1904] opened 2019-08-02 19:31 UTC
```
Plugin: 4.3.1
WordPress: 5.2.2 (single)
PHP: 7.1.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
JavaScript: https://www.bulkgemstones.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.bulkgemstones.com/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/home/ethiopia/public_html/bulkgemstones.com/wp-content/plugins/woocommerce/includes/class-wc-api.php</b> on line <b>372</b><br />
{"items":[],"total":0}
```

**Comment by johngodley** [comment] 2019-08-02 19:34
The problem is shown above:

`<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/home/ethiopia/public_html/bulkgemstones.com/wp-content/plugins/woocommerce/includes/class-wc-api.php</b> on line <b>372</b>`

**Comment by vineet6649** [comment] 2019-08-02 19:35
What should i do to resolve this?

**Comment by johngodley** [comment] 2019-08-02 19:55
As you can see in the error, the problem is in WooCommerce. You should direct your attention to WooCommerce and either disable the plugin or contact them for a fix.

**Comment by johngodley** [comment] 2019-08-10 11:25
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-08-10 11:25 UTC
Labels: need-feedback
