### ISSUE TITLE
Problem starting Redirection 4.1.1

### ISSUE THREAD

**Issue by mkruip05** [johngodley/redirection#1621] opened 2019-03-30 13:51 UTC
```
Uncaught SyntaxError: Invalid or unexpected token https://www.fashionstores-online.nl/wp-content/plugins/redirection/redirection.js?ver=4.1.1-fe636e19d78b7c1e78f5ebf2f550f37e 17
```

Plugin: 4.1.1
WordPress: 5.1.1 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
JavaScript: https://www.fashionstores-online.nl/wp-content/plugins/redirection/redirection.js
REST API: https://www.fashionstores-online.nl/wp-json/

**Comment by johngodley** [comment] 2019-03-30 14:15
Please open your browser's developer console and see if there are any other details. This is likely an error caused by another plugin

**Comment by johngodley** [comment] 2019-04-08 17:02
Closing for now, please reopen with more information

**Closed by johngodley** 2019-04-08 17:02 UTC
Labels: need-feedback
