### ISSUE TITLE
Redirection Error: while trying to export for Apache 

### ISSUE THREAD

**Issue by 101sam** [johngodley/redirection#3114] opened 2021-10-31 15:59 UTC
```
Plugin: 5.1.3 4.2
WordPress: 5.8.1 (single)
PHP: 7.4.24
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
JavaScript: https://kidsontheyard.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://kidsontheyard.com/wp-json/
Query: ?page=redirection.php&sub=io

Error: No route was found matching the URL and request method. (rest_no_route)
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method.","data":{"status":404}}
```

**Comment by 101sam** [comment] 2021-10-31 16:05
The problem happens when you install rankmath SEO and use redirection plugin instead rankmath redirection:

'''
 AH01071: Got error 'PHP message: WordPress database error Table 'koty_wordpress.wp_rank_math_redirections' doesn't exist for query SELECT COUNT(*) FROM wp_rank_math_redirections made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Redirection_Api_Import->route_plugin_import_list, Red_Plugin_Importer::get_plugins, Red_RankMath_Importer->get_data', referer: https://kidsontheyard.com/wp-admin/tools.php?page=redirection.php
'''

**Comment by johngodley** [comment] 2021-10-31 18:40
Those are not related problems. The second message is when you are trying to import from Rank Math and suggests you do not have any rank Math redirects.

**Comment by 101sam** [comment] 2021-10-31 18:46
We know but the problem is not importing the problem when we try to export from redirect we get this error

**Comment by johngodley** [comment] 2021-12-22 10:56
I don't understand what you are trying to show here. The first problem is a REST API issue, probably caused by a security plugin.

The second is caused when you try and import from rank math and don't have rank math installed.

Closing for now, please reopen with more information.

**Closed by johngodley** 2021-12-22 10:56 UTC
