### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by sardharajaydeep** [johngodley/redirection#2666] opened 2020-12-23 08:18 UTC
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.3.25
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
JavaScript: https://theacvprogram.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://theacvprogram.com/wp-json/

**Comment by johngodley** [comment] 2020-12-23 10:10
This is almost certainly caused by another plugin. Please read the onscreen instructions and look in your developer console.

**Comment by johngodley** [comment] 2021-01-10 10:43
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-01-10 10:43 UTC
