### ISSUE TITLE
Problem starting Redirection 2.10.1

### ISSUE THREAD

**Issue by msmaxsoft** [johngodley/redirection#600] opened 2018-01-05 09:29 UTC
```
Uncaught TypeError: t(...).iris is not a function http://***/wp-content/plugins/woocommerce/assets/js/admin/settings.min.js?ver=3.2.5 1,Uncaught TypeError: Cannot read property 'mouse' of undefined http://***/wp-includes/js/jquery/ui/resizable.min.js?ver=1.11.4 11,Uncaught TypeError: a.widget is not a function http://***/wp-includes/js/jquery/ui/button.min.js?ver=1.11.4 11,Uncaught TypeError: a.widget is not a function http://***/wp-includes/js/jquery/ui/dialog.min.js?ver=1.11.4 11
```

Plugin: 2.10.1
WordPress: 4.9.1
PHP: 5.6.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

**Comment by johngodley** [comment] 2018-01-05 09:31
Based on the error it looks like one of your other plugins (WooCommerce?) is causing a problem. You could try temporarily disabling your other plugins to identify which one is the cause, and then we can see if it can be worked around.

**Comment by johngodley** [comment] 2018-01-11 17:54
Closing for now, please reopen with more information

**Closed by johngodley** 2018-01-11 17:54 UTC
