### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by danielwebguy** [johngodley/redirection#1785] opened 2019-05-30 15:52 UTC
```
Plugin: 4.2.3
WordPress: 5.2.1 (single)
PHP: 7.0.10
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
JavaScript: https://www.hagaishalev.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.hagaishalev.com/wp-json/

Error: Unexpected token G in JSON at position 4 (SyntaxError)
Raw: 410 Gone
```

**Comment by johngodley** [comment] 2019-06-01 16:34
Your WordPress REST API is returning a 410 error. This is probably caused by a security plugin.

**Comment by johngodley** [comment] 2019-06-07 17:51
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-06-07 17:51 UTC
Labels: need-feedback
