### ISSUE TITLE
Problem starting Redirection 5.2.3

### ISSUE THREAD

**Issue by zsouhail** [johngodley/redirection#3267] opened 2022-03-24 22:31 UTC
Plugin: 5.2.3 4.2
WordPress: 5.9.2 (single)
PHP: 7.4.28
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
JavaScript: https://www.tetouanclub.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://www.tetouanclub.com/wp-json/

**Comment by johngodley** [comment] 2022-03-25 08:53
Please follow the onscreen instructions. This is likely caused by another plugin.

**Comment by johngodley** [comment] 2022-04-02 17:33
Closing for now, please reopen with more information.

**Closed by johngodley** 2022-04-02 17:33 UTC
