### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by EuroBusinessCar** [johngodley/redirection#2775] opened 2021-02-22 18:00 UTC
```
Plugin: 5.0.1
WordPress: 5.6.1 (single)
PHP: 7.3.23
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
JavaScript: http://candidat.online/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: http://candidat.online/wp-json/
Query: ?page=redirection.php&sub=options

Action: http://candidat.online/wp-json/redirection/v1/plugin/data/ POST
Code: 508 Loop Detected

Error: Unexpected token < in JSON at position 1 (SyntaxError)
Raw: 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML><HEAD>
<TITLE> 508 Resource Limit Is Reached</TITLE>
</HEAD><BODY>
<H1>Resource Limit Is Reached</H1>
The website is temporarily unable to service your request as it exceeded resource limit.
Please try again later.
</BODY></HTML>
```

**Comment by johngodley** [comment] 2021-02-22 18:19
The problem is shown above:

`508 Resource Limit Is Reached`

**Comment by johngodley** [comment] 2021-03-27 12:56
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-27 12:56 UTC
