### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by YardenF** [johngodley/redirection#1039] opened 2018-07-02 11:59 UTC
```
Plugin: 3.0.1
WordPress: 4.9.4
PHP: 7.0.8-0ubuntu0.16.04.3
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

Error: REST API disabled.
Action: redirection/v1/redirect?orderby=id GET
Code: 403 Forbidden
Raw: {"code":"rest_disabled","message":"REST API disabled.","data":{"status":403}}

Error: REST API disabled.
Action: redirection/v1/group GET
Code: 403 Forbidden
Raw: {"code":"rest_disabled","message":"REST API disabled.","data":{"status":403}}
```

**Comment by johngodley** [comment] 2018-07-02 12:00
The problem is shown in your message: `REST API disabled`

Please enable it to continue.

**Comment by johngodley** [comment] 2018-07-07 15:47
Closing for now, please reopen with more details

**Closed by johngodley** 2018-07-07 15:47 UTC
