### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by HendraWahyut** [johngodley/redirection#3271] opened 2022-04-03 06:36 UTC
```
Plugin: 5.2.3 4.2
WordPress: 5.9.2 (single)
PHP: 7.4.16
Browser: Mozilla/5.0 (Linux; Android 11; vivo 2007) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.73 Mobile Safari/537.36
JavaScript: https://ndra.sbs/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://ndra.sbs/wp-json/
Query: ?page=redirection.php
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    at Uu (https://ndra.sbs/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:462360)
    at p
    at div
    at Mu (https://ndra.sbs/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:462485)
    at wp (https://ndra.sbs/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:541382)
    at div
    at a (https://ndra.sbs/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:484680)
    at https://ndra.sbs/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:752964
    at f (https://ndra.sbs/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:376159)
    at Fe (https://ndra.sbs/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:374082)
    at s_
```

**Comment by johngodley** [comment] 2022-04-03 07:04
What are you doing when this happens? Could it be caused by another plugin or browser extension?

**Comment by johngodley** [comment] 2022-04-23 13:07
Closing for now, please reopen with more information.

**Closed by johngodley** 2022-04-23 13:07 UTC
