### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by vivekvag** [johngodley/redirection#2824] opened 2021-03-17 21:27 UTC
```
Plugin: 5.0.1
WordPress: 5.7 (single)
PHP: 7.3.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
JavaScript: https://pressboltnews.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://pressboltnews.com/wp-json/
Query: ?page=redirection.php

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}
```

**Comment by johngodley** [comment] 2021-03-17 22:07
This is caused by Cloudflare caching your REST API. You should exclude Cloudflare from /wp-json/

**Comment by johngodley** [comment] 2021-03-27 12:44
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-27 12:44 UTC
