### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Redouanhmeid** [johngodley/redirection#2508] opened 2020-10-26 03:50 UTC
```

Action: http://www.maany.life/wp-json/redirection/v1/group/ GET
Code: 404 Not Found

Error: لم يتم ايجاد مسار يتوافق مع الرابط ووسيلة الطلب. (rest_no_route)
Raw: {"code":"rest_no_route","message":"\u0644\u0645 \u064a\u062a\u0645 \u0627\u064a\u062c\u0627\u062f \u0645\u0633\u0627\u0631 \u064a\u062a\u0648\u0627\u0641\u0642 \u0645\u0639 \u0627\u0644\u0631\u0627\u0628\u0637 \u0648\u0648\u0633\u064a\u0644\u0629 \u0627\u0644\u0637\u0644\u0628.","data":{"status":404}}
```

**Comment by johngodley** [comment] 2020-10-26 08:57
Your REST API is returning a 404 error. This is likely caused by a security plugin.

**Comment by johngodley** [comment] 2020-11-08 17:37
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-08 17:37 UTC
Labels: need-feedback
