### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by wilburlikesmith** [johngodley/redirection#2571] opened 2020-11-12 10:45 UTC
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.2.34-8+0~20201103.52+debian9~1.gbpafa084
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36 Edg/86.0.622.63
JavaScript: https://rossouwmodern.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://rossouwmodern.com/wp-json/

**Comment by johngodley** [comment] 2020-11-12 10:46
This is almost certainly caused by another plugin. Please open your browser's developer console and look for other error information

**Comment by wilburlikesmith** [comment] 2020-11-12 10:50
Oh wow that was super quick. I am actually not sure if it's actually a problem and also my the cache plugin I'm replacing is the fix.

**Comment by johngodley** [comment] 2020-11-22 08:01
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-22 08:01 UTC
