### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by enricoaleandri** [johngodley/redirection#2626] opened 2020-12-07 14:16 UTC
After configuration wizard an error is provided and  I do not understand why the default provider page is returned.
Thank you

```
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.3.18-1+0~20200515.59+debian9~1.gbp12fa4f
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
JavaScript: https://www.marketingbio.it/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.marketingbio.it/wp-json/
Query: ?page=redirection.php

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-language" content="it" />
    <meta name="author" content="Tophost; http://www.tophost.it" lang="it" xml:lang="it" />
    <meta name="copyright" content="Tophost; http://www.tophost.it" lang="it" xml:lang="it" />
    <meta name="description" content="Attivazione del prodotto di hosting Topweb by Tophost" />
    <meta name="keywords" content="tophost, topweb, hosting, registrazione nome a dominio, php, mysql, database, antispam, antivirus, alias di posta, ftp, mysql, host" />
    <meta name="robots" content="all,follow" />
    <link href="/__tmp/topweb/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <title>Benvenuto su www.marketingbio.it</title>
  </head>
  <body>

    <div id="layout">
      
      <div id="header">
        
        <h1 id="logo"><a href="#" title='www.marketingbio.it'>www.marketingbio.it</a></h1>
        <div id="navigation">
        <ul>
          <li><a href="http://www.tophost.it" title="Tophost hosting e registrazione nome a dominio">&nbsp;<img src="/__tmp/topweb/tophost.png" alt="Tophost Internet Hosting" longdesc="Tophost hosting e registrazione nome a dominio" /></a></li>
        </ul>
        </div>
      </div>
      
<div class="rbroundbox">
	         <div class="rbtop"><div></div></div>
		          <div class="rbcontent">
          			
          		<div class="content">
				
              <h2>Benvenuto!</h2>
              <p>Ci complimentiamo per l'acquisto!

Questa pagina attesta la corretta registrazione e funzionamento del pacchetto <span class="strong">topweb</span>. Siamo sicuri che imparerai ad apprezzare fin da subito le potenzialità e la facilità d'uso del prodotto appena acquistato.    </p>
          
              </div>
              	         			
   		  </div>
	         <div class="rbbot"><div></div></div>
      </div>
          
      <div id="main"><div id="panel-right"><div id="panel-right-inside">
            <p>Clicca e scopri anche tu  le iniziative Tophost</p>
            <script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://ad.tophost.it/adssrv/www/delivery/ajs.php':'http://ad.tophost.it/adssrv/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=2");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://ad.tophost.it/adssrv/www/delivery/ck.php?n=a043a410&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://ad.tophost.it/adssrv/www/delivery/avw.php?zoneid=2&amp;n=a043a410' border='0' alt='' /></a></noscript>
</div>
      </div>
        <h2>Caratteristiche di <a href="http://www.tophost.it/sc/topweb/">Topweb</a></h2>
        <p>Queste qui sono le principali caratteristiche del tuo nuovo sito web.</p>
        <p>- <b>10 GB</b> di spazio ripartibile tra web, posta e mysql;<br />
        - supporto PHP e CGI;<br />
        - <b>trenta</b> indirizzi e-mail con infiniti alias, antispam e antivirus;<br />
        - <b>quattro</b> database mysql e phpmyadmin incluso;<br />
        - file manager web FTP per il trasferimento dei file dal proprio PC allo spazio web via browser web.</p>
        <h2>Area utente</h2>
        <p>Per cominciare fin da subito a prendere confidenza con tutte le funzionalità messe a disposizione, collegati all'area utente inserendo le credenziali di accesso che ti abbiamo inviato alla conferma dell'ordine. <a href="http://www.tophost.it/th/">Clicca qui per accedere all'Area utente.</a></p>
        <h2>Posta elettronica</h2>
        <p>Controlla la tua posta elettronica via web e invia dei messaggi ai tuoi amici, utilizzando il servizio di webmail incluso nel prodotto Tophost. Per accedere utilizza le credenziali di accesso che ti abbiamo inviato con la lettera di attivazione del prodotto. <a href='http://www.marketingbio.it/webmail/'>Clicca qui per accedere alla webmail.</a></p>
        <h2>Registrazione del nome a dominio</h2>
        <p> Il nome a dominio è sempre registrato a nome del cliente. In Tophost ci teniamo alla trasparenza.</p>
      </div>
  </div>
        <div id="footer">
        <div id="footer-inside">
        <p id="footersx"></p>
        <p id="footerdx">pagina di cortesia per <b>www.marketingbio.it</b> offerta da <a rel="nofollow" href="http://www.tophost.it"><b>TOPHOST</b> Internet Hosting Provider</a></p>
        </div><div style="clear: both;"></div></div>
  </body>
</html>

```

**Comment by johngodley** [comment] 2020-12-12 12:24
Please see https://redirection.me/support/problems/rest-api/

Closing for now, please reopen with more information.

**Closed by johngodley** 2020-12-12 12:24 UTC

**Comment by enricoaleandri** [comment] 2020-12-12 14:26
Thank you sir, the rest API works correctly as you can see at the following link: 
https://www.marketingbio.it/wp-json

I also checked all other problems: 

- The REST API has been disabled -> **Nope**
- You are using a REST API plugin  -> **Nope**
- Requests to the REST API are being redirected -> Not if directly invoked
- Trailing slashes are being trimmed from all URLs  -> **Nope**
- Security software is blocking requests  -> I don't think so
- Using different URLs for your site and WordPress URL settings in Settings > General  -> **Nope**
- Server settings do not pass authorisation  -> **Nope**

Any other idea?
Thank you so much

**Comment by johngodley** [comment] 2020-12-12 14:29
Your REST API opening in a browser does not indicate it fully works. In your original message you can see your site is returning something about Topweb. This is not caused by Redirection and is something your site is doing instead of returning the REST API response.
