### ISSUE TITLE
Redirection Error - Unexpected end of JSON input

### ISSUE THREAD

**Issue by cenemil** [johngodley/redirection#1685] opened 2019-04-18 16:55 UTC
```
Plugin: 4.1.1
WordPress: 4.5.17 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://www.lifestylepestcontrol.com.au/wp-content/plugins/redirection/redirection.js
REST API: https://www.lifestylepestcontrol.com.au/wp-json/

Error: Unexpected end of JSON input
Raw: -no data-
```
Upgrade database won't proceed due to the error stated above. Tried disabling plugins but it still shows error.

**Comment by cenemil** [comment] 2019-04-18 17:27
Smush Pro plugin could be causing the issue. Tried deactivating that plugin and wp-json works.

**Comment by johngodley** [comment] 2019-04-27 15:02
I couldn't reproduce the problem with the free smush plugin. 

If I try and access your REST API I get a 500 error:

https://www.lifestylepestcontrol.com.au/wp-json/

This is probably something that should be fixed, particularly if you intend to use Gutenberg.

**Comment by johngodley** [comment] 2019-05-04 14:05
Closing for now, please reopen with more details

**Closed by johngodley** 2019-05-04 14:05 UTC
Labels: need-feedback
