### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by dfkuehn** [johngodley/redirection#1516] opened 2019-02-28 18:58 UTC
```
Plugin: 4.0
WordPress: 5.1 (single)
PHP: 7.2.11
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0
JavaScript: http://www.tjmabrey.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.tjmabrey.com/wp-json/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 404 Not Found
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /boot-fs.php was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

```

**Comment by johngodley** [comment] 2019-02-28 19:03
The problem is shown in the message above, and you will need to fix whatever `boot-fs.php` is.

**Comment by johngodley** [comment] 2019-03-08 19:28
Closing for now, please reopen with more details

**Closed by johngodley** 2019-03-08 19:28 UTC
Labels: need-feedback
