### ISSUE TITLE
Problem starting Redirection 4.3.1

### ISSUE THREAD

**Issue by pippyn** [johngodley/redirection#1903] opened 2019-08-02 09:29 UTC
```
Uncaught SyntaxError: missing ) after argument list https://iamtoro.shop/wp-content/plugins/redirection/redirection.js?ver=4.3.1-76c2e333a0fb0e417d3c1937d0c4045c 12
```

Plugin: 4.3.1
WordPress: 5.2.2 (single)
PHP: 7.3.7
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
JavaScript: https://iamtoro.shop/wp-content/plugins/redirection/redirection.js
REST API: https://iamtoro.shop/wp-json/

**Comment by johngodley** [comment] 2019-08-03 09:57
Open your browser's developer console and see if any other information is shown. This is likely caused by another plugin

**Comment by johngodley** [comment] 2019-08-10 11:25
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-08-10 11:25 UTC
Labels: need-feedback
