### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by BIGtechnologies** [johngodley/redirection#2560] opened 2020-11-06 15:38 UTC
```
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.4.11
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
JavaScript: https://www.bigapp.work/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.bigapp.work/wp-json/
Query: ?page=redirection.php

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <p style="display: none">
<a href="https://besthomemania.com/"></a>
<a href="https://bestfoodcentral.com/"></a>
<a href="https://toptoycentral.com/"></a>
<a href="https://bestkitchencentral.com/"></a>
</p>
```

**Comment by BIGtechnologies** [comment] 2020-11-06 15:39
hey the website is down

**Comment by johngodley** [comment] 2020-11-06 15:40
Your website isn't down. It is displaying the same message shown above. This is not connected to Redirection.

**Comment by BIGtechnologies** [comment] 2020-11-06 15:49
ok thank you

**Comment by BIGtechnologies** [comment] 2020-11-06 15:51
is it a problem with a plugin you think?

**Comment by johngodley** [comment] 2020-11-06 15:52
No, it is not connected to the plugin.

Your website is outputting this:

```
<p style="display: none">
<a href="https://besthomemania.com/"></a>
<a href="https://bestfoodcentral.com/"></a>
<a href="https://toptoycentral.com/"></a>
<a href="https://bestkitchencentral.com/"></a>
</p>
```

That is not caused by the plugin. Unless you know what those links are I would say you site has been hacked.

**Comment by BIGtechnologies** [comment] 2020-11-06 15:54
it says i need to upgrade the redirection database but i get an error messge. sorry im not a developer

**Comment by johngodley** [comment] 2020-11-06 15:56
Yes, you can see in the error message this:

```
<p style="display: none">
<a href="https://besthomemania.com/"></a>
<a href="https://bestfoodcentral.com/"></a>
<a href="https://toptoycentral.com/"></a>
<a href="https://bestkitchencentral.com/"></a>
</p>
```

This is also appearing on your website. It is not produced by Redirection and is breaking your website and Redirection.

You will need to fix whatever is outputting that.

**Comment by BIGtechnologies** [comment] 2020-11-06 15:57
ok thank you very much

**Comment by johngodley** [comment] 2020-11-14 10:22
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-14 10:22 UTC
