### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by aacosae** [johngodley/redirection#2318] opened 2020-05-27 22:16 UTC
```
Plugin: 4.8
WordPress: 5.4.1 (single)
PHP: 7.3.18
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
JavaScript: https://mostex.ae/wp-content/plugins/redirection/redirection.js
REST API: https://mostex.ae/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>403 Forbidden</title>
  <link rel="stylesheet" href="/error_docs/styles.css">
</head>
<body>
<div class="page">
  <div class="main">
    <h1>Server Error</h1>
    <div class="error-code">403</div>
    <h2>Forbidden</h2>
    <p class="lead">You do not have permission to access this document.</p>
    <hr/>
    <p>That's what you can do</p>
    <div class="help-actions">
      <a href="javascript:location.reload();">Reload Page</a>
      <a href="javascript:history.back();">Back to Previous Page</a>
      <a href="/">Home Page</a>
    </div>
  </div>
</div>
</body>
</html>
```

**Comment by johngodley** [comment] 2020-05-28 06:47
As indicated in the plugin, this is likely caused by a security plugin of some kind.

**Comment by johngodley** [comment] 2020-06-06 09:32
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-06-06 09:32 UTC
