### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by faldhubaib** [johngodley/redirection#1551] opened 2019-03-11 18:05 UTC
```
Plugin: 3.7.3
WordPress: 4.9.9 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
JavaScript: https://www.simpleinfoapps.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.simpleinfoapps.com/wp-json/

Error: Unexpected token < in JSON at position 0
Raw: <br />
<b>Warning</b>:  mysqli_query(): MySQL server has gone away in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php</b> on line <b>1924</b><br />
<br />
<b>Warning</b>:  mysqli_query(): Error reading result set's header in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php</b> on line <b>1924</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1274</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api.php</b> on line <b>544</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api.php</b> on line <b>545</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api.php</b> on line <b>546</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/34/d407972395/htdocs/wordpress/wp-includes/wp-db.php:1924) in <b>/homepages/34/d407972395/htdocs/wordpress/wp-includes/rest-api.php</b> on line <b>547</b><br />
{"status":"need-update","inProgress":true,"current":"2.4","next":"2.4","time":1552327479.9394,"complete":14.3,"result":"ok","reason":"Migrate any groups with invalid module ID"}
```

**Comment by johngodley** [comment] 2019-03-11 18:06
The problem is shown above:

`MySQL server has gone away`

Do you have problems with your MySQL server?

**Comment by johngodley** [comment] 2019-03-16 08:06
Closing for now, please reopen with more details

**Closed by johngodley** 2019-03-16 08:06 UTC
Labels: need-feedback
