### ISSUE TITLE
Redirection Error invalid nonce

### ISSUE THREAD

**Issue by mike-henderson** [johngodley/redirection#1329] opened 2018-12-05 18:40 UTC
```
Plugin: 3.6.3
WordPress: 4.9.8 (single)
PHP: 7.2.12
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
JavaScript: /wp-content/plugins/redirection/redirection.js
REST API: /wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/setting/ GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/plugin/ GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

I've cleared cookies and logged out and back in multiple times. In previous versions I could get the plugin to hit the rest api using admin-ajax. That option from the dropdown has been removed in newer versions. I can hit the rest api as a normal user. Redirections are still working just can't list active redirections. We are running replicated with a different instance for wp-admin logins. Any thoughts?

**Comment by johngodley** [comment] 2018-12-09 14:51
This message is almost always fixed by logging out and logging back in again. If that doesn't fix it then you probably have some caching happening and need to clear that.

Yes, the admin-ajax route was removed. You will need to get your REST API working properly. Although you may be able to view the REST API, the problem is probably that you are not able to submit data to it, and this is likely a security plugin.

WordPress 5 will suffer a lot of the same problems.

**Comment by johngodley** [comment] 2018-12-15 19:34
Closing for now, please reopen with more information

**Closed by johngodley** 2018-12-15 19:34 UTC
Labels: need-feedback

**Comment by YesThatAllen** [comment] 2019-02-08 22:34
I experienced this today in my multisite setup after upgrading to the v4 beta 1

I ended up deleting the cookies for all the sites in my multisite, then logged back in and the plugin page worked as expected
