### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by alyai** [johngodley/redirection#2720] opened 2021-01-25 04:10 UTC
```
Plugin: 5.0
WordPress: 5.6 (single)
PHP: 7.4.13
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
JavaScript: https://sleepingculture.com/wp-content/plugins/redirection/redirection.js?ver=5.0-3451e9c29beac3055f61a8e45f1bf15e
REST API: https://sleepingculture.com/wp-json/
Query: ?page=redirection.php

Error: Failed to fetch
```

**Comment by johngodley** [comment] 2021-01-25 07:55
Have you tried changing the REST API? Your site is using Cloudflare and that may be causing problems.

**Comment by alyai** [comment] 2021-01-25 13:12
It used cloud flare before and never had any issue. Also if I bypass CF the issue is still persists and looks like many users having same issue after the upgrade.

**Comment by johngodley** [comment] 2021-01-25 13:14
The  issue is caused by something on your site preventing the plugin from communicating with your REST API. Cloudflare often causes problems like this, as does other caches and other software. Other users may have similar problems, and they are not specific to the new version.

**Comment by johngodley** [comment] 2021-03-27 13:08
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-27 13:08 UTC
