### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by kumasan007** [johngodley/redirection#2617] opened 2020-12-04 06:25 UTC
```
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.3.18
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
JavaScript: https://gamersettings.net/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://gamersettings.net/wp-json/
Query: ?page=redirection.php

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}
```

**Comment by johngodley** [comment] 2020-12-04 08:03
Is your site cached in anyway? You are trying to do a bulk action on a redirect that doesn't exist, and this is likely caused by caching issues.

**Comment by johngodley** [comment] 2020-12-19 12:23
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-12-19 12:23 UTC
