### ISSUE TITLE
rest_forbidden Redirection Error

### ISSUE THREAD

**Issue by utags** [johngodley/redirection#1665] opened 2019-04-14 16:11 UTC
I have an Ubuntu Nginx VPS. When I use this plugin "WordPress REST API" test, it shows everything Good. Although when I added redirect url, it gives "rest_forbidden". I have a Cloudflare origin certificate. (_cURL failed on this server_). May I know what's the reason for this issue? Does it use cURL?

When I open https://www.domain.com/wp-json/ url it shows the script without any error. 

When I added redirect URL this plugin stuck at Testing - 83% (REST API).

```
Plugin: 4.2.2
WordPress: 5.1.1 (single)
PHP: 7.3.4-1+ubuntu18.04.1+deb.sury.org+3
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://www.domain.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.domain.com/wp-json/

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```

**Comment by johngodley** [comment] 2019-04-15 17:19
I don't know what you mean about cURL and Cloudflare, but Cloudflare often does block things and cause these kind of problems. It may also be caused by any security plugins you have installed in WordPress.

**Comment by johngodley** [comment] 2019-04-19 12:38
Closing for now, please reopen with more information

**Closed by johngodley** 2019-04-19 12:38 UTC
Labels: need-feedback

**Comment by Warxcell** [comment] 2025-04-26 06:42
Same problem here. I have WordPress in Container - when I do 

```
curl -u user:"password" "https://publicly-available-uri.com/wp-json/redirection/v1/redirect\?filterBy\[url\]=%2Fdsa"
```

it works, I get 
```
{"items":[],"total":0}
```

but when I do

```
curl -u user:"password" "http://internal-network-ip/wp-json/redirection/v1/redirect\?filterBy\[url\]=%2Fdsa"
```

i get

```
{"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```

Logs from wordpress container:

```
162.158.216.122 - admin [26/Apr/2025:06:18:31 +0000] "GET /wp-json/redirection/v1/redirect\\?filterBy[url]=%2Fdsa HTTP/1.1" 200 646 "-" "curl/8.9.1"

10.0.34.5 - admin [26/Apr/2025:06:18:33 +0000] "GET /wp-json/redirection/v1/redirect\\?filterBy[url]=%2Fdsa HTTP/1.1" 401 604 "-" "curl/8.9.1"
```
