### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by Brianlfontenot** [johngodley/redirection#2650] opened 2020-12-17 01:57 UTC
Plugin: 4.9.2
WordPress: 5.6 (single)
PHP: 7.3.12
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
JavaScript: https://brianlfontenot.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://brianlfontenot.com/wp-json/

**Comment by johngodley** [comment] 2020-12-19 12:20
This is almost certainly caused by another plugin. If you open your browsers developer console it may show more information.

**Comment by johngodley** [comment] 2020-12-23 12:54
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-12-23 12:54 UTC
Labels: need-feedback
