### ISSUE TITLE
Problem starting Redirection 4.8

### ISSUE THREAD

**Issue by rjaoun** [johngodley/redirection#2375] opened 2020-07-08 23:29 UTC
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.3.17
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
JavaScript: https://www.karagesales.com/wp-content/plugins/redirection/redirection.js
REST API: https://rabihaoun.com/wp-json/

**Comment by johngodley** [comment] 2020-07-18 15:09
This is likely caused by another plugin. Please disable them and see which it is.

**Comment by johngodley** [comment] 2020-07-25 11:59
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-07-25 11:59 UTC
Labels: need-feedback
