### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by tfrisch** [johngodley/redirection#3127] opened 2021-11-11 21:11 UTC
```
Plugin: 5.1.3 4.2
WordPress: 5.8.2 (single)
PHP: 7.3.32
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
JavaScript: https://tonercoins.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://tonercoins.com/wp-json/
Query: ?page=redirection.php

Action: https://tonercoins.com/wp-json/redirection/v1/redirect/?orderby=id&direction=desc&per_page=25 POST
Params: {"id":0,"url":"https://tonercoins.com/?attachment_id=2090","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":false,"flag_case":false,"flag_query":"exact"},"options":{}},"match_type":"url","action_type":"url","position":0,"group_id":3,"action_code":301,"action_data":{"url":"https://tonercoins.com/product/1885-o-morgan-dollar-pcgs-ms/"}}
Code: 412 Unknown error

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <html><body><h1 style='text-align:center'>Error 412</h1><hr><center>Pyxsoft Pxshield</center></body></html>
```

**Comment by johngodley** [comment] 2021-11-11 22:08
You can see the problem above: `Pyxsoft Pxshield`

**Comment by tfrisch** [comment] 2021-11-11 22:28
Over my head I guess

**Comment by johngodley** [comment] 2021-11-12 06:26
The message is coming from your website. I don't know what it is, but it is not caused by Redirection.

**Comment by johngodley** [comment] 2022-01-09 16:45
Closing for now, please reopen with more information.

**Closed by johngodley** 2022-01-09 16:45 UTC
