### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by RahmathullahRM** [johngodley/redirection#3315] opened 2022-06-14 18:49 UTC
```
Plugin: 5.2.3 4.2
WordPress: 5.9.3 (single)
PHP: 8.1.6
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
JavaScript: https://nadal-forwarding.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://nadal-forwarding.com/wp-json/
Query: ?page=redirection.php&sub=io
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    at div
    at div
    at https://nadal-forwarding.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:714301
    at div
    at a (https://nadal-forwarding.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:724094)
    at f (https://nadal-forwarding.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:376159)
    at VE (https://nadal-forwarding.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:749609)
    at wp (https://nadal-forwarding.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:541382)
    at div
    at a (https://nadal-forwarding.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:484680)
    at https://nadal-forwarding.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:752964
    at f (https://nadal-forwarding.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:376159)
    at Fe (https://nadal-forwarding.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:374082)
    at s_
```

**Comment by johngodley** [comment] 2022-06-14 18:56
This is caused by a browser extension or another plugin.

**Comment by RahmathullahRM** [comment] 2022-06-14 20:20
can you explain about browser extension?

We have able to import but it shows everytime if we click on any other option in the redirection plugin

**Comment by johngodley** [comment] 2022-06-18 11:55
I don't have any more information about the browser extension, but possibly something else you are running in your browser or on your site is breaking the plugin.

**Comment by johngodley** [comment] 2022-06-25 10:12
Closing for now, please reopen with more information

**Closed by johngodley** 2022-06-25 10:12 UTC
