### ISSUE TITLE
Can't import a CSV file

### ISSUE THREAD

**Issue by illtrax** [johngodley/redirection#297] opened 2017-08-11 15:07 UTC
### Summary

Trying to import a CSV file. Anyone else having issues? I was able to export a CSV file but can't import. 

### Actual Behavior

Selecting a file or drag-and-drop not working. Nothing loads in the upload area.

### Steps to reproduce

Clicking Add File or drag-and-dropping a file.

### Environment

Tried Chrome Version 60.0.3112.90 (Official Build) (64-bit) and Edge, wordpress Version 4.8.1, Redirection Version 2.7

**Comment by dlipper2** [comment] 2017-08-11 18:53
Me too

**Comment by illtrax** [comment] 2017-08-11 19:20
Ok, good, not just me. I even tried importing the exported csv but it still didn't work.

**Comment by dlipper2** [comment] 2017-08-11 19:32
I tried using both Google sheets and Excel to create the CSV (other posters said that Excel sometimes inserts a semicolon). I changed the column headings to capital letters (Source URL, Target URL) just in case it was case-sensitive. Since I only have 96 redirects to do, I'm doing them by hand instead of waiting. Good luck!

**Comment by illtrax** [comment] 2017-08-11 19:38
Thanks. Yeah, I tried a bunch of ways. A few online generators. Notepad. Visual Studio Code. Nothing. I entered 90+ so far, manually. :P

**Comment by johngodley** [comment] 2017-08-11 20:32
Can one of you attach a CSV file that's failed to upload? One or two lines is fine.

**Comment by dlipper2** [comment] 2017-08-11 21:29
John,
[Here is the sheet as a Google Sheet](https://docs.google.com/spreadsheets/d/1tQVDDzpZhmk8H7RAgdSKD91z5PWHSCJQlahcjwE-Noc/edit?usp=sharing). I exported it using download as CSV. Did the same in Excel.  
Thanks!
Don

Don

**Comment by johngodley** [comment] 2017-08-12 07:21
Thanks. I've just tried that and it works fine for me.

> Selecting a file or drag-and-drop not working. Nothing loads in the upload area.

What happens when you click the button? Does a file selector appear?

What happens when you drag and drop a file over the dropzone? Does the border change colour?

Can you try this with your browser's error console enabled, and see if there are any errors

**Comment by chrisdadd** [comment] 2017-08-12 10:41
I'm having the same problem. Using Chrome Version 60.0.3112.90 (Official Build) (64-bit). The file dialog opens but doesn't list .csv files. If I choose All files from the file types and remove the .csv file extension, the importer attempts to import. Then shows 0 imported.

I have put the column headings in the first row. The URLs do not have quotes around them. Should they? I couldn't find any example CSVs so wasn't sure.

**Comment by johngodley** [comment] 2017-08-12 10:59
Hmm, I don't see any of that behaviour in Chrome or Edge. When the file dialog opens it's already showing All files, and when I pick a CSV file it imports things.

The CSV format is shown on the import/export page. It must be a valid CSV file - quotes are optional unless your column has a comma in it, and the separator is a comma. This is not specific to Redirection, but just standard CSV format.

@chrisdadd does the Google Sheet link above work for you if you export as CSV and then import into Redirection? That is a valid CSV file

**Comment by chrisdadd** [comment] 2017-08-12 11:13
Hi John, no the google sheet link version doesn't work after saving as a csv either on Chrome or Edge. Even if I manually create a redirection link and view the csv using the export function, copy paste into a text file and try to reimport it, it fails to find data. Interestingly the column titles shown in the export are different (see below) so are the words in the header row important?:

source,target,regex,type,code,match,hits,title
"/dealer-log-in/dynaudiopro-lyd-media","/dealer-log-in/dynaudio-pro-media/","0","url","301","url","0",""

I'm prepared to create a login for you on the test site I'm working on to see if you can import to it - then we'd know if it was a browser issue my end or a clash of plugins, or directory permissions for example. 

I'm running latest Wordpress with Divi Theme and a bunch of plugins.

**Comment by johngodley** [comment] 2017-08-12 12:01
No, the header is ignored. The export has more data, but only the first part is used when importing - the rest is ignored.

A login would be very useful! If you click on my avatar you can send it through the contact form on my site

**Comment by johngodley** [comment] 2017-08-12 12:18
Got it. I tried with the CSV exported from the above Google Sheet and it worked perfectly in Chrome 60.0.3112.90 and Edge.  I'm a little puzzled now as it seems to be specific to your computers.

Can you try clearing your browser cache and reloading the page?

**Comment by chrisdadd** [comment] 2017-08-12 12:43
Thanks John. I've cleared the cache including app data and reloaded. No difference. Interestingly, when I loaded the site in Opera (which is the first time I've loaded the site), I get the same file dialog behaviour of it opening with Custom Files and therefore not showing csv. I also did a reboot just in case.  

Are you running the latest Windows 10 Creator update? Wondering if it's to do with the interface between browsers and generic Windows Explorer functionality for the file selection piece. Although it doesn't explain why when I remove the file extension and the plugin then accepts the file, it still doesn't import correctly as I assume the file is uploaded to a directory first, then your plugin processes it server-side?

**Comment by johngodley** [comment] 2017-08-12 12:58
Tried Edge on Windows 10 version 1703, and Chrome on MacOS.

Something to try is to to perform an upload with the developer tools open, which will be easier in Chrome. If you open the page in Chrome with the developer tools window open and then refresh the page you should see a request to `admin-ajax.php`. Then drop a CSV file into the dropzone and upload it. You should see another request to `admin-ajax.php` - click on it, and you'll see the request. If you copy the request payload (right click on the request), and then click on the 'response' tab and copy the response, and send both to me then it might show something. Don't include your cookie in the data!

**Comment by johngodley** [comment] 2017-08-12 13:06
And yes, to answer your question, the file is just uploaded as a normal file upload and is then processed by the server. The only way it would be different is if the file isn't being uploaded correctly. You could add some debug to the plugin to see what is being received. On this line:

https://github.com/johngodley/redirection/blob/master/redirection-api.php#L48

If you add above or below:

`error_log(print_r($_FILES,true));`

Then your server error log will contain information about what was sent.

One final thought, do you have Excel installed? I don't, but I think it may alter some system settings for CSV and it's possible this is somehow changing things in the upload. The `error_log` should show that. It may be worth exporting from Redirection as JSON and the importing that file to see if it works.

**Comment by chrisdadd** [comment] 2017-08-12 13:57
Hi John,
I did the export to JSON and reimported. That worked. So maybe the excel installation handling csv types somehow interferes with this.  I have converted my csv into the JSON format you're using with this online tool http://www.convertcsv.com/csv-to-json.htm and managed to load my records. 

I'll have to look into the debug options later once I've got my client's site live. Thanks for your help and perhaps update this thread if someone finds the cause.

**Comment by johngodley** [comment] 2017-08-12 15:03
Yeah, it seems specific to CSV. I have an idea for a few tweaks I can make that will help, and I'll include those in 2.7.1. If you do get chance to try out the debug option that would be great.

**Comment by albertalbs** [comment] 2017-08-14 06:22
@johngodley 

I too having the same issue. I tried all the possible options, like CSV, JSON and Different browsers Firefox, Chrome, Opera, MS Edge even in private more. Nothing worked. 

I thing it is bug inside plugin. Need a urgent solution for now. Is there any other plugin can help uploading bulk 301 redirects?

**Comment by albertalbs** [comment] 2017-08-14 06:53
**Found a solution:**

Installed following two plugins:

1. https://wordpress.org/plugins/simple-301-redirects/
2. https://wordpress.org/plugins/simple-301-redirects-addon-bulk-uploader

And then uploaded bulk CSV file. That is it. 

1st column contains OLD URL. 
2nd column contains NEW URL. 
(URL will start without domain name. It is just a post name). 

**- Live saved. 
- Profit.** 

The only problem is, Both the plugins does not supports UTF Characters in URL. For example Tamil 
 (தமிழ்) Characters in URL is not supported via bulk upload. So need to add those manually in Redirection page.

**Comment by johngodley** [comment] 2017-08-14 06:56
@albertalbs neither of those plugins are connected to Redirection and I don't see how they could import into Redirection.

As detailed above, the problem is likely software installed on the computer being used - the plugin itself is importing files. I have released 2.7.1 which has some changes to what files can be dropped into the plugin so as to hopefully remove any issues with CSV files.

**Comment by albertalbs** [comment] 2017-08-14 07:04
@johngodley I really liked your plugin. But in real time, I only faced importing via CSV. Rest all is ok. LIke 404 Monitoring is really a good feature. 
**I will again evaluate your plugin in new WP installations.** 

The main reason I was coming to bulk upload is, our WordPress installation is hosted in AWS and some permission issues, while adding/updating .htaccess files. So the last option is change the permalink and then do 301 redirection via bulk upload.

**Comment by johngodley** [comment] 2017-08-17 05:35
I'm going to close this as resolved with 2.7.1, but reopen if not

**Closed by johngodley** 2017-08-17 05:35 UTC
