### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Bio4Pets2017** [johngodley/redirection#3462] opened 2022-11-05 20:06 UTC
```
Plugin: 5.3.4 4.2
WordPress: 6.1 (single)
PHP: 7.4.32
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
JavaScript: https://www.bio4pets.nl/wp-content/plugins/redirection/redirection.js?ver=5.3.4-04d536d277e6e20820f24f21d395db08
REST API: https://www.bio4pets.nl/wp-json/
Query: ?page=redirection.php&sub=options

Error: Unexpected token '<', "<!DOCTYPE "... is not valid JSON (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```

**Comment by johngodley** [comment] 2022-11-05 20:19
The problem is shown above. Your REST API is broken and you will need to fix it.

**Comment by johngodley** [comment] 2022-11-26 12:32
Closing for now, please reopen with more information.

**Closed as completed by johngodley** 2022-11-26 12:32 UTC
