### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Eneva** [johngodley/redirection#2332] opened 2020-06-10 07:32 UTC
```
Plugin: 4.8
WordPress: 5.4.1 (single)
PHP: 7.2.31
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
JavaScript: http://besthomeideas.com.au/wp-content/plugins/redirection/redirection.js
REST API: http://besthomeideas.com.au/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 404 Not Found
Raw: <!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" lang="en-US"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="viewport" content="width=device-width"><meta name='robots' content='noindex,follow' /><link media="all" href="http://besthomeideas.com.au/wp-content/cache/autoptimize/css/autoptimize_9440d57b0ae26227e7e0b51bb735d544.css" rel="stylesheet" /><title>404 - Page not found</title></head><body id="error-page"><div class="wp-die-message">Page not found.</div></body></html>
```

**Comment by johngodley** [comment] 2020-06-10 07:36
The problem is shown in the message above. If you access your WordPress REST API it returns a 404:

http://besthomeideas.com.au/wp-json/

You will need to fix whatever is causing that 404. It should look like this:

http://redirection.me/wp-json/

**Comment by johngodley** [comment] 2020-06-29 05:34
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-06-29 05:34 UTC
Labels: need-feedback
