### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by nounzein** [johngodley/redirection#2708] opened 2021-01-18 15:29 UTC
```
Plugin: 5.0
WordPress: 5.6 (single)
PHP: 7.3.20
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
JavaScript: https://nordlinger-pro.com/wp-content/plugins/redirection/redirection.js?ver=5.0-3451e9c29beac3055f61a8e45f1bf15e
REST API: /wp-json/
Query: ?page=redirection.php&sub=support

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by johngodley** [comment] 2021-01-25 08:37
Your REST API is returning an error, probably caused by a security plugin.

**Comment by johngodley** [comment] 2021-03-27 13:10
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-27 13:10 UTC
Labels: need-feedback
