### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by mermolenko1** [johngodley/redirection#3540] opened 2023-01-27 15:11 UTC
Hello! I've been trying to delete a redirect after changing the URL of a page to a new one, but while I was able to delete a earlier redirection of the same page, I haven't been able to disable or delete the new iteration of the redirect, below you'll find the debug code that keeps popping up. 

```
Plugin: 5.3.2 4.2
WordPress: 6.0.3 (single)
PHP: 7.4.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.69
JavaScript: https://www.catalyst.org/wp-content/plugins/redirection/redirection.js?ver=5.3.2-c785eb862c23d732cc3689b27f4eec09
REST API: https://www.catalyst.org/wp-json/
Query: ?page=redirection.php

Action: https://www.catalyst.org/wp-json/redirection/v1/bulk/redirect/delete/?orderby=id POST
Params: {"items":[2384]}
Code: 400 Bad Request

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}
```

**Comment by johngodley** [comment] 2023-03-04 14:01
This is likely caused by an aggressive cache on your site. You should clear it and make sure it doesn't affect your REST API.

**Comment by johngodley** [comment] 2023-04-15 13:37
Closing for now, please reopen with more details.

**Closed as completed by johngodley** 2023-04-15 13:37 UTC
Labels: need-feedback
