### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by mazika4way** [johngodley/redirection#2335] opened 2020-06-10 17:20 UTC
```
Plugin: 4.8
WordPress: 5.4.1 (single)
PHP: 7.2.31
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
JavaScript: https://tv.cima4up.com/wp-content/plugins/redirection/redirection.js
REST API: https://tv.cima4up.com/wp-json/

Error: لم يتم ايجاد مسار يتوافق مع الرابط ووسيلة الطلب. (rest_no_route)
Raw: 

 {"code":"rest_no_route","message":"\u0644\u0645 \u064a\u062a\u0645 \u0627\u064a\u062c\u0627\u062f \u0645\u0633\u0627\u0631 \u064a\u062a\u0648\u0627\u0641\u0642 \u0645\u0639 \u0627\u0644\u0631\u0627\u0628\u0637 \u0648\u0648\u0633\u064a\u0644\u0629 \u0627\u0644\u0637\u0644\u0628.","data":{"status":404}}

Error: Failed to fetch
```

**Comment by johngodley** [comment] 2020-06-29 05:34
Your REST API is being blocked. This is probably caused by a security plugin.

**Comment by johngodley** [comment] 2020-07-18 15:25
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-07-18 15:25 UTC
Labels: need-feedback
