### ISSUE TITLE
Problem starting Redirection 4.5.1

### ISSUE THREAD

**Issue by younesshadani** [johngodley/redirection#2107] opened 2019-12-27 22:49 UTC
Plugin: 4.5.1
WordPress: 5.3.2 (single)
PHP: 7.3.6
Browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
JavaScript: http://www.sidiahmedbenali.ezyro.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.sidiahmedbenali.ezyro.com/wp-json/

**Comment by johngodley** [comment] 2019-12-28 10:29
Please open your browser's developer console and see if any more errors are shown. This is likely caused by another plugin.

**Comment by johngodley** [comment] 2020-01-11 13:36
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-01-11 13:36 UTC
