### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by Itxtech0** [johngodley/redirection#2544] opened 2020-11-04 07:06 UTC
```
Uncaught TypeError: jQuery(...).live is not a function https://www.captionslife.com/wp-admin/tools.php?page=redirection.php&sub=options 1797
```

Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.4.8
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
JavaScript: https://www.captionslife.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.captionslife.com/?rest_route=/

**Comment by johngodley** [comment] 2020-11-04 07:07
This is not caused by Redirection and is likely another plugin.

**Comment by johngodley** [comment] 2020-11-08 17:40
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-08 17:40 UTC
