### ISSUE TITLE
Problem starting Redirection 5.1.1

### ISSUE THREAD

**Issue by prangishviliAbe** [johngodley/redirection#3225] opened 2022-02-06 09:11 UTC
Plugin: 5.1.1 4.2
WordPress: 5.4.9 (single)
PHP: 7.4.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36
JavaScript: /redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: https://internationaldoctoralschool.iliauni.edu.ge/wp-json/

**Comment by johngodley** [comment] 2022-02-06 09:22
Please follow the onscreen instructions. This is caused by another plugin, or some setup on your site. The JavaScript file  location is wrong for a start

**Comment by johngodley** [comment] 2022-02-12 16:13
Closing for now, please reopen with more information.

**Closed by johngodley** 2022-02-12 16:13 UTC
