### ISSUE TITLE
Redirection Error when creating group

### ISSUE THREAD

**Issue by dayunz** [johngodley/redirection#311] opened 2017-08-17 09:49 UTC
Hi,

Here is my problem when I try to add a group.

Thank you,

Jm

```
Versions: Plugin 2.7.1, WordPress 4.8.1, PHP 5.5.9-1ubuntu4.22
Nonce: 3a1294da50

Action: red_set_group
Params: {"orderBy":"id","selected":[],"filterBy":"","filter":"","id":0,"name":"kjmlfkj","moduleId":1}
Code: 200 OK
Error: Invalid group or parameters (135)
Raw: {"error":"Invalid group or parameters (135)"}
```

**Comment by johngodley** [comment] 2017-08-26 14:05
Can you try 2.7.3 and see if the error exists, and if there is more information?

**Comment by dayunz** [comment] 2017-08-29 22:26
Hi,

I tried with 2.7.3, and here is the error : 
WordPress: 4.8.1
PHP: 5.5.9-1ubuntu4.22
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
Nonce: acd1837cb3
URL: http://<site>/wp-admin/admin-ajax.php

Error: Invalid group or parameters (165): Table 'artdusexecom.wp_redirection_groups' doesn't exist
Action: red_set_group
Params: {"orderBy":"id","filterBy":"","filter":"","id":0,"name":"test","moduleId":1}
Code: 200 OK
Raw: {"error":{"message":"Invalid group or parameters","code":165,"wpdb":"Table 'artdusexecom.wp_redirection_groups' doesn't exist"}}

**Comment by johngodley** [comment] 2017-08-30 05:17
Ok, the error explains exactly what the problem is - your groups table does not exist.

To fix this you will need to press the red delete button on the redirection settings page and then re-activate the plugin.

Note this will delete everything in the plugin. Please export any data you wish to keep.

**Comment by johngodley** [comment] 2017-09-07 05:29
Closing for now, please provide more details if the problem still exists

**Closed by johngodley** 2017-09-07 05:29 UTC
