### ISSUE TITLE
Problem starting Redirection 5.1.3

### ISSUE THREAD

**Issue by armadio1** [johngodley/redirection#3003] opened 2021-07-29 18:24 UTC
Plugin: 5.1.3 4.2
WordPress: 5.8 (single)
PHP: 7.2.34
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
JavaScript: https://webonlinecare.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://webonlinecare.com/wp-json/

**Comment by johngodley** [comment] 2021-07-31 14:07
Please read the onscreen instructions. This is almost certainly caused by another plugin.

**Comment by johngodley** [comment] 2021-08-22 13:39
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-08-22 13:39 UTC
