### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by redashalaby44** [johngodley/redirection#3453] opened 2022-11-01 01:19 UTC
```
Plugin: 5.3.4 4.2
WordPress: 6.0.3 (single)
PHP: 7.4.32
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
JavaScript: https://www.house-golden.com/wp-content/plugins/redirection/redirection.js?ver=5.3.4-04d536d277e6e20820f24f21d395db08
REST API: https://www.house-golden.com/wp-json/
Query: ?page=redirection.php&sub=io

Error: Invalid group (redirect_import_invalid_group)
Raw: {"code":"redirect_import_invalid_group","message":"Invalid group","data":{"status":400,"error_code":85}}
```

**Comment by johngodley** [comment] 2022-12-03 11:17
As it says you are using an invalid group. I don't know how that might happen but probably it is caused by a cache on your site.

**Comment by johngodley** [comment] 2022-12-10 10:36
Closing for now, please reopen with more information.

**Closed as completed by johngodley** 2022-12-10 10:36 UTC
