### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by webmyc** [johngodley/redirection#2561] opened 2020-11-06 19:32 UTC
Plugin: 4.9.2
WordPress: 5.5.1 (single)
PHP: 7.4.9
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
JavaScript: https://mihai.love/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://mihai.love/wp-json/

**Comment by johngodley** [comment] 2020-11-06 19:33
The problem is almost certainly caused by another plugin. Please open your browser's developer console for more information

**Comment by johngodley** [comment] 2020-12-12 12:27
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-12-12 12:27 UTC
