### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by runridedive** [johngodley/redirection#2535] opened 2020-11-01 06:26 UTC
```
Plugin: 4.9.2
WordPress: 5.5.1 (single)
PHP: 7.4.11
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
JavaScript: https://www.runridedive.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.runridedive.com/wp-json/
Query: ?page=redirection.php

Action: https://www.runridedive.com/wp-json/redirection/v1/plugin/database/ POST
Code: 500 Internal Server Error

Error: <p>There has been a critical error on your website.</p><p><a href="https://wordpress.org/support/article/debugging-in-wordpress/">Learn more about debugging in WordPress.</a></p> (internal_server_error)
Raw: {"code":"internal_server_error","message":"<p>There has been a critical error on your website.<\/p><p><a href=\"https:\/\/wordpress.org\/support\/article\/debugging-in-wordpress\/\">Learn more about debugging in WordPress.<\/a><\/p>","data":{"status":500},"additional_errors":[]}
```

**Comment by johngodley** [comment] 2020-11-01 09:11
Your WordPress REST API is broken:

https://www.runridedive.com/wp-json/

**Comment by runridedive** [comment] 2020-11-01 09:22
Hi, unfortunately what you replied means nothing to me. What needs to be done?

**Comment by johngodley** [comment] 2020-11-01 09:24
You need to fix the URL above on your site. This is not caused by Redirection, but is breaking the plugin.

**Comment by runridedive** [comment] 2020-11-01 09:39
Okay. what needs to be done?

**Comment by johngodley** [comment] 2020-11-01 09:48
As I said, it's not caused by the plugin, and is a general WordPress problem that you will need to investigate yourself. You can follow the link in the message, and maybe contact your hosting provider. You should see the same problem if you look at your Site Health.

**Comment by johngodley** [comment] 2020-11-08 17:39
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-08 17:39 UTC
