### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by RonenMars** [johngodley/redirection#1854] opened 2019-06-25 15:03 UTC
```
Plugin: 4.3.1
WordPress: 5.2.2 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
JavaScript: http://pereg.ronenmars.com/wp-content/plugins/redirection/redirection.js
REST API: http://pereg.ronenmars.com/wp-json/

Error: Unable to add new redirect (58)
Action: redirection/v1/redirect/ POST
Params: {"id":0,"url":"/workers.asp?category=%F9%E5%FA%F4%E9%ED","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":false,"flag_case":false,"flag_query":"exact"}},"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"/אודות/רו״ח-משה-פרג/"}}
Code: 400 Bad Request
Raw: {"code":"redirect","message":"Unable to add new redirect","data":{"status":400,"error_code":58}}
```

**Comment by johngodley** [comment] 2019-07-13 16:42
This is caused by your source URL, which appears to contain an invalid character. What is it supposed to be?

If you enter `%F9%E5%FA%F4%E9%ED` into https://meyerweb.com/eric/tools/dencoder/ and decode, then nothing is shown.

**Comment by johngodley** [comment] 2019-07-21 08:25
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-07-21 08:25 UTC
Labels: need-feedback
