### ISSUE TITLE
Problem starting Redirection 4.9

### ISSUE THREAD

**Issue by azokatheo** [johngodley/redirection#2498] opened 2020-10-24 15:09 UTC
```
Uncaught TypeError: Cannot read property 'setLocaleData' of undefined https://www.recruitmenttrust.com/wp-admin/tools.php?page=redirection.php 391,Uncaught TypeError: Cannot read property 'setLocaleData' of undefined https://www.recruitmenttrust.com/wp-admin/tools.php?page=redirection.php 413,Uncaught TypeError: Cannot read property 'setLocaleData' of undefined https://www.recruitmenttrust.com/wp-admin/tools.php?page=redirection.php 428,Uncaught TypeError: $(...).wpColorPicker is not a function https://www.recruitmenttrust.com/wp-content/plugins/simple-job-board/admin/js/simple-job-board-admin.js?ver=1.3.0 377
```

Plugin: 4.9
WordPress: 5.5.1 (single)
PHP: 7.2.24-0ubuntu0.18.04.7
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
JavaScript: https://www.recruitmenttrust.com/wp-content/plugins/redirection/redirection.js?ver=4.9-2dd41d397208f86537f3e2656caeb502
REST API: https://www.recruitmenttrust.com/wp-json/

**Comment by johngodley** [comment] 2020-10-24 15:11
That looks like an error caused by another plugin

**Comment by johngodley** [comment] 2020-11-08 17:36
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-08 17:36 UTC
Labels: need-feedback
