### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by careeralley** [johngodley/redirection#3227] opened 2022-02-06 17:17 UTC
```
Plugin: 5.2.3 4.2
WordPress: 5.8.3 (single)
PHP: 7.4.26
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
JavaScript: https://careeralley.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://careeralley.com/wp-json/
Query: ?page=redirection.php

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}
```

**Comment by careeralley** [comment] 2022-02-06 17:18
Some redirections are not working, not sure why.  When I try to delete it I get the attached error

**Comment by johngodley** [comment] 2022-02-06 18:23
This is caused by a cache on your site.

**Comment by careeralley** [comment] 2022-02-06 18:42
Could that be Cloudflare?




***@***.***
http://CareerAlley.com

**Comment by johngodley** [comment] 2022-02-12 16:13
Possibly. The redirects have been deleted, but your site has cached them and is saying they still exist.

**Comment by johngodley** [comment] 2022-02-19 14:48
Closing for now, please reopen with more information.

**Closed by johngodley** 2022-02-19 14:48 UTC
