### ISSUE TITLE
Swedish characters does not work as Source URL

### ISSUE THREAD

**Issue by sagaio** [johngodley/redirection#936] opened 2018-05-11 12:07 UTC
### Summary

We recently migrated from the extremly simple (i've gone through the code and it's tiny) plugin "Simple 301 Redirects" to this plugin and "Simple 301 Redirects" could handle these characters without any problems but Redirection can't.
I think this has something to do with your decoding/sanitation process but I'm not sure we really need this to work since there are ALOT of URLs with the characters described below.

Redirecting FROM swedish characters Å, Ä, Ö to another URL does not work.
Source URL: /köp
Target URL: /shop

### Actual Behavior

Returns a 404

### Environment

Redirection: 3.2
WordPress: 4.9.5

**Comment by johngodley** [comment] 2018-05-19 13:05
These characters will need to be URL encoded:

https://meyerweb.com/eric/tools/dencoder/

`/k%C3%B6p`

**Comment by sagaio** [comment] 2018-05-19 13:46
Thanks but I’m more interested in a permanent built in solution since this is not intuitive or normal to ask from an end user and complicates exports/imports very much. Has development stopped for this plugin or is there simply no interest in making it better?

Do you have any hint or

**Comment by johngodley** [comment] 2018-05-19 14:01
> Has development stopped for this plugin or is there simply no interest in making it better?

I'm not sure what gave you that impression, but no, development has not stopped. And yes, there is interest in making the plugin better.

However, I have a limited amount of time to make changes, there are a lot of requests, and a large user base that can be negatively affected if things start behaving differently. In this instance changing how the plugin works could affect a lot of people, and so it's not something I can casually do.

> where I might find the code which prevents these characters from being interpreted correctly

The problem is not as simple as that, and it is something I intend to improve in the future. For the moment the solution is to manually encode the characters.

**Comment by sagaio** [comment] 2018-05-19 20:46
Thanks for your response!

I've found a solution and it is quite simple but took some time to figure out.
Add this to `functions.php`

```
add_filter( 'redirection_request_url', 'redirection_decode' );
function redirection_decode($url) {
    return urldecode($url);
}
```

Perhaps you could add an option/checkbox under "Options" in the plugin to give the users ability to "Enable URL decoding for supporting special language characters"?

**Comment by johngodley** [comment] 2018-05-20 06:50
Thanks. Solving the problem isn't an issue, but as I said it affects a lot of sites and is not something I can just add in without a lot of consideration. Equally I don't want to add it as an option as it will just make the situation make complicated to fix properly. If the above solves the problem for you then that's great.

I'll close this for now

**Closed by johngodley** 2018-05-20 06:50 UTC
