### ISSUE TITLE
Problem starting Redirection 4.3.3

### ISSUE THREAD

**Issue by ley995** [johngodley/redirection#1930] opened 2019-08-22 07:44 UTC
Plugin: 4.3.3
WordPress: 5.2.2 (multi)
PHP: 5.6.40-5+ubuntu14.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
JavaScript: http://bme.hcmiu.edu.vn/wp-content/plugins/redirection/redirection.js
REST API: http://bme.hcmiu.edu.vn/wp-json/

**Comment by johngodley** [comment] 2019-08-22 08:05
This is likely caused by another plugin. Please open your developer console and see if more information is shown

**Comment by johngodley** [comment] 2019-08-25 07:04
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-08-25 07:04 UTC
