### ISSUE TITLE
plugin installation cause the wordpress site structure redirection to fail

### ISSUE THREAD

**Issue by bwleung** [johngodley/redirection#617] opened 2018-01-12 16:01 UTC
I used redirection plugin 2.10.1 on Monday Jan 8, 2018 to establish a redirection rule for a URL and though it would be useful for other admins to use it.

However, on 1/11/18, the site broke with the symptoms that the home page could be displayed but when clicking into a post, I got a 404 redirection error and nothing could be displayed. he NGINX error log was filled with entried like this:

2018-01-11 14:14:47 | Error | 172.68.174.97 |   | 18086#0: *25110 "/var/www/vhosts/thewoksoflife.com/httpdocs/feed/index.html" is not found (2: No such file or directory) |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
2018-01-11 14:14:47 | Error | 162.158.62.186 |   | 18086#0: *25111 "/var/www/vhosts/thewoksoflife.com/httpdocs/2013/10/cantonese-steamed-fish/index.html" is not found (2: No such file or directory) |   |   |  
2018-01-11 14:14:47 | Error | 162.158.74.144 |   | 18071#0: *25112 "/var/www/vhosts/thewoksoflife.com/httpdocs/2015/04/vegetable-noodles-with-shrimp/index.html" is not found (2: No such file or directory)

I tried to disable the redirection plugin without success and after much troubleshooting, realized that the redirection in my server or perhaps wordpress must have broken somehow and it was related to the redirection plugin.  I am not familiar with exactly how the redirection is accomplished but I have always had the wordpress permalinks set to month and date.

In order to restore the problem, 

I had to restore my mysql database to the previous night's back up.

Then, I had to place the following emergency code snippet into the nginx configuration on my server to restore the problem:

if (!-e $request_filename) {
	set $test P;
}
if ($uri !~ ^/(plesk-stat|webstat|webstat-ssl|ftpstat|anon_ftpstat|awstats-icon|internal-nginx-static-location)) {
	set $test "${test}C";
}
if ($test = PC) {
	rewrite ^/(.*)$ /index.php?$1;
}

This is working but is a temporary fix.

So the question is, what did the redirection plugin do to changed the default settings, if it did, in wordpress or my server and how do I change it back?  I also want to drop any tables in mysql and remove any other file created or modified by the plugin so I accomplish a clean uninstall. Can you provide a list of all files and database tables that this plugin creates and/or modifies?

I would like to remove the plugin until this problem is fixed.

One other fact that may be quite important is that I did run Wp-Optimize in the morning before this issue occurred but I am not sure about the timing. I did run wp_optimize the night before the backup luckily with no issues. I should have backed up right before optimization. Again, I ran wp-optimize again in the morning and then shortly after, the redirection issue occurred.

I hope I have provided enough details for you and would be happy to work with you to determine what may have happened and how to prevent it in the future.

Bill
bill@thewoksoflife.com

**Comment by johngodley** [comment] 2018-01-12 16:11
Can you list the redirect you created (or add a screenshot)?

Did you use Redirection to create an Nginx rewrite file, or did you use it in it's default setting?

**Comment by bwleung** [comment] 2018-01-13 14:52
Defaults settings I believe

There was only one simple redirect:
http://thewoksoflife.com/2018/01/pickled-long-bean-pork-noodle-soup/
to
http://thewoksoflife.com/2018/01/pickled-long-bean-noodle-soup/

**Comment by johngodley** [comment] 2018-01-13 15:04
Ok thanks, I don't think the problem is caused by Redirection then. It's a fairly benign plugin and while you can cause some problems if incorrectly setup, it's rare that it would break a site.

That single redirect will only affect that URL. Redirection does not change any of your server settings or anything that would require you to reconfigure your server, restore your database, or cause 404 errors.

If you disable the plugin then it will entirely stop working, and if Redirection was the cause of the problem then it would have stopped at this point. Any data left in your database will not affect the working of your site at all.

If you want to completely remove the plugin and all database tables then you can press the red delete button on Redirection's settings page, which does a full uninstall.

> I tried to disable the redirection plugin without success

Can you explain this further?

Also, can you tell me what version of WordPress and PHP you are using?

**Comment by johngodley** [comment] 2018-01-19 18:52
Closing for now, please reopen with more information

**Closed by johngodley** 2018-01-19 18:52 UTC
