### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by voltar** [johngodley/redirection#3181] opened 2021-12-29 06:26 UTC
```
Plugin: 5.1.3 4.2
WordPress: 5.8.2 (single)
PHP: 7.4.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
JavaScript: https://neue-sicht-des-lebens.org/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://neue-sicht-des-lebens.org/wp-json/
Query: ?page=redirection.php&sub=options

Error: Es wurde keine Route gefunden, die mit der URL und der Request-Methode identisch ist. (rest_no_route)
Raw: {"code":"rest_no_route","message":"Es wurde keine Route gefunden, die mit der URL und der Request-Methode identisch ist.","data":{"status":404}}
```
I deactivated autoptimize and have just wp-cache installed, but still I am getting this message.

Kind regards

Gianni

**Comment by johngodley** [comment] 2021-12-29 07:09
It is caused by WP cache, or something else on your site. The message is not from Redirection, and according to https://neue-sicht-des-lebens.org/wp-json/ Redirection is not even installed on your site.

**Comment by johngodley** [comment] 2022-01-03 19:34
Closing for now, please reopen with more information.

**Closed by johngodley** 2022-01-03 19:34 UTC
