### ISSUE TITLE
Cant't get Redirection to work for external addresses

### ISSUE THREAD

**Issue by ManfredMeise** [johngodley/redirection#358] opened 2017-09-04 09:25 UTC
To help track problems please follow this template. If you can provide screenshots then that will help.

Hi, I can't get the plugin to work for me. I tried to redirect to external site (at the end of the day to our own)....

### Summary

Trying to redirect to external websites. Got it working once with one external site (not others) and did break it after editing it.

### Actual Behavior

Does not redirect to external URL but stays on the current server and displays the standard error page I created using "404page - deine maßgeschneiderte 404-Fehlerseite" plugin

### Steps to reproduce
Use one entry in the redirections list and create/edit it
from: /test/
to: https://www.heise.de
---> worked fine
from: /test/
to: https://www.t-online.de
---> did not work
from: /test/
to: https://www.heise.de
---> did not work, even after clearing caches (server and browser)

### Environment

current Wordpress, tested with actual versions of firefox and chrome.

**Comment by Steve3100** [comment] 2017-09-04 16:30
I have the same issue. I moved a folder to another domain and wanted to use a 301 redirect but I received a 404 error. So I created the following line in htaccess, which worked.
**Redirect 301 /folder https://domainname/folder**
Since the redirect in htaccess worked, I deleted the line from htaccess and placed the same code in the plugin but the 404 error remained. 
My environment: Apache 2.4, PHP 7.0 and WordPress 4.8.1

**Comment by johngodley** [comment] 2017-09-04 17:26
Redirection doesn't care whether the target is local or external. The problem is most likely something to do with the setup of your site, but without access or more information I can't say what.

You can look in the 404 log to see if the URL is being logged at all. If it isn't then Redirection isn't being called.

**Comment by ManfredMeise** [comment] 2017-09-04 18:20
Hi John, 

internal redirections do work but not external (as indicated). The ones which are not working are logged as 404 by the plugin.

**Comment by johngodley** [comment] 2017-09-04 19:02
Can you list a real source URL and target that I can test with? That should be enough to know whether further access is needed

**Comment by ManfredMeise** [comment] 2017-09-04 19:13
https://www.mmi-consult.de/faq/  should redirect to    https://blog.mmi-consult.de/faq
or
https://www.mmi-consult.de/dummy/    should redirect to https://www.heise.de
or
https://www.mmi-consult.de/lp/    should redirect to https://www.heise.de
or
https://www.mmi-consult.de/lp/    should redirect to  https://messaging.mmi-consult.de/webmail

Only one of them is working.....
Manfred

**Comment by johngodley** [comment] 2017-09-04 19:25
The last one is working fine:

```
curl -v https://www.mmi-consult.de/lp/
*   Trying 46.101.109.6...
* TCP_NODELAY set
* Connected to www.mmi-consult.de (46.101.109.6) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: mmi-consult.de
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET /lp/ HTTP/1.1
> Host: www.mmi-consult.de
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 302 Moved Temporarily
< Server: nginx
< Date: Mon, 04 Sep 2017 19:17:32 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Location: https://www.heise.de/
< Link: <https://www.mmi-consult.de/wp-json/>; rel="https://api.w.org/"
< Link: <https://www.mmi-consult.de/?p=3109>; rel=shortlink
< Strict-Transport-Security: max-age=31536000
< X-Cache: HIT
< X-Cache-Type: NGINX
< X-Cache-Device-Type: pc
```

Note that it is a 302 redirect, I don't know if that is what you configured.

The first two arent working:

```
curl -I -v https://www.mmi-consult.de/faq/
*   Trying 46.101.109.6...
* TCP_NODELAY set
* Connected to www.mmi-consult.de (46.101.109.6) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: mmi-consult.de
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> HEAD /faq/ HTTP/1.1
> Host: www.mmi-consult.de
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: nginx
< Date: Mon, 04 Sep 2017 19:17:57 GMT
< Content-Type: text/html; charset=UTF-8
< Connection: keep-alive
< Vary: Accept-Encoding
< Location: https://blog.mmi-consult.de/faq
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< Link: <https://www.mmi-consult.de/wp-json/>; rel="https://api.w.org/"
```

Note that it includes both a HTTP 404 and a `Location` header (this is what contains the target URL). This does not seem right.

You could try disabling all other plugins and see if that helps. If you disable the appropriate redirect and the `Location` header disappears then you know that it is being added by Redirection.

**Comment by ManfredMeise** [comment] 2017-09-05 06:51
Hi John,

I just deactivated all plugins, which potentially may interfere with yours, cleared caches and tested again. Unchanged results.

I turns out to me, that redirections configured for existing pages reply with 302 (even though I configured a 301) and do work. Non existing targets produce a 404 and reply with the configured target location in the header. Wired........

What else can I do in order to track the problem down?
Manfred

**Comment by johngodley** [comment] 2017-09-07 05:44
I don't think Redirection is actually doing anything here, and something else is redirecting/not redirecting. Is it possible to get a login to the site? That would speed things up a lot. Otherwise I can only suggest adding bits of debug code to the plugin to try and dig deeper.

**Comment by ManfredMeise** [comment] 2017-09-07 06:43
Hi John, you are welcome to receive a login in order to speed things up an reduce your effort. What do you need (Wordpress and/or OS)? How would I communicate login data in a secure manor to you? Please send a private message to "Manfred.Meise@mmi-consult.de". Thx in advance

**Comment by Steve3100** [comment] 2017-09-08 00:50
I just tried it again and everything works. I don't know if this made a difference but I used CCleaner to clear the chrome and Firefox browser cache. I tried it with a couple of different links without any failures.

**Comment by ManfredMeise** [comment] 2017-09-08 11:55
I did the same with different result. In order to track down the issue I had created several hidden pages, before you did you testing. It turn out to me, that the result is different if a page with the Source url exists or not. 

I still agree with you, that there might something else going wrong besides your plug-in, but also think, that the only way to track it right now is to have a look at the site. 

Tell me, if you are still prepared to have a look (either on your own or together with myself) on the live site?  Where are you located (timezone wise) to perhaps have an interactive session?

**Comment by ManfredMeise** [comment] 2017-09-12 13:41
Hi @johngodley ,

I recognize, that there are a lot of requests and issue posted these days. But are you still available to have a look at my general issue? Perhaps this solves also other's issue.

We need to find out, if the misbehaviour is a result of Redirection plugin or interference with another configuration or plugin. Gett hundreds of 404s due to many external backlinks.

Looking forward to your response,
Manfred

**Comment by ManfredMeise** [comment] 2017-09-13 10:16
I am stil struggeling with Redirection. After deleting all other plugins and switching back to a WP theme, Redirections still failed. Browsing the web, I found some hint to reconfigure WP Permalinks. This got some redirections to work in "Simple" configuration. Going back to may perfered permalink setting "Post Name" broke these previously working redirections again.

@johngodley This leads me to the assumption, that Redirection is doing wrong. Please comment!

**Comment by johngodley** [comment] 2017-09-15 14:39
@ManfredMeise I don't understand what you mean about WP permalinks and redirections. Redirection may very well be doing something wrong, but I'm not convinced in this instance it is and I suspect that it's something specific to your site. I have been/am travelling so am unable to investigate further right now, but if you do still want to investigate then my contact details are found on the website link from my profile (click my avatar)

**Comment by ManfredMeise** [comment] 2017-09-20 17:19
Hi John,

we got the Plugin to work! Thanks to the support team of our hosting provider Raidboxes.de !

You will find the change request details: 

https://wordpress.org/support/topic/bugfix-bug-report-5-minutes-work-only/

Regards,
Manfred

**Comment by johngodley** [comment] 2017-09-21 10:57
Thanks Manfred, that's perfect. I've reopened this ticket and copied the solution here:

> 
> BUGIFX:
> In file modules/wordpress.php replace the following line:
> 
> elseif ( $status === 301 && php_sapi_name() === ‘cgi-fcgi’ ) {
> 
> with
> 
> elseif ( $status == 301 && in_array(php_sapi_name(), array(‘cgi-fcgi’, ‘fpm-fcgi’))) {
> 
> Explanation:
> 1. You are comparing with ===. So $status has to be an integer. If $status is the string “301” this expression evaluates to false and plugin does not work. You CAN safely compare with == and let PHP use its automatic type conversion. This will NOT break anything else!
> 
> 2. Our server setup uses ‘fpm-fcgi’. So I’ve extended the check with this.

**Comment by johngodley** [comment] 2017-09-30 11:07
After looking at this some more I don't think it fixes anything, but just hides the underlying problem. The check for fpm-fcgi isn't needed and adding it has the potential to affect a lot of people. My site uses this and doesn't need the modification.

The thing that makes it work is the fact that this branch of code ends in `exit`, which is preventing the redirect being ignored and turned into a 404 (as demonstrated above).

The `exit` shouldn't be there, as per the WordPress documentation. The question still remains as to what is causing the redirect to be ignored.

I'd still be interested in gaining access to the server to investigate this further. I won't be including the above fix as-is, but it does confirm the general area.

**Comment by ManfredMeise** [comment] 2017-10-02 09:22
Hi John,

you are welcome to have a look at our installation/configuration to figure out, what is going wrong. With the modifications mentioned, I got most redierctions to work (but not all). So I can provide good and bad cases.

Tell me when and how you would like to get access?

Manfred

**Comment by marcelgleis** [comment] 2017-10-18 09:51
Hey John,

I am from raidboxes.de and we are the hosting company of Manfred.

We have *a lot* of customers that can't use your plugin because of this error. I understand that my suggested solution might be a workaround and does not fix the real cause of the errors. 

Nevertheless can't you implement our workaround to ensure that thousands of our customers can use your plugin?

Best regards,
Marcel

**Comment by johngodley** [comment] 2017-10-20 11:10
Hi @marcelgleis I've contacted Manfred regarding access. I'm planning on making another release soon, and hope to get a fix in.

I'd rather not include the above workaround as it could negatively affect a lot more people than it helps. I'm fairly sure the solution will be reasonably easy to track down. If not then I'll try and put something in place where the workaround and the current code can work without negatively affecting anyone.

**Comment by johngodley** [comment] 2017-10-21 15:26
@marcelgleis I signed up for a raidbox (thanks for the free signup period!) and was able to reproduce the problem.

There is a plugin `rb-plugins/nginx-compatibility/nginx-compatibility.php` that has the following code:

```php
if ($nginx_compatibility->haveNginx() && !function_exists('wp_redirect')) {

    function wp_redirect($location, $status = 302) {
        $location = apply_filters('wp_redirect', $location, $status);

        if (empty($location)) {
            return false;
        }

        $status = apply_filters('wp_redirect_status', $status, $location);
        if ($status < 300 || $status > 399) {
            $status = 302;
        }

        $location = wp_sanitize_redirect($location);
        header('Location: ' . $location, true, $status);
    }

}
```

This is incorrect according to the WordPress definition for `wp_redirect`, and it should return either true (the redirect was valid) or false (the redirect was invalid).

https://developer.wordpress.org/reference/functions/wp_redirect/

Your function is not returning anything. Redirection is expecting a return value, and so it doesn't think that the redirect was valid and so doesn't call `exit` (as described on the WordPress page above). This means that the page request continues, and a 404 is returned instead.

I don't have write permission to anything other than my own plugins on raidbox so I'm unable to confirm this directly. However, I have downloaded the same plugins and used them locally. I experienced the same problem and changing the  `nginx-compatibility` function to return `true` fixes the issue:

```php
function wp_redirect($location, $status = 302) {
	$location = apply_filters('wp_redirect', $location, $status);

	if (empty($location)) {
		return false;
	}

	$status = apply_filters('wp_redirect_status', $status, $location);
	if ($status < 300 || $status > 399) {
		$status = 302;
	}

	$location = wp_sanitize_redirect($location);

	return true;
}
```

Note the `return true;` on the last line, which makes it conform to the WordPress documentation.

**Comment by johngodley** [comment] 2017-10-28 11:17
Closing for now, please reopen if there's anything else I can do here.

**Closed by johngodley** 2017-10-28 11:17 UTC
