### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Landshark67** [johngodley/redirection#2492] opened 2020-10-19 14:34 UTC
Checking the logs, when any url is clicked or entered (such as oddsideales.com/wp-json) the first response is 404, then all of a sudden all the info appears. The log shows file or folder not found and then the next line that pops up shows a connection. This is happening on every single url on my site. I've attached a screenshot that illustrates what is going on.
<img width="1299" alt="Screen Shot 2020-10-16 at 2 30 51 PM" src="https://user-images.githubusercontent.com/39766367/96465162-a6067480-11f6-11eb-9cb4-8bbd1b6fa0f1.png">

```
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.4.11
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36
JavaScript: https://oddsideales.com/wp-content/plugins/redirection/redirection.js
REST API: https://oddsideales.com/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment] 2020-10-19 15:05
Ok. These are separate issues. The first is unrelated to Redirection and you will need to fix your server configuration (or have you host look at).

The second is that your site blocking access to the REST API. Typically this is caused by a security plugin. I note you are on OVH and I remember in the past this often caused issues. You could also try changing the REST API to see if it helps.

**Comment by johngodley** [comment] 2020-10-25 06:44
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-10-25 06:44 UTC
