### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by israelmeirwi** [johngodley/redirection#3375] opened 2022-08-01 10:57 UTC
```
Plugin: 5.3.1 4.2
WordPress: 6.0.1 (single)
PHP: 7.4.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
JavaScript: https://thekotel.org/wp-content/plugins/redirection/redirection.js?ver=5.3.1-861e7f0132a71a1fdb94b8db22f36d35
REST API: https://thekotel.org/wp-json/
Query: ?page=redirection.php
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    at $l (https://thekotel.org/wp-content/plugins/redirection/redirection.js?ver=5.3.1-861e7f0132a71a1fdb94b8db22f36d35:2:375218)
    at p
    at div
    at Hl (https://thekotel.org/wp-content/plugins/redirection/redirection.js?ver=5.3.1-861e7f0132a71a1fdb94b8db22f36d35:2:375344)
    at op (https://thekotel.org/wp-content/plugins/redirection/redirection.js?ver=5.3.1-861e7f0132a71a1fdb94b8db22f36d35:2:461418)
    at div
    at i (https://thekotel.org/wp-content/plugins/redirection/redirection.js?ver=5.3.1-861e7f0132a71a1fdb94b8db22f36d35:2:401304)
    at https://thekotel.org/wp-content/plugins/redirection/redirection.js?ver=5.3.1-861e7f0132a71a1fdb94b8db22f36d35:2:683157
    at Su (https://thekotel.org/wp-content/plugins/redirection/redirection.js?ver=5.3.1-861e7f0132a71a1fdb94b8db22f36d35:2:206942)
    at M (https://thekotel.org/wp-content/plugins/redirection/redirection.js?ver=5.3.1-861e7f0132a71a1fdb94b8db22f36d35:2:280637)
    at iw
```

**Comment by johngodley** [comment] 2022-08-01 13:00
This is caused by another plugin or a browser extension.

**Comment by johngodley** [comment] 2022-09-06 12:54
Closing for now please reopen with more details.

**Closed as completed by johngodley** 2022-09-06 12:54 UTC
