### ISSUE TITLE
Problem starting Redirection 5.0.1

### ISSUE THREAD

**Issue by tokyographer** [johngodley/redirection#2760] opened 2021-02-10 11:50 UTC
Plugin: 5.0.1
WordPress: 5.6.1 (single)
PHP: 7.4.15
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
JavaScript: https://innermastery.es/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://innermastery.es/wp-json/

**Comment by johngodley** [comment] 2021-02-10 12:12
This is likely caused by another plugin. Your browser's developer console should show any issues.

**Comment by johngodley** [comment] 2021-02-10 12:13
Also, your file does not load:

https://innermastery.es/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3

**Comment by johngodley** [comment] 2021-03-27 13:00
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-27 13:00 UTC
