### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by pabloaugusto** [johngodley/redirection#1882] opened 2019-07-17 01:52 UTC
```
Plugin: 4.3.1
WordPress: 5.2.2 (single)
PHP: 5.6.36
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
JavaScript: https://pabloaugusto.com/wp-content/plugins/redirection/redirection.js
REST API: https://pabloaugusto.com/wp-json/

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Action: redirection/v1/group/ GET
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```

**Comment by johngodley** [comment] 2019-07-21 08:23
As the plugin should explain this is likely caused by a security plugin.

**Comment by johngodley** [comment] 2019-07-25 20:23
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-07-25 20:23 UTC
Labels: need-feedback
