### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by brahim0009** [johngodley/redirection#2778] opened 2021-02-24 10:19 UTC
```
Plugin: 5.0.1
WordPress: 5.6.2 (single)
PHP: 7.4.12
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
JavaScript: https://ireez.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://ireez.com/wp-json/
Query: ?page=redirection.php

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

**Comment by johngodley** [comment] 2021-03-27 12:55
Your server is returning a 503 error, probably caused by a security plugin or misconfiguration.

**Comment by johngodley** [comment] 2021-03-31 19:12
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-31 19:12 UTC
Labels: need-feedback
