### ISSUE TITLE
Problem starting Redirection 4.8

### ISSUE THREAD

**Issue by poovarasu208** [johngodley/redirection#2462] opened 2020-09-22 10:09 UTC
```
Uncaught ReferenceError: commonL10n is not defined https://dsv4fxpzi0skc.cloudfront.net/wp-admin/js/common.min.js?ver=5.5.1 1
```

Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.3.7
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
JavaScript: https://dsv4fxpzi0skc.cloudfront.net/wp-content/plugins/redirection/redirection.js
REST API: https://dsv4fxpzi0skc.cloudfront.net/wp-json/

**Comment by johngodley** [comment] 2020-09-22 11:01
I believe that error is caused by another plugin.

**Comment by johngodley** [comment] 2020-10-03 13:56
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-10-03 13:56 UTC
