### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by lpvcorp** [johngodley/redirection#2356] opened 2020-06-28 18:27 UTC
```
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.3.19
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
JavaScript: https://www.subscribe.lpvcorp.com/global/wp-content/plugins/redirection/redirection.js
REST API: https://www.subscribe.lpvcorp.com/wp-json/

Error: Unexpected end of JSON input (SyntaxError)
Raw: -no data-
```

**Comment by johngodley** [comment] 2020-06-28 18:28
Your site doesn't work. How are you expecting the plugin to get data?

**Comment by lpvcorp** [comment] 2020-06-28 23:33
Our website is working. We are having issues with this one Plugin.

**Comment by johngodley** [comment] 2020-06-29 04:43
https://www.subscribe.lpvcorp.com/ does not work, nor does https://www.subscribe.lpvcorp.com/wp-json/

**Comment by lpvcorp** [comment] 2020-06-29 07:33
It works perfectly fine for us.

**Comment by johngodley** [comment] 2020-06-29 07:44
It returns a 500 error for me, and it would explain the error you posted above, which shows that no data is being returned by your server. This is almost certainly something caused by your server or setup

**Comment by johngodley** [comment] 2020-07-18 15:24
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-07-18 15:24 UTC
Labels: need-feedback
