### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by fhtwl** [johngodley/redirection#1748] opened 2019-05-10 11:30 UTC
```
Plugin: 4.2.3
WordPress: 4.8.9 (single)
PHP: 5.6.31
Browser: Mozilla/5.0 (Linux; U; Android 8.0.0; zh-cn; MI 5s Build/OPR1.170623.032) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.7.3
JavaScript: http://47.96.7.137/wp-content/plugins/redirection/redirection.js
REST API: http://47.96.7.137/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Action: redirection/v1/group/ GET
Code: 503 Service Unavailable
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>

```

**Comment by johngodley** [comment] 2019-05-11 14:10
Your WordPress REST API is returning a 503 error. You will need to investigate why this is happening. It may be caused by a security plugin.

**Comment by johngodley** [comment] 2019-05-18 12:15
Closing for now, please reopen with more details.

**Closed by johngodley** 2019-05-18 12:15 UTC
Labels: need-feedback
