### ISSUE TITLE
Automatic Redirects

### ISSUE THREAD

**Issue by NorthwoodsChurch** [johngodley/redirection#142] opened 2016-10-25 20:43 UTC
Hello,

On my website http://northwoods.church, we use The Events Calendar Pro by Modern Tribe for our calendar of events. We also use your Redirection plugin. I am seeing that a lot of redirects are being created for calendar events automatically. I would like to understand why this is happening and if there is a way for it to stop. All of these redirects are in the group Modified Posts. Could you please explain why these redirects are being created and how I might stop them?

Thanks,
Hope

**Comment by johngodley** [comment] 2017-05-29 14:53
I don't have Events Calendar Pro to test this out. What kind of redirects are being created?

**Comment by NorthwoodsChurch** [comment] 2017-05-30 14:14
301

**Comment by johngodley** [comment] 2017-08-08 05:13
Do you still have this problem? I am unable to reproduce the problem with the latest version of Redirection, and it is possible that it has been fixed. I will close this for now, but if you do have the problem still the reopen and please provide detailed steps for how to use Events Calendar to force a redirection to be created.

**Closed by johngodley** 2017-08-08 05:13 UTC
Labels: question
