### ISSUE TITLE
Redirection Error - no idea how to fix.

### ISSUE THREAD

**Issue by mmarvel1** [johngodley/redirection#1809] opened 2019-06-11 01:47 UTC
```
Plugin: 4.3.1
WordPress: 5.2.1 (single)
PHP: 7.2.15
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
JavaScript: https://designedbliss.com/wp-content/plugins/redirection/redirection.js
REST API: https://designedbliss.com/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /wp-json/redirection/v1/plugin/ was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

```

**Comment by johngodley** [comment] 2019-06-14 05:44
Please follow the plugin information regarding this problem. It should suggest a security plugin is the cause.

**Comment by johngodley** [comment] 2019-06-14 05:55
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-06-14 05:55 UTC
