### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by amaherjr** [johngodley/redirection#2503] opened 2020-10-25 07:54 UTC
```

Action: https://mercatoday.com/wp-json/redirection/v1/plugin/database/ POST
Code: 503 Service Unavailable

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<p>Additionally, a 503 Service Unavailable
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

```

**Comment by johngodley** [comment] 2020-10-25 07:56
As the message indicates, your site is returning a `503 Service Unavailable` when accessing the REST API. This may be caused by a security plugin.

**Comment by johngodley** [comment] 2020-11-08 17:37
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-08 17:37 UTC
Labels: need-feedback
