### ISSUE TITLE
Problem starting Redirection 5.3.9

### ISSUE THREAD

**Issue by vesko2103** [johngodley/redirection#3553] opened 2023-02-16 11:55 UTC
Plugin: 5.3.9 4.2
WordPress: 6.1.1 (single)
PHP: 7.4.29
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
JavaScript: https://www.esbabes.com/wp-content/plugins/redirection/redirection.js?ver=5.3.9-d9e6fbf82d86a7f9b256e669c214cb3a
REST API: https://www.esbabes.com/wp-json/

**Comment by johngodley** [comment] 2023-03-04 14:02
This is likely caused by another plugin. Please follow the onscreen instructions and look at your browser's developer console.

**Comment by johngodley** [comment] 2023-04-15 13:36
Closing for now, please reopen with more details.

**Closed as completed by johngodley** 2023-04-15 13:36 UTC
Labels: need-feedback
