### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by pirtpal-matharu** [johngodley/redirection#2585] opened 2020-11-19 17:14 UTC
```
Plugin: 4.8
WordPress: 5.5.3 (single)
PHP: 7.4.10
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
JavaScript: https://allthingsmarketplace.com/wp-content/plugins/redirection/redirection.js
REST API: https://allthingsmarketplace.com/wp-json/

Error: RESTful API is disabled (rest_access_disabled)
Action: redirection/v1/group/ GET
Code: 403 Forbidden
Raw: {"code":"rest_access_disabled","message":"RESTful API is disabled","data":{"status":403}}
```

**Comment by johngodley** [comment] 2020-11-19 17:15
The problem is shown above:

RESTful API is disabled (rest_access_disabled)

**Comment by johngodley** [comment] 2020-11-22 08:02
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-22 08:02 UTC
