### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by blueprintmrk** [johngodley/redirection#2346] opened 2020-06-16 18:23 UTC
```
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.2.31-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
JavaScript: https://tomzickell.com/wp-content/plugins/redirection/redirection.js
REST API: https://tomzickell.com/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment] 2020-06-29 05:32
Your REST API is being blocked. This is probably caused by a security plugin.

**Comment by johngodley** [comment] 2020-07-18 15:23
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-07-18 15:23 UTC
Labels: need-feedback
