### ISSUE TITLE
Problem starting Redirection 5.2.3

### ISSUE THREAD

**Issue by julincicel93** [johngodley/redirection#3307] opened 2022-05-30 07:54 UTC
```
Uncaught SyntaxError: Invalid or unexpected token https://moshammer-automotive.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be 2
```

Plugin: 5.2.3 4.2
WordPress: 6.0 (single)
PHP: 7.4.29
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
JavaScript: https://moshammer-automotive.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://moshammer-automotive.com/wp-json/

**Comment by johngodley** [comment] 2022-05-30 08:43
This is almost certainly caused by another plugin on your site.

**Comment by johngodley** [comment] 2022-06-04 06:07
Closing for now please reopen with more details.

**Closed by johngodley** 2022-06-04 06:07 UTC
