### ISSUE TITLE
io

### ISSUE THREAD

**Issue by DouglasMediaGroup** [johngodley/redirection#1499] opened 2019-02-22 23:13 UTC
Plugin: 3.7
WordPress: 5.0.3 (single)
PHP: 7.1.26-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15
JavaScript: https://highlandpharms.com/wp-content/plugins/redirection/redirection.js
REST API: https://highlandpharms.com/wp-json/
Buster: 3.7 === 3.7

TypeError: Object is not a function (near '...r...')

    in t
    in div
    in t
    in Connect(t)
    in div
    in t
    in Connect(t)
    in t
    in Hf
    in t

**Comment by johngodley** [comment] 2019-02-23 10:18
Please open your browser's developer console and see if any other errors are shown. This is likely caused by another plugin.

**Comment by johngodley** [comment] 2019-03-02 11:29
Closing for now, please reopen with more details

**Closed by johngodley** 2019-03-02 11:29 UTC
Labels: need-feedback
