### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by cosmocanuck** [johngodley/redirection#3099] opened 2021-10-18 17:35 UTC
Hi! I've happily used Redirection on many sites and it always works great. So I'm hopeful I can get to the bottom of the WordPress REST API issues that are apparently breaking things on my latest install, at heroshockey.com. To summarize what's happened:

1.  I set up the plugin, and was warned about an issue the last of three API-related checks  - but it also said this was not a critical issue and things should still work.
2. I imported my CSV of redirects, and all seemed to work fine.
3. Soon after, all was not fine - when I go to Tools --> Redirection, the redirects list never loads, and on the Support tab, the grey box next to REST API that says "Testing: X%" crawls slowly to about 83% then just sits there. Plugin status just shows a pulsating grey bar.
4. Redirects are still happening, and working correctly, except for one of them which is not going to the right place. But I can't load the list of redirects to edit it.
4. This info came up at one point: "JSON Parse error: Unrecognized token '<' (SyntaxError). This could be a security plugin, or your server is out of memory or has an external error. Please check your server error log."
5. I'm not running security software... and my hosting contact has assured me there's plenty of server memory....

I'm stumped and hope you can assist. Thanks!
Adam

```
Plugin: 5.1.3 4.2
WordPress: 5.8.1 (single)
PHP: 7.4.24
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
JavaScript: https://heroshockey.com/wp2021/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://heroshockey.com/wp-json/
Query: ?page=redirection.php

Error: undefined
```

**Comment by cosmocanuck** [comment] 2021-10-19 22:22
Hmm. CPU Usage was 100% in cPanel. I removed Redirection and it dropped down to under 40%. Will see what happens after I reinstall it.

**Comment by johngodley** [comment] 2022-01-09 16:49
Unless you have a lot of regular expression redirects I don't think the CPU increase is caused by Redirection - there's very little going on. If you have more details then please post them, but for now I will close this issue.

**Closed by johngodley** 2022-01-09 16:49 UTC
