### ISSUE TITLE
Problem starting Redirection 4.9

### ISSUE THREAD

**Issue by GendalfW** [johngodley/redirection#2519] opened 2020-10-27 10:47 UTC
```
SyntaxError: illegal character http://seo-gen.org.ua/wp-content/plugins/redirection/redirection.js?ver=4.9-c383de96c0b7e38459253ead4f6e9b10 2,ReferenceError: QTags is not defined http://seo-gen.org.ua/wp-admin/tools.php?page=redirection.php 412
```

Plugin: 4.9
WordPress: 5.5.1 (single)
PHP: 7.2.0
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
JavaScript: http://seo-gen.org.ua/wp-content/plugins/redirection/redirection.js?ver=4.9-c383de96c0b7e38459253ead4f6e9b10
REST API: http://seo-gen.org.ua/wp-json/

**Comment by johngodley** [comment] 2020-10-27 12:07
The file http://seo-gen.org.ua/wp-content/plugins/redirection/redirection.js?ver=4.9-c383de96c0b7e38459253ead4f6e9b10 appears to be corrupt, which may have happened during installation. You will need to re-install it.

The QTags error is caused by some other plugin on your site.

**Comment by johngodley** [comment] 2020-11-08 17:37
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-08 17:37 UTC
