### ISSUE TITLE
Redirection is no longer ignoring url parameters

### ISSUE THREAD

**Issue by justlevine** [johngodley/redirection#1275] opened 2018-11-13 22:16 UTC
Edited for clarity.

### Summary

Instead of unmatched url parameters not redirecting, these links are redirecting to a random pages on my site.

Thought this was a specific issue with facebooks `fbclid` (before I found #1248 ), but the quirk is for all url parameters, and redirects instead of creating a 404.

E.g. https://mysite.test/oldurl -> https://mysite.test/newurl
https://mysite.test/oldurl?anything -> a random post.

I'm __pretty sure__ this is not the old behavior. (As even in the aformentioned #1248 users are getting a 404, not a redirect to somewhere random)
### Steps to reproduce
Live example: 
[https://thegsc.co.il/thanksgiving](https://thegsc.co.il/thanksgiving) -> [https://thegsc.co.il/event/the-givat-shmuel-thanksgiving-dinner](https://thegsc.co.il/event/the-givat-shmuel-thanksgiving-dinner)
**but**
[https://thegsc.co.il/thanksgiving?a](https://thegsc.co.il/thanksgiving?a) -> [https://thegsc.co.il/shop/thanksgiving-dinner-buy-something-for-me/?a](https://thegsc.co.il/shop/thanksgiving-dinner-buy-something-for-me/?a)

**Note:** the parameter gets appended to the redirected page.

###Workaround
Enable regex and add `\?.*` to the end of the source slug.
### Environment

Chrome and Firefox latest on both Android and Windows . Wordpress 4.9.8, Redirection 3.6.2. both on localhost (wamp), and siteground live (apache), PHP 7.2

**Comment by johngodley** [comment] 2018-11-14 08:29
That is expected behaviour. You need to include URL parameters in your redirect

**Comment by justlevine** [comment] 2018-11-14 08:54
@Johngodley - correct me if I'm wrong but the expected behavior is that if you don't include site params, the page will go to to a 404 (at that link), not create a random 301 redirect to somewhere else.


No?

**Comment by johngodley** [comment] 2018-11-14 09:03
I don't know what you mean by random redirect, but a match has always needed to include any query parameters. If you expect a URL to have them then you'll need to account for it in the source URL otherwise it won't be redirected.

As mentioned in #1248, a future enhancement will add the option to ignore query params, making this behaviour automatic.

**Comment by justlevine** [comment] 2018-11-14 09:19
To my understanding, prior behavior was as follows:

Redirect for: `/oldurl` -> `https://site.com/newurl`

Visiting https://site.com/`oldurl` would take the user to `\newurl`.

Visiting https://site.com/`oldurl?parameter` would **not redirect** and take you to `oldurl`.

__Now__, visiting `/oldurl?parameter` is taking me to `/entirely-different-and-random-url`, via a 301 redirect created by the plugin.

**Comment by justlevine** [comment] 2018-11-14 09:30
No that's what I'm saying: It's a random redirect, when there's no regex involved.
The redirect will even change to `/different-random-page` if I set the `/current-random-redirect` post to draft.

**Comment by justlevine** [comment] 2018-11-14 09:36
Live example (because it's a live site, the example in my original ticket was fixed with the regex I described).

Redirect set for: `shabbaton`:

https://thegsc.co.il/shabbaton -> https://thegsc.co.il/event/welcome-back-shabbaton-2018/ ✔️

https://thegsc.co.il/shabbaton?add-random-param -> https://thegsc.co.il/event/shabbaton-after-party-bonfire/?j ❌

**Comment by johngodley** [comment] 2018-11-14 09:39
https://thegsc.co.il/shabbaton is being redirected with Redirection:

https://redirect.li/http/?url=https%3A%2F%2Fthegsc.co.il%2Fshabbaton

https://thegsc.co.il/shabbaton?add-random-param is not being redirected with Redirection:

https://redirect.li/http/?url=https%3A%2F%2Fthegsc.co.il%2Fshabbaton%3Fadd-random-param

**Comment by johngodley** [comment] 2018-11-14 10:36
Ok understood. I'm not able to reproduce this behaviour myself. Can you paste a screenshot of a redirect being edited on your localhost?

**Comment by johngodley** [comment] 2018-11-20 08:30
@mheiduk your source URL will need to take any parameters into account. This doesn't sound related to the original problem here.

**Comment by mheiduk** [comment] 2018-11-20 09:00
@johngodley Thanks for the fast answer! It is not possible to take this parameter into account, because Facebook generates a random hash which gets automatically attached.

For example domain.com/shorturl?fbclid=IwAR3F6TUCCcCcuk-rdyPp_SKQuPJz8ifqc9x6gemsEFLDFp_GrUEM_EIsS2c

**Comment by johngodley** [comment] 2018-11-20 09:10
Yep, as you mentioned, the solution is to use regular expressions: https://redirection.me/support/redirect-regular-expressions/

**Comment by Log1x** [comment] 2018-11-21 06:59
Any possibility of having an option implemented to allow the ability to enable automatically passing parameters on all Redirect URLs? There are no scenarios on our end that we wouldn't want parameters (such as `utm_x` or `fbclid`) appended to the redirected URL.

It'd be much appreciated.

**Comment by johngodley** [comment] 2018-11-21 07:40
See #410

**Comment by mvl22** [comment] 2018-12-02 20:44
A hotfix for the Wordpress `fbclid` issue is to edit `wordpress.php` and in `public function init()`, after:

```
$url = apply_filters( 'redirection_url_source', Redirection_Request::get_request_url() );
```

add:

```
// Remove fbclid; see: https://github.com/johngodley/redirection/issues/1275
$url = preg_replace ('/\?fbclid=[a-zA-Z0-9]+&/', '?', $url);
$url = preg_replace ('/\?fbclid=[a-zA-Z0-9]+$/', '', $url);
```

**Comment by Log1x** [comment] 2018-12-02 21:49
In your example, you could just filter `redirection_url_source`. No need to edit plugin code that will get overwritten when updated.

```
add_filter('redirection_url_source', function ($url) {
    return preg_replace ('/\?fbclid=[a-zA-Z0-9]+&/', '?', $url);
});
```

**Comment by johngodley** [comment] 2018-12-09 14:43
I'm closing this as it's possible to use regular expressions, and it will be made easier with #410

**Closed by johngodley** 2018-12-09 14:43 UTC

**Comment by Mte90** [comment] 2018-12-17 09:47
For me the filter wasn't working but I founda solution by htaccess https://stackoverflow.com/a/52877205/1902215
In that way less stuff to elaborate to php :-)
