### ISSUE TITLE
After update, regex redirections only work for admin

### ISSUE THREAD

**Issue by nerdyandawesome** [johngodley/redirection#2185] opened 2020-02-16 21:31 UTC
After the latest update 4.7, now any redirects using regex to match query parameters only works for admin. Once I logged out, it doesn't work anymore.

for example, .*utm_campaign=abc

**Comment by johngodley** [comment] 2020-02-16 22:07
I'm not able to reproduce any problem with regular expressions. Can you give an example URL?

**Comment by johngodley** [comment] 2020-02-23 15:12
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-02-23 15:12 UTC
