### ISSUE TITLE
301 Loop on top page on domain

### ISSUE THREAD

**Issue by AustZ** [johngodley/redirection#3552] opened 2023-02-16 04:26 UTC
### Summary

Intermittent front-page outages due to 301 redirect loops.

### Actual Behavior

We have a website at https://robokaru.jp/ - over the past few days we've had intermittent outages with 301 loops at the top page of the domain.

The 301 loops redirect https://robokaru.jp to https://robokaru.jp - thus causing an infinite loop. They all resolve themselves at the around one hour mark (is this possibly a sign of a cron job issue?)

<img width="484" alt="スクリーンショット 2023-02-16 13 10 09" src="https://user-images.githubusercontent.com/19422259/219267954-2eecc9a8-df66-452e-878f-959dbb7a11c4.png">

Checking with a tool such as https://www.redirect-checker.org/index.php states that it is the redirection plugin which is causing this redirect. However no such rule exists in the current redirection items. (At most there is one which leads from /index.html to /)

Current settings are to force https:// and to remove www. from the domains - but the latter isn't working either so this may be linked.

### Steps to reproduce

Not reproducible on demand. Intermittent outages of around 1 hour. Web page is accessible 90% of the time.

### Environment

Chrome 109.0.5414.119. However the 301 loop has been observed in other environments.
Wordpress 6.1.1
Redirection 5.3.9
PHP 7.4

**Comment by johngodley** [comment] 2023-02-16 06:36
You should look through your redirects for any that might cause a loop. Regular expressions are often responsible. Your site is cached and that is generally the cause of sporadic changes.

**Comment by johngodley** [comment] 2023-03-04 13:57
Closing for now please reopen with more details.

**Closed as completed by johngodley** 2023-03-04 13:57 UTC
