### ISSUE TITLE
Check Redirect link does nothing when clicked

### ISSUE THREAD

**Issue by bizmate** [johngodley/redirection#1977] opened 2019-09-24 08:42 UTC
### Summary

Clicking the "Check Redirect" link for redirects does nothing. 

### Actual Behavior & Steps to reproduce

Clicking on the "Check Redicrect" link does absolutely nothing. 
I see no popup request, nor any other action happening on the interface or javascript console log for that matter.

#### Browser 

Google Chrome | 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux
JavaScript | V8 7.7.299.11
Flash | 32.0.0.255 /home/user/.config/google-chrome/PepperFlash/32.0.0.255/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

#### Wordpress/Plugin
Wordpress 5.2.3
Redirection Version 4.4

**Comment by johngodley** [comment] 2019-09-26 18:41
Are you running any browser extensions? I'm not able to reproduce a problem with the check redirect feature, and you are the only reporter of the problem.

**Comment by bizmate** [comment] 2019-09-26 19:35
I do run plenty of extensions but I still see the problem even in incognito (chrome) with all extension disabled. I see the same experience on Firefox, Opera and Brave, ie no result at all and no traces in console or network traffic. The extension works as it has recorded the redirect for the several links i have ported from another CMS. I can provide further information if needed but at this point I honestly do not know what else to look for.

**Comment by johngodley** [comment] 2019-09-26 21:10
Would it be possible to see this in action myself? If that's ok I can be contact at https://redirection.me/contact/

I suspect there may be other code running on the page that is somehow blocking the functionality.

**Comment by johngodley** [comment] 2019-10-05 12:06
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-10-05 12:06 UTC
Labels: need-feedback
