### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by letuanthhcm** [johngodley/redirection#2207] opened 2020-03-10 07:19 UTC
```
Plugin: 4.6.2
WordPress: 5.3.2 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/85.0.134 Chrome/79.0.3945.134 Safari/537.36
JavaScript: https://sieuthitrathaomoc.com/wp-content/plugins/redirection/redirection.js
REST API: https://sieuthitrathaomoc.com/index.php?rest_route=/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Action: redirection/v1/group/&per_page=200 GET
Code: 500 Internal Server Error
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@sieuthitrathaomoc.com to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>

```

**Comment by johngodley** [comment] 2020-03-10 08:24
Are you running a security plugin?

**Comment by letuanthhcm** [comment] 2020-03-10 09:42
No, I don't

**Comment by johngodley** [comment] 2020-03-10 09:48
Ok, as you can see above something on your site is blocking the WordPress REST API and returning the error. This is usually caused by a security plugin, but could also be settings on your server. It will be worth trying the WordPress site health and see if that has issues. You could also try changing the REST API option in Redirection.

**Comment by johngodley** [comment] 2020-03-21 15:33
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-03-21 15:33 UTC
