### ISSUE TITLE
Support doc says a delete all button exists for 404s, but only clear all (and that's not working)

### ISSUE THREAD

**Issue by tigredanky** [johngodley/redirection#2986] opened 2021-07-14 16:41 UTC
https://www.loom.com/share/4d7d0fd999044b32b57940e42c64b3a8

Support doc here says 404 page has a delete all button, but there is none (just the select all, clear all option)
https://redirection.me/support/tracking-404-errors/

When I do select all logs and try to clear them, they don't clear. Thanks!

**Comment by johngodley** [comment] 2021-07-17 06:12
I have updated the docs.

I am unable to reproduce a problem with the select all option. Can you delete individual entries?

**Comment by johngodley** [comment] 2021-07-24 05:47
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-07-24 05:47 UTC
