### ISSUE TITLE
auto-create two redirect records

### ISSUE THREAD

**Issue by kage690** [johngodley/redirection#3587] opened 2023-03-24 09:37 UTC
Hi, when i changed url, system auto-create two redirect records, how can i fix it?

Plugin Version 5.3.9
WordPress Version 6.1.1

![image](https://user-images.githubusercontent.com/48980365/227480903-0c21c46d-7cd0-45a4-97fb-aa72759e7e4f.png)
![image](https://user-images.githubusercontent.com/48980365/227481191-e5cb7d9c-8118-4576-8746-70adc4d8f0e6.png)
![image](https://user-images.githubusercontent.com/48980365/227481477-732d9919-880d-476b-b649-89ae108d6ea5.png)

**Comment by kage690** [comment] 2023-03-24 09:45
Plugin Version 5.3.9

**Comment by robertstaddon** [comment] 2023-03-28 16:56
I experienced the same issue! It's caused by a bug on the "Options" page which automatically inserts "/" into the "Create an associated redirect" field in your screenshot. If you clear this value and re-save the options, the plugin automatically puts it right back. This bug can be fixed (allowing you to save options with no value in that field and thus stop the second redirect from being created) by making a small edit in your plugin's redirection-settings.php file: https://github.com/johngodley/redirection/pull/3585  

Hopefully, the developer will be able to get this Pull Request merged into his next release.

**Comment by kage690** [comment] 2023-03-29 06:37
> I experienced the same issue! It's caused by a bug on the "Options" page which automatically inserts "/" into the "Create an associated redirect" field in your screenshot. If you clear this value and re-save the options, the plugin automatically puts it right back. This bug can be fixed (allowing you to save options with no value in that field and thus stop the second redirect from being created) by making a small edit in your plugin's redirection-settings.php file: #3585
> 
> Hopefully, the developer will be able to get this Pull Request merged into his next release.

Great, your solution solved my problem.
Thank you!

**Closed as completed** 2023-03-29 06:42 UTC
