### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by barking-horse** [johngodley/redirection#1034] opened 2018-06-28 15:06 UTC
```
Plugin: 3.3.1
WordPress: 4.9.6 (single)
PHP: 5.6.31-4+wpengine10
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
JavaScript: https://www.appaloosa.fr/wp-content/plugins/redirection/redirection.js
REST API: https://www.appaloosa.fr/wp-json/

Error: The REST API on this site has been disabled. Machete don't REST (rest_disabled)
Action: redirection/v1/redirect/?orderby=id GET
Code: 403 Forbidden
Raw: {"code":"rest_disabled","message":"The REST API on this site has been disabled. Machete don't REST","data":{"status":403}}

Error: The REST API on this site has been disabled. Machete don't REST (rest_disabled)
Action: redirection/v1/group/ GET
Code: 403 Forbidden
Raw: {"code":"rest_disabled","message":"The REST API on this site has been disabled. Machete don't REST","data":{"status":403}}
```

**Comment by johngodley** [comment] 2018-07-01 14:15
The problem is described above:

`The REST API on this site has been disabled. Machete don't REST (rest_disabled)`

You will need to enable the REST API.

**Comment by johngodley** [comment] 2018-07-07 15:47
Closing for now, please reopen with more details

**Closed by johngodley** 2018-07-07 15:47 UTC
