### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by limekeymedia** [johngodley/redirection#3260] opened 2022-03-16 18:49 UTC
```
Plugin: 5.2.3 4.2
WordPress: 5.9.2 (single)
PHP: 7.4.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0
JavaScript: https://dev-onlineuneedu.pantheonsite.io/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://dev-onlineuneedu.pantheonsite.io/?rest_route=/
Query: ?page=redirection.php

Action: https://dev-onlineuneedu.pantheonsite.io/?rest_route=/redirection/v1/bulk/redirect/delete/&orderby=id POST
Params: {"items":[6]}
Code: 400 Bad Request

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}
```

**Comment by johngodley** [comment] 2022-04-23 13:22
This is likely caused by a cache on your site.

**Comment by johngodley** [comment] 2022-06-04 06:08
Closing for now please reopen with more details.

**Closed by johngodley** 2022-06-04 06:08 UTC
Labels: need-feedback
