### ISSUE TITLE
ReDirection Error

### ISSUE THREAD

**Issue by joelsprechman** [johngodley/redirection#2436] opened 2020-08-31 23:40 UTC
In redirection I have this set(See attached [image)]([url](url
![redirect](https://user-images.githubusercontent.com/52116940/91778582-cb3c1680-eba7-11ea-9ef7-eb6afa61e6f3.JPG)
))

However when I goto the URL
https://www.cassie.net/offers/cravings-to-freedom-c/
it redirects to
https://www.cassie.net/cravings-to-freedom-waitlistc/

Why would this happen?

Browser: 
Chrome Version 85.0.4183.83 (Official Build) (64-bit)
Edge: Microsoft Edge 44.17763.1.0
 Also Firefox + Brave

WP: Version 5.5
Redirection: Version 4.8 

Thanks

**Comment by johngodley** [comment] 2020-09-01 06:53
Do you have other redirects that could match?

**Comment by joelsprechman** [comment] 2020-09-01 18:03
> Do you have other redirects that could match?

No. Here are all that match with "Freedom"
As you can see I Tried  disabling the a* one and now the above redirects to:

https://www.cassie.net/https:/www.cassie.net/cravings-to-freedom-waitlistc

Once it even redirected to this page which is no where in redirection
https://www.cassie.net/product/cravings-to-freedom-christine-melvin/

**Comment by johngodley** [comment] 2020-09-01 18:13
Can you export your redirects and attach them here? The problem is almost certainly another redirect

**Comment by joelsprechman** [comment] 2020-09-01 18:42
> Can you export your redirects and attach them here? The problem is almost certainly another redirect

Sure. Here you go: https://drive.google.com/file/d/1AnMBia6tc2DChNGPLCXgly1MEs7cdc_w/view?usp=sharing

**Comment by johngodley** [comment] 2020-09-02 17:48
The `a*` was the cause of the original problem, and it is not a valid regular expression. The CSV you exported shows that the rule is still enabled, and the redirect still behaves the same, so I think the redirect is still operational.

**Comment by joelsprechman** [comment] 2020-09-02 20:06
thanks,  John

I removed the * but It still acts funky

https://www.cassie.net/product/cravings-to-freedom-c now forwards to a URL that is not listed in redirection at all

https://www.cassie.net/product/cravings-to-freedom-someones-name

Also, are wildcards like that allowed? I looked through the documentation but don't see it listed as a way to create one redirection that would work for a few different URLs

**Comment by johngodley** [comment] 2020-09-02 20:34
Sure, it's being redirected by something else:

https://redirect.li/http/?url=https%3A%2F%2Fwww.cassie.net%2Fproduct%2Fcravings-to-freedom-c

Redirection only ever redirects you to something in its list. It never redirects elsewhere

Wildcards are not supported. Regular expressions are

https://redirection.me/support/redirect-regular-expressions/

**Comment by johngodley** [comment] 2020-09-06 07:04
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-09-06 07:04 UTC
