### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by seojacky** [johngodley/redirection#2772] opened 2021-02-18 15:58 UTC
```
Plugin: 5.0.1
WordPress: 5.4.4 (single)
PHP: 7.3.20
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 OPR/74.0.3911.107
JavaScript: /wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: /wp-json/
Query: ?page=redirection.php

Error: Подходящий маршрут для URL и метода запроса не найден (rest_no_route)
Raw: {"code":"rest_no_route","message":"\u041f\u043e\u0434\u0445\u043e\u0434\u044f\u0449\u0438\u0439 \u043c\u0430\u0440\u0448\u0440\u0443\u0442 \u0434\u043b\u044f URL \u0438 \u043c\u0435\u0442\u043e\u0434\u0430 \u0437\u0430\u043f\u0440\u043e\u0441\u0430 \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d","data":{"status":404}}
```

**Comment by johngodley** [comment] 2021-03-27 12:58
This is likely caused by a security plugin.

**Comment by johngodley** [comment] 2021-03-31 19:12
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-31 19:12 UTC
Labels: need-feedback
