### ISSUE TITLE
Redirection Error Unexpected token < in JSON at position 0 (SyntaxError)

### ISSUE THREAD

**Issue by petarstefanovv** [johngodley/redirection#1687] opened 2019-04-19 22:31 UTC
```
Plugin: 4.2.3
WordPress: 4.9.10 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://dutchseedsshop.com/wp-content/plugins/redirection/redirection.js
REST API: https://dutchseedsshop.com/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
<a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="4e392b2c232f3d3a2b3c0e2a3b3a2d263d2b2b2a3d3d26213e602d2123">[email&#160;protected]</a> to inform them of the time this error occurred,
and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<p>Additionally, a 500 Internal Server Error
error was encountered while trying to use an ErrorDocument to handle the request.</p>
<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script></body></html>

```

**Comment by johngodley** [comment] 2019-04-27 14:06
Your WordPress REST API is returning a 500error. This is likely caused by a security plugin.

https://redirection.me/support/problems/rest-api/

**Comment by johngodley** [comment] 2019-05-04 14:06
Closing for now, please reopen with more details

**Closed by johngodley** 2019-05-04 14:06 UTC
Labels: need-feedback
