### ISSUE TITLE
Distinct regex rules cancelling others

### ISSUE THREAD

**Issue by intellitonic-jared** [johngodley/redirection#3722] opened 2023-10-07 07:32 UTC
### Summary

I have multiple regex redirects of the format:
Rule 1: ^/old-url-1/.* -> example.com/new-url-1
Rule 2: ^/old-url-2/.* -> example.com/new-url-2
Rule 3: ^/old-url-3/.* -> example.com/new-url-3
Rule 4: ^/old-url-4/.* -> example.com/new-url-4

### Actual Behavior

Only the rule in the lowest position takes effect. If I set Rule 1 to position 0 and the rest to higher positions, Rule 1 will work and the rest won't. If I switch Rule 2 into position 0 then the rest won't work. If all rules are put to the same position then only one of them will work.

I've tried clearing cache and swapping each rule in and the behavior repeats - only the rule in the lowest position works.

### Steps to reproduce

Create multiple working regex rules, only the lowest position one will work.

### Environment

Redirection 5.3.10

**Comment by johngodley** [comment] 2023-10-07 07:35
I am not able to reproduce this, and there are no other reports of similar behaviour. This is likely something specific to your site, either caused by a cache (the most likely cause), or something else performing the redirect (you haven't given full URLs so I can't check).

**Comment by johngodley** [comment] 2023-10-25 07:42
Closing for now please re open with more details.

**Closed as completed by johngodley** 2023-10-25 07:42 UTC

**Comment by intellitonic-jared** [comment] 2023-10-31 09:52
Here are a couple examples. Whichever regex rule I move to the highest position will work, while any in the lower positions will not. If I was to swap the event redirect below to position 0 and the online-resources to position 1 and clear the cache, then the event redirect would work and the online-resources redirect would fail.

This works: 
Source URL: ^/online-resources/(.*)
Ignore Case, Regex, Ignore Slash
Match: URL and WordPress page type
Page Type: 404
When matched:  Redirect to URL with HTTP code 301 - Moved Permanently
Target URL: https://cando-ms.org/resource/
Position: 0

This does not work: 
Source URL: ^/event/(.*)
Ignore Case, Regex, Ignore Slash
Match: URL and WordPress page type
Page Type: 404
When matched:  Redirect to URL with HTTP code 301 - Moved Permanently
Target URL: https://cando-ms.org/events/
Position: 1
