### ISSUE TITLE
Problem starting Redirection 5.1.1

### ISSUE THREAD

**Issue by singh28param08** [johngodley/redirection#2985] opened 2021-07-14 09:24 UTC
Plugin: 5.1.1 4.2
WordPress: 5.7.2 (single)
PHP: 7.2.34
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
JavaScript: https://blogverdict.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: https://blogverdict.com/wp-json/

**Comment by johngodley** [comment] 2021-07-14 09:28
As described on the page, this is almost certainly caused by another plugin. You can open your developer console to see if any extra information is shown.

Additionally, your REST API is broken: https://blogverdict.com/wp-json/

**Comment by johngodley** [comment] 2021-07-17 06:09
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-07-17 06:09 UTC
