### ISSUE TITLE
Problem starting Redirection 4.8

### ISSUE THREAD

**Issue by mbajoshuac** [johngodley/redirection#2330] opened 2020-06-06 19:40 UTC
Plugin: 4.8
WordPress: 5.4.1 (single)
PHP: 7.3.17
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
JavaScript: https://dorisidahor.com/wp-content/plugins/redirection/redirection.js
REST API: https://dorisidahor.com/wp-json/

**Comment by johngodley** [comment] 2020-06-06 20:04
Can you open you browser developer console and see what other information is there? This is almost certainly caused by another plugin.

**Comment by johngodley** [comment] 2020-06-29 05:34
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-06-29 05:34 UTC
