### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by THOMXS** [johngodley/redirection#2567] opened 2020-11-09 14:17 UTC
```
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.2.34
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
JavaScript: https://www.qualitatautopecas.com.br/loja/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.qualitatautopecas.com.br/loja/wp-json/
Query: ?page=redirection.php

Action: https://www.qualitatautopecas.com.br/loja/wp-json/redirection/v1/plugin/database/ POST
Code: 200 OK

Error: Unexpected token < in JSON at position 2 (SyntaxError)
Raw: 
<script>

    function loading(e){

        var loading = document.getElementById("loader");

        if(e.value.length > 3){
            loading.style.visibility = "visible";
        }else{
            loading.style.visibility = "hidden";
        }
        
    }
</script>{"status":"need-update","inProgress":true,"current":"4.1","next":"4.2","time":1604931375.8528149127960205078125,"manual":["ALTER TABLE `wp_redirection_logs` DROP `module_id`","ALTER TABLE `wp_redirection_logs` DROP `group_id`","ALTER TABLE `wp_redirection_404` ADD `domain` VARCHAR(255) NULL DEFAULT NULL AFTER `url`","ALTER TABLE `wp_redirection_404` ADD `http_code` INT(11) unsigned NOT NULL DEFAULT 0 AFTER `referrer`","ALTER TABLE `wp_redirection_404` ADD `request_method` VARCHAR(10) NULL DEFAULT NULL AFTER `http_code`","ALTER TABLE `wp_redirection_404` ADD `request_data` MEDIUMTEXT NULL DEFAULT NULL AFTER `request_method`","ALTER TABLE `wp_redirection_404` DROP INDEX `url`","ALTER TABLE `wp_redirection_404` CHANGE COLUMN `url` `url` MEDIUMTEXT NOT NULL"],"complete":25,"result":"ok","reason":"Add extra logging support"}
```

**Comment by johngodley** [comment] 2020-11-09 14:19
The problem is shown above. Your REST API is outputting:

```
<script>

    function loading(e){

        var loading = document.getElementById("loader");

        if(e.value.length > 3){
            loading.style.visibility = "visible";
        }else{
            loading.style.visibility = "hidden";
        }
        
    }
</script>
```

That should not be there, and is likely added by a plugin or theme.

**Comment by johngodley** [comment] 2020-11-14 10:24
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-14 10:24 UTC
