### ISSUE TITLE
404s not being logged

### ISSUE THREAD

**Issue by gsalkin** [johngodley/redirection#1185] opened 2018-09-20 14:44 UTC
The 404 log for Redirection does not return any results for my website. I've tested by triggering 404s on my site and have not seen any logs under the 404 tab.

Any ideas?

**Comment by johngodley** [comment] 2018-09-22 13:50
Can you confirm that you have the logging option enabled?

**Comment by gsalkin** [comment] 2018-09-25 20:07
Yes it appears to be enabled.

**Comment by gsalkin** [comment] 2018-10-09 19:43
Does this feature rely on some kind of configuration of the Wordpress REST API?

**Comment by johngodley** [comment] 2018-11-03 07:44
Sorry for the delay. It doesn't require any configuration.

I suspect this is caused by a plugin or a theme that is 'eating' the 404s and not passing them through WordPress correctly. Can you try temporarily disabling other plugins and changing your theme to see if this has any effect?

**Comment by johngodley** [comment] 2018-11-10 13:09
Closing for now, please reopen with more information

**Closed by johngodley** 2018-11-10 13:09 UTC
Labels: need-feedback
