### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by luxinyu1** [johngodley/redirection#1670] opened 2019-04-15 04:51 UTC
```
Plugin: 4.2.2
WordPress: 5.0.4 (single)
PHP: 5.6.31
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://www.themillennials.cn/wp-content/plugins/redirection/redirection.js
REST API: https://www.themillennials.cn/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Action: redirection/v1/redirect/?orderby=id GET
Code: 503 Service Unavailable
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>

```

**Comment by johngodley** [comment] 2019-04-19 12:41
Your server is returning a 503 error. This may be caused by a security plugin. The warning message should provide details about what to do.

**Comment by johngodley** [comment] 2019-04-27 14:09
Closing for now, please reopen with more information

**Closed by johngodley** 2019-04-27 14:09 UTC
Labels: need-feedback
