### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by jatinbphp** [johngodley/redirection#3312] opened 2022-06-10 08:05 UTC
```
Plugin: 4.6.2
WordPress: 5.1.1 (single)
PHP: 7.4.29
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
JavaScript: https://industrytop5.com.au/wp-content/plugins/redirection/redirection.js
REST API: https://industrytop5.com.au/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<title> 403 Forbidden
</title></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">403</h1>
<h2 style="margin-top:20px;font-size: 30px;">Forbidden
</h2>
<p>Access to this resource on the server is denied!</p>
</div></div></body></html>

```

**Comment by johngodley** [comment] 2022-06-18 11:56
The problem is shown above. Your site is returning a 403 error on your REST API and you will need to fix that.

**Comment by johngodley** [comment] 2022-06-25 10:12
Closing for now, please reopen with more information

**Closed by johngodley** 2022-06-25 10:12 UTC
