### ISSUE TITLE
Not sure if this is a bug

### ISSUE THREAD

**Issue by billbennettnz** [johngodley/redirection#3148] opened 2021-11-28 01:23 UTC
<img width="1082" alt="Screen Shot 2021-11-28 at 2 15 34 PM" src="https://user-images.githubusercontent.com/5514395/143725196-25d8dabb-90e9-4fa8-a94f-a92eb8c381d3.png">

### Summary

I'm not entirely sure this is a bug... it could be a feature that I haven't encountered before or a form of user error. The screenshot shows how the 404 log looks, there are two pages with the same series of 0s.

### Actual Behavior

I was looking at the 404 log and had deleted any that I'd dealt with or decided not to deal with. 

### Steps to reproduce

I can't reproduce the problem, when I left Redirection and returned the log was back to normal. The number of entries with 0 roughly correlates to the number of actual entries in the log. 

### Environment

Safari 15.1 on a Mac. Wordpress is up to date. 5.8.2 There are no new plug-ins.

**Comment by johngodley** [comment] 2021-11-28 11:11
It's not something that should happen, but as it seems to be transitory there's nothing I can really do unless you have a way of recreating it.

**Comment by johngodley** [comment] 2022-07-13 14:52
I'm going to close this for now, but if you can reproduce it again then please do add the details

**Closed by johngodley** 2022-07-13 14:52 UTC
