### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by CrazybutSolid** [johngodley/redirection#2951] opened 2021-06-15 08:36 UTC
```
Plugin: 5.1.1 4.2
WordPress: 5.7.2 (single)
PHP: 7.4.18
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
JavaScript: https://woyago.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: https://woyago.com/wp-json/
Query: ?page=redirection.php

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}
```

**Comment by johngodley** [comment] 2021-07-04 11:31
This is almost certainly caused by an aggressive cache on your site.

**Comment by johngodley** [comment] 2021-07-17 06:06
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-07-17 06:06 UTC
Labels: need-feedback
