### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by abubaker-cs** [johngodley/redirection#1802] opened 2019-06-09 06:37 UTC
```
Plugin: 4.3.1
WordPress: 5.2.1 (single)
PHP: 7.1.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
JavaScript: http://www.systemoflife.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.systemoflife.com/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Action: redirection/v1/redirect/ POST
Params: {"id":0,"url":"http://www.systemoflife.com/articles/refutation/2000147-sufis-forged-the-fatwa-of-ibn-taymiyah-on-visiting-the-grave-of-prophet-peace-be-upon-him","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":false,"flag_case":false,"flag_query":"exact"}},"match_type":"url","action_type":"url","position":0,"group_id":2,"action_code":301,"action_data":{"url":"http://www.systemoflife.com/sufis-forged-the-fatwa-of-ibn-taymiyah-on-visiting-the-grave-of-prophet-peace-be-upon-him/"}}
Code: 500 Internal Server Error
Raw: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<title>732</title>
<meta http-equiv="Cache-Control" content="no-cache"/>
</head>
<body>
<p>
Internal Server Error 
</p>
</body>
</html>

```

**Comment by johngodley** [comment] 2019-06-14 05:44
Please follow the plugin information regarding this problem. It should suggest that a security plugin may be the cause.

**Comment by johngodley** [comment] 2019-06-20 17:47
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-06-20 17:47 UTC
Labels: need-feedback
