### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by AdrienAVAL** [johngodley/redirection#697] opened 2018-01-29 09:08 UTC
```
Plugin: 3.1
WordPress: 4.9.2 (multi)
PHP: 5.3.10-1ubuntu3.14
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
REST API: https://www.avendrealouer.fr/conseils/wp-json/

Error: Le nonce du cookie n’est pas valide
Action: redirection/v1/redirect?orderby=id GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Le nonce du cookie n\u2019est pas valide","data":{"status":403}}

Error: Le nonce du cookie n’est pas valide
Action: redirection/v1/group GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Le nonce du cookie n\u2019est pas valide","data":{"status":403}}
```

**Comment by johngodley** [comment] 2018-01-30 17:29
Can you describe your setup a little? When I try and access https://www.avendrealouer.fr/conseils/wp-json/ I get a HTTP 500 error. Are you running any security plugins?

I see you are using multisite. Is this the root domain?

**Comment by AdrienAVAL** [comment] 2018-01-31 14:48
Hi John, 

Sorry, the 500 error was due to Woo commerce plugin which is now enabled. You can now access to https://www.avendrealouer.fr/conseils/wp-json/

We are using multisite and the root domain is https://www.avendrealouer.fr/ but it's not a wordpress. The 3 sites built on wordpress are https://www.avendrealouer.fr/conseils/ https://www.avendrealouer.fr/pros/ and https://www.avendrealouer.frpresse/

I hope I've been clear...

Thanks a lot
Adrien

**Comment by johngodley** [comment] 2018-02-03 15:08
I investigated this problem on another server and found that it was caused by a Varnish config. Do you know if you are using Varnish on your server?

**Comment by johngodley** [comment] 2018-02-11 09:24
Can you try the 3.2 beta and let me know if it helps:

https://github.com/johngodley/redirection/releases/tag/3.2-beta

**Comment by johngodley** [comment] 2018-02-17 16:49
Closing for now, please reopen with more information

**Closed by johngodley** 2018-02-17 16:49 UTC

**Comment by AdrienAVAL** [comment] 2018-02-27 14:25
Hi john,

Everything is working now.
Thanks a lot

Adrien



*Adrien GUIDICELLI*

Content Manager

01 78 91 04 03

*adrien.guidicelli@schibsted.com* <adrien.guidicelli@schibsted.com>


*www.avendrealouer.fr/conseils/
<https://www.avendrealouer.fr/conseils/> www.avendrealouer.fr
<https://www.avendrealouer.fr/>*


2018-02-03 16:08 GMT+01:00 John <notifications@github.com>:
