### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by AgnesCraftip** [johngodley/redirection#2146] opened 2020-01-16 04:58 UTC
Plugin: 4.6.2
WordPress: 5.3.2 (single)
PHP: 7.1.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: https://housego.com.tw/wp-content/plugins/redirection/redirection.js
REST API: https://housego.com.tw/wp-json/
Buster: 4.6.2 === 4.6.2

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    in span
    in div
    in div
    in div
    in t
    in p
    in div
    in div
    in t
    in p
    in t
    in p
    in M
    in py

**Comment by johngodley** [comment] 2020-01-18 14:22
Can you open your browser's developer console and see if other information is shown? The error is likely caused by another plugin.

**Comment by johngodley** [comment] 2020-02-02 17:00
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-02-02 17:00 UTC
Labels: need-feedback
