### ISSUE TITLE
Unexpected fqdn in target when using "ignore and pass parameters"

### ISSUE THREAD

**Issue by YesThatAllen** [johngodley/redirection#2033] opened 2019-10-21 00:55 UTC
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

I'm trying to take a URL sent to our `www` site and pass it to a page in our `support` site, and retain url parameters

### Actual Behavior

Browsers are redirected to the `www` site

### Expected Behavior 

I would expect the browser to be redirected to the support site, with any URL Parameters appended.

### Steps to reproduce

this is the setup:

![2019-10-18_17-41-23](https://user-images.githubusercontent.com/2879972/67169781-3bb4bd00-f373-11e9-96ab-4eafae731282.png)

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

this is browser independent.

Hosting is nginx/wordpress 5.2.4, redirection 4.4.2

**Comment by johngodley** [comment] 2019-10-27 06:24
Can you explain what the problem is? It's not obvious from the above description.

**Comment by johngodley** [comment] 2019-11-03 09:13
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-11-03 09:13 UTC
Labels: need-feedback

**Comment by YesThatAllen** [comment] 2021-02-02 06:24
Looking back on this, there was either a conflicting redirection, or some caching issue. But the problem no longer exists in the current version. Thank you
