### ISSUE TITLE
[Suggestion] Double redirection detection

### ISSUE THREAD

**Issue by ShadowXVII** [johngodley/redirection#2889] opened 2021-05-03 04:29 UTC
Over time, the list of redirects might get quite long. For a site with hundreds of redirects, it can be hard to see any "double redirects" -- i.e. URL 1 redirects that to a second URL, which in turn redirects to the final destination.

A way to "scan" or "highlight" said double redirects would be useful. This could be as simple as showing which rules would redirect to other rules.

1. `/first-page` => `/second-page`
2. `/second-page` => `/final-page`

In the ruleset above, the first rule would be highlighted as a "duplicate" (?) of the second rule. The first rule could be updated to redirect directly to `/final-page`, saving a 301. Some older sites might end up with additional levels of unnecessary redirection.

**Comment by johngodley** [comment] 2021-05-03 12:34
It's quite complicated with many factors to take into account.

Closing as duplicate of #82

**Closed by johngodley** 2021-05-03 12:34 UTC
