### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by manas794** [johngodley/redirection#1889] opened 2019-07-22 13:24 UTC
```
Plugin: 4.3.1
WordPress: 5.2.2 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
JavaScript: https://MsLearning.in/wp-content/plugins/redirection/redirection.js
REST API: http://MsLearning.in/index.php?rest_route=/

Error: Failed to fetch
```

**Comment by johngodley** [comment] 2019-07-25 20:30
The message tells you what the problem is - you need to change your http URL to https

**Comment by johngodley** [comment] 2019-08-03 09:55
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-08-03 09:55 UTC
Labels: need-feedback
