### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Cm-8** [johngodley/redirection#2295] opened 2020-05-13 08:13 UTC
```
Plugin: 4.7.2
WordPress: 5.4.1 (single)
PHP: 7.4.5
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
JavaScript: https://xxxxxx.it/wp-content/plugins/redirection/redirection.js
REST API: https://xxxxxx.it/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

**Comment by johngodley** [comment] 2020-05-16 09:40
As shown above your REST API is returning an error. This may be caused by a security plugin.

**Comment by johngodley** [comment] 2020-05-23 09:57
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-05-23 09:57 UTC
Labels: need-feedback
