### ISSUE TITLE
Error loading data on 2.6.4 and 2.6.5

### ISSUE THREAD

**Issue by aeromusek** [johngodley/redirection#251] opened 2017-07-19 22:35 UTC
The last couple updates of this plugin (since the move to React, I believe?) have started showing the following error on the <strong>Log</strong> and <strong>404s</strong> tabs:

```
Sorry but something went wrong loading the data - please try again

Loading chunk 0 failed.
```

The browser debug console shows the following:

```
Failed to load resource: the server responded with a status of 404 (Not Found) https://example.com/wp-admin/redirection-compat-bace59f2d78f2fe916a9.js
```

Any help much appreciated!

**Comment by aeromusek** [comment] 2017-07-19 22:58
Reverting to 2.6.1 fixes the problem for now.

**Comment by johngodley** [comment] 2017-07-20 05:25
I believe this is just a browser problem, and if you use Chrome it will work. It will be fixed for other browsers in the next version

**Comment by aeromusek** [comment] 2017-07-20 18:55
@johngodley you are absolutely right: Safari-only issue. Looking forward to the fix!

**Comment by johngodley** [comment] 2017-07-22 12:12
@aeromusek what browser and version were you using? I've tried with Safari and Edge and couldnt reproduce a problem.

**Comment by aeromusek** [comment] 2017-07-22 23:45
@johngodley I have two machines, one on macOS 10.12.5, and the other on 10.12.3 (out-of-date corporate security policy blocking updates). The 10.12.5 machine has no trouble, but the 10.12.3 was getting stuck.

**Comment by johngodley** [comment] 2017-07-26 07:27
Just a note to say that I reproduced this on an older version of Safari, and it will be fixed in the next release.

**Closed by johngodley** 2017-07-26 07:27 UTC
