### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Islamjamel24** [johngodley/redirection#3860] opened 2024-05-18 20:42 UTC
```
Plugin: 5.4.2 4.2
WordPress: 6.5.3 (single)
PHP: 8.2.19
Browser: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36
JavaScript: https://greatishop.net/wp-content/plugins/redirection/redirection.js?ver=5.4.2-2dfac6cbb88915145528d6945ba453dd
REST API: https://greatishop.net/wp-json/
Query: ?page=redirection.php&sub=options

Error: لم يتم العثور على مسار يتوافق مع الرابط URL وطريقة الطلب. (rest_no_route)
Raw: {"code":"rest_no_route","message":"\u0644\u0645 \u064a\u062a\u0645 \u0627\u0644\u0639\u062b\u0648\u0631 \u0639\u0644\u0649 \u0645\u0633\u0627\u0631 \u064a\u062a\u0648\u0627\u0641\u0642 \u0645\u0639 \u0627\u0644\u0631\u0627\u0628\u0637 URL \u0648\u0637\u0631\u064a\u0642\u0629 \u0627\u0644\u0637\u0644\u0628.","data":{"status":404}}
```

**Comment by johngodley** [comment] 2024-06-15 05:24
Please follow the onscreen instructions. This is caused by something on your site.

**Comment by johngodley** [comment] 2024-11-23 14:26
Closing for now, please reopen with more details.

**Closed as completed by johngodley** 2024-11-23 14:26 UTC
Labels: need-feedback
