### ISSUE TITLE
Modal doesn't show on options in 404s errors page

### ISSUE THREAD

**Issue by KonradSajdak** [johngodley/redirection#876] opened 2018-04-04 06:40 UTC
Hi!

I have little problem with modal when click on any link (Agent Info | Geo Info | Delete | Add Redirect). Backdrop shows but any modal part does not show. 

To reproduce problem simply go to 404s errors page on Redirection settings and click to any link below logged 404 error. 

I tested this problem and it throws on Chrome 65.0.3325.181, on Opera 51.0.2830.55 and Firefox 58.0.2, a don't tested any other browser. 
This problem starts on 3.2 version of Redirection. My version of Wordpress is 4.9.5.

**Comment by johngodley** [comment] 2018-04-08 15:53
I think this is something specific to your site, and could be caused by another plugin. Can you open your browser's developer console and see if any errors are shown?

**Comment by johngodley** [comment] 2018-04-22 14:54
Closing for now, please reopen with more information

**Closed by johngodley** 2018-04-22 14:54 UTC
