### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by binnythap** [johngodley/redirection#1691] opened 2019-04-22 04:19 UTC
```
Plugin: 4.2.3
WordPress: 5.1.1 (single)
PHP: 7.0.31
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://www.mysite.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.mysite.com/wp-json/

Error: Unexpected end of JSON input (SyntaxError)
Action: redirection/v1/setting/ GET
Code: 500 Internal Server Error
Raw: -no data-
```
replaced my original site address above.

this has been happening since the latest update

**Comment by johngodley** [comment] 2019-04-27 14:06
Your WordPress REST API is returning a 500 error. This is likely caused by a security plugin.

https://redirection.me/support/problems/rest-api/

**Comment by johngodley** [comment] 2019-05-04 14:05
Closing for now, please reopen with more details

**Closed by johngodley** 2019-05-04 14:05 UTC
Labels: need-feedback

**Comment by websupergirl** [comment] 2019-05-23 03:42
I have disabled caching (wp-rocket), security (Wordfence) ... and still this same error.

**Comment by websupergirl** [comment] 2019-05-23 03:43
I can't even check plugin status because it won't show me that without upgrading the database, and I can't upgrade the database because of this error.

Plugin: 4.2.3
WordPress: 5.1.1 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
JavaScript: https://confidentrider.online/wp-content/plugins/redirection/redirection.js
REST API: https://confidentrider.online/wp-json/

Error: Unexpected end of JSON input (SyntaxError)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 500 Internal Server Error
Raw: -no data-
