### ISSUE TITLE
Issue: Total redirects imported: 0

### ISSUE THREAD

**Issue by iremkulakci** [johngodley/redirection#3345] opened 2022-07-11 10:13 UTC
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I am trying to import the redirection file to the site but I receive this error 'Total redirects imported: 0 Double-check the file is the correct format!'

### Actual Behavior

The file format is csv and I assume the format is correct. I am sending you the csv file attached.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

The version of Redirection plugin is 5.2
The version of Wordpress is 5.2.3
Browser is Google Chrome (Chrome 103 on Windows 10)

[Firstmed redirection.csv](https://github.com/johngodley/redirection/files/9082980/Firstmed.redirection.csv)

**Comment by johngodley** [comment] 2022-07-13 07:00
I'm unable to reproduce this with the CSV file. Does your server have enough memory and upload size to support that file?

**Comment by johngodley** [comment] 2022-07-28 18:33
Closing for now, please reopen with more details.

**Closed by johngodley** 2022-07-28 18:33 UTC
