### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by webpyro** [johngodley/redirection#1060] opened 2018-07-13 02:43 UTC
```
Plugin: 3.3.1
WordPress: 4.9.7 (single)
PHP: 7.0.30-1~dotdeb+8.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
JavaScript: https://pmmentors.com/wp-content/plugins/redirection/redirection.js
REST API: https://pmmentors.com/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

**Comment by johngodley** [comment] 2018-07-16 05:24
Please logout and login again

**Comment by sidneydemoraes** [comment] 2018-07-19 20:56
Hi, @johngodley. I have that very same issue. Loging out and in didn't work.
Do you want me to open a new issue? Maybe it's easier for you to manage in a single issue.

**Comment by tongrhj** [comment] 2018-07-30 10:12
I am also experiencing this issue.

I can verify that logging in and out changes the nonce that is used, but all the nonces returned the 403 error above.

Clearing cookies and accessing using different users also did not address this issue.

Is there any information that would aid in the debugging?

```
Plugin: 3.4
WordPress: 4.9.7 (single)
PHP: 5.6.36-1+wpengine13
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
JavaScript: https://www.candybar.co/wp-content/plugins/redirection/redirection.js
REST API: https://www.candybar.co/blog/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

**Comment by johngodley** [comment] 2018-09-22 13:46
I'm pretty sure this is to do with a caching issue, but I'm unable to reproduce the problem. If anyone is willing to allow me to login to their site and see if I can discover the problem then please contact me directly at https://redirection.me/contact/

**Comment by johngodley** [comment] 2018-10-28 19:08
Closing for now, please reopen with more information

**Closed by johngodley** 2018-10-28 19:08 UTC
Labels: api, need-feedback
