### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by eddogustian7** [johngodley/redirection#2944] opened 2021-06-11 06:16 UTC
```
Plugin: 5.1.1 4.2
WordPress: 5.7.2 (single)
PHP: 7.2.34
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
JavaScript: https://melandas-indonesia.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: /wp-json/
Query: ?page=redirection.php&sub=support

Error: <p>There has been a critical error on this website.</p><p><a href="https://wordpress.org/support/article/faq-troubleshooting/">Learn more about troubleshooting WordPress.</a></p> (internal_server_error)
Raw: {"code":"internal_server_error","message":"<p>There has been a critical error on this website.<\/p><p><a href=\"https:\/\/wordpress.org\/support\/article\/faq-troubleshooting\/\">Learn more about troubleshooting WordPress.<\/a><\/p>","data":{"status":500},"additional_errors":[]}
```

**Comment by johngodley** [comment] 2021-07-04 11:32
You will need to look at your site error log to see what the problem is.

**Comment by johngodley** [comment] 2021-07-17 06:06
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-07-17 06:06 UTC
Labels: need-feedback
