### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by jeremypascual** [johngodley/redirection#2348] opened 2020-06-18 18:30 UTC
```
Plugin: 4.8
WordPress: 5.4.1 (single)
PHP: 7.3.19
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
JavaScript: https://www.thx.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.thx.com/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment] 2020-06-29 05:31
Your REST API is being blocked. This is probably caused by a security plugin.

**Comment by johngodley** [comment] 2020-07-18 15:23
Closing for now, please reopen with more information.

**Comment by johngodley** [comment] 2020-07-18 15:23
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-07-18 15:23 UTC
Labels: need-feedback
