### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by namo57** [johngodley/redirection#3338] opened 2022-07-07 06:55 UTC
```
Plugin: 5.2.3 4.2
WordPress: 6.0 (single)
PHP: 7.4.30
Browser: Mozilla/5.0 (Windows NT 10.0; rv:102.0) Gecko/20100101 Firefox/102.0
JavaScript: https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://namoshop.ir/wp-json/
Query: ?page=redirection.php
NotFoundError: Node.removeChild: The node to be removed is not a child of this node

div
Ey@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:635612
_E<@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:741208
f@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:376159
td
gm@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:616317
tr
vm@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:616811
tbody
table
_m@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:617880
hy@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:634080
div
ZE<@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:746832
f@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:376159
VE@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:749590
wp@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:541372
div
a@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:484677
r_<@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:752945
f@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:376159
Fe@https://namoshop.ir/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be:2:374080
s_
```

**Comment by johngodley** [comment] 2022-07-07 07:00
This is caused by another plugin or a browser extension.

**Comment by Ronitkk** [comment] 2022-07-08 06:54
Why this email are coming to me and why Should I reply them I don't have
any profit of this plz dont send this email daily.

**Comment by johngodley** [comment] 2022-07-13 06:14
Closing for now please reopen with more information.

**Closed by johngodley** 2022-07-13 06:14 UTC
