### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by foysalimran** [johngodley/redirection#2037] opened 2019-10-23 05:07 UTC
```
Plugin: 4.4.2
WordPress: 5.2.4 (single)
PHP: 7.2.23-1+0~20191008.27+debian8~1.gbp021266
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
JavaScript: https://noemprendacon.com/wp-content/plugins/redirection/redirection.js
REST API: https://noemprendacon.com/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <br />
<b>Deprecated</b>:  Function create_function() is deprecated in <b>/home/117276.cloudwaysapps.com/dzuejyyzcy/public_html/wp-content/plugins/backupbuddy/init_global.php</b> on line <b>112</b><br />
{"items":[{"id":2,"url":"\/poliza-de-privacidad\/","match_url":"\/poliza-de-privacidad","match_data":{"source":{"flag_query":"exact","flag_case":false,"flag_trailing":false,"flag_regex":false}},"action_code":301,"action_type":"url","action_data":{"url":"https:\/\/noemprendacon.com\/privacy-policy-terms-and-conditions\/"},"match_type":"url","title":"","hits":19,"regex":false,"group_id":1,"position":1,"last_access":"August 31, 2019","enabled":true},{"id":1,"url":"\/terminos-y-condiciones\/","match_url":"\/terminos-y-condiciones","match_data":{"source":{"flag_query":"exact","flag_case":false,"flag_trailing":false,"flag_regex":false}},"action_code":301,"action_type":"url","action_data":{"url":"https:\/\/noemprendacon.com\/privacy-policy-terms-and-conditions\/"},"match_type":"url","title":"","hits":80,"regex":false,"group_id":1,"position":0,"last_access":"October 7, 2019","enabled":true}],"total":2}
```

**Comment by johngodley** [comment] 2019-10-27 06:09
The problem is shown in the message:
`<b>Deprecated</b>:  Function create_function() is deprecated in <b>/home/117276.cloudwaysapps.com/dzuejyyzcy/public_html/wp-content/plugins/backupbuddy/init_global.php</b>`

**Comment by johngodley** [comment] 2019-11-03 09:14
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-11-03 09:14 UTC
Labels: need-feedback
