### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by alexandresgf** [johngodley/redirection#1793] opened 2019-06-03 23:42 UTC
```
Plugin: 4.3
WordPress: 5.2.1 (single)
PHP: 5.6.20-0+deb8u1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
JavaScript: https://dev.georanker.com/content/plugins/redirection/redirection.js
REST API: https://dev.georanker.com/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment] 2019-06-14 05:55
As the plugin should indicate this is likely caused by a security plugin.

**Comment by johngodley** [comment] 2019-06-20 17:47
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-06-20 17:47 UTC
Labels: need-feedback
