### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by bmillersw** [johngodley/redirection#2128] opened 2020-01-10 15:59 UTC
```
Plugin: 4.6.2
WordPress: 5.3.2 (single)
PHP: 7.1.33-3+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
JavaScript: http://staging.hcconcrete.flywheelsites.com/wp-content/plugins/redirection/redirection.js
REST API: http://staging.hcconcrete.flywheelsites.com/wp-json/

Error: Unexpected token W in JSON at position 1 (SyntaxError)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 200 OK
Raw: 
Warning: Invalid argument supplied for foreach() in /www/wp-includes/class-wp-post-type.php on line 526
{"status":"need-update","inProgress":true,"current":"2.4","next":"4.1","time":1578671913.238292,"manual":["ALTER TABLE `wp_redirection_items` ADD INDEX `match_url` (`match_url`(191))","ALTER TABLE `wp_redirection_items` ADD `match_data` TEXT NULL DEFAULT NULL AFTER `match_url`","UPDATE `wp_redirection_items` SET match_url='regex' WHERE regex=1","UPDATE `wp_redirection_items` SET match_url=SUBSTRING_INDEX(LOWER(url), '?', 1) WHERE regex=0","UPDATE `wp_redirection_items` SET match_url=LEFT(match_url,LENGTH(match_url)-1) WHERE regex=0 AND match_url != '\/' AND RIGHT(match_url, 1) = '\/'","UPDATE `wp_redirection_items` SET match_url='\/' WHERE match_url=''","UPDATE `wp_redirection_items` SET match_url=LOWER(LEFT(SUBSTRING_INDEX(url, '?', 1),LENGTH(SUBSTRING_INDEX(url, '?', 1)) - 1)) WHERE RIGHT(SUBSTRING_INDEX(url, '?', 1), 2) = '\/\/' AND regex=0","UPDATE `wp_redirection_items` SET match_url='\/' WHERE match_url=''"],"complete":20,"result":"ok","reason":"Add a matched URL column"}
```

**Comment by johngodley** [comment] 2020-01-10 17:44
You can see the error, which appears to be caused by a post type. This is unrelated to Redirection and is likely caused by another plugin.

**Comment by johngodley** [comment] 2020-01-18 14:24
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-01-18 14:24 UTC
Labels: need-feedback
