### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by orso081980** [johngodley/redirection#1648] opened 2019-04-08 20:56 UTC
```
Plugin: 4.2.1
WordPress: 5.1.1 (single)
PHP: 5.6.18
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
JavaScript: https://edumarketinggroup.com/ibiwp/wp-content/plugins/redirection/redirection.js
REST API: https://edumarketinggroup.com/ibiwp/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 200 OK
Raw: <br />
<b>Notice</b>:  rest_enabled is <strong>deprecated</strong> since version 4.7.0! Use rest_authentication_errors instead. The REST API can no longer be completely disabled, the rest_authentication_errors filter can be used to restrict access to the API, instead. in <b>/home/edumarketinggrou/public_html/ibiwp/wp-includes/functions.php</b> on line <b>4605</b><br />
<br />
<b>Warning</b>:  call_user_func_array() expects parameter 1 to be a valid callback, function '_return_false' not found or invalid function name in <b>/home/edumarketinggrou/public_html/ibiwp/wp-includes/class-wp-hook.php</b> on line <b>286</b><br />
<br />
<b>Warning</b>:  call_user_func_array() expects parameter 1 to be a valid callback, function '_return_false' not found or invalid function name in <b>/home/edumarketinggrou/public_html/ibiwp/wp-includes/class-wp-hook.php</b> on line <b>286</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/edumarketinggrou/public_html/ibiwp/wp-includes/functions.php:4605) in <b>/home/edumarketinggrou/public_html/ibiwp/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1258</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/edumarketinggrou/public_html/ibiwp/wp-includes/functions.php:4605) in <b>/home/edumarketinggrou/public_html/ibiwp/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1258</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/edumarketinggrou/public_html/ibiwp/wp-includes/functions.php:4605) in <b>/home/edumarketinggrou/public_html/ibiwp/wp-includes/rest-api.php</b> on line <b>587</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/edumarketinggrou/public_html/ibiwp/wp-includes/functions.php:4605) in <b>/home/edumarketinggrou/public_html/ibiwp/wp-includes/rest-api.php</b> on line <b>588</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/edumarketinggrou/public_html/ibiwp/wp-includes/functions.php:4605) in <b>/home/edumarketinggrou/public_html/ibiwp/wp-includes/rest-api.php</b> on line <b>589</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/edumarketinggrou/public_html/ibiwp/wp-includes/functions.php:4605) in <b>/home/edumarketinggrou/public_html/ibiwp/wp-includes/rest-api.php</b> on line <b>590</b><br />
{"status":"need-update","inProgress":true,"current":"2.4","next":"4.1","time":1554756991.81,"manual":["ALTER TABLE `wp_redirection_items` ADD `match_url` VARCHAR(2000) NULL DEFAULT NULL AFTER `url`","ALTER TABLE `wp_redirection_items` ADD INDEX `match_url` (`match_url`(191))","ALTER TABLE `wp_redirection_items` ADD `match_data` TEXT NULL DEFAULT NULL AFTER `match_url`","UPDATE `wp_redirection_items` SET match_url='regex' WHERE regex=1","UPDATE `wp_redirection_items` SET match_url=SUBSTRING_INDEX(LOWER(url), '?', 1) WHERE regex=0","UPDATE `wp_redirection_items` SET match_url=LEFT(match_url,LENGTH(match_url)-1) WHERE regex=0 AND match_url != '\/' AND RIGHT(match_url, 1) = '\/'","UPDATE `wp_redirection_items` SET match_url='\/' WHERE match_url=''","UPDATE `wp_redirection_items` SET match_url=LOWER(LEFT(SUBSTRING_INDEX(url, '?', 1),LENGTH(SUBSTRING_INDEX(url, '?', 1)) - 1)) WHERE RIGHT(SUBSTRING_INDEX(url, '?', 1), 2) = '\/\/' AND regex=0","UPDATE `wp_redirection_items` SET match_url='\/' WHERE match_url=''"],"complete":10,"result":"ok","reason":"Migrate any groups with invalid module ID"}
```

**Comment by orso081980** [comment] 2019-04-08 20:57
I tried to update my redirection plugin on wordpress, but I receive this message and I'm not sure what it is about.

**Comment by johngodley** [comment] 2019-04-08 21:01
The problem is shown above:

`<b>Notice</b>:  rest_enabled is <strong>deprecated</strong> since version 4.7.0! Use rest_authentication_errors instead. The REST API can no longer be completely disabled, the rest_authentication_errors filter can be used to restrict access to the API, instead. in <b>/home/edumarketinggrou/public_html/ibiwp/wp-includes/functions.php</b> on line <b>4605</b><br />
`

Something on your site is trying to disable the WordPress REST API, and this is no longer supported. It's probably a plugin.

**Comment by johngodley** [comment] 2019-04-14 14:48
Closing for now, please reopen with more details

**Closed by johngodley** 2019-04-14 14:48 UTC
Labels: need-feedback
