### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by mark-smith0439** [johngodley/redirection#2769] opened 2021-02-17 19:22 UTC
```
Plugin: 5.0.1
WordPress: 5.3.2 (single)
PHP: 7.2.29
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
JavaScript: https://queenstown.crowneplaza.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://queenstown.crowneplaza.com/wp-json/
Query: ?page=redirection.php

Error: <p>There has been a critical error on your website.</p><p><a href="https://wordpress.org/support/article/debugging-in-wordpress/">Learn more about debugging in WordPress.</a></p> (internal_server_error)
Raw: {"code":"internal_server_error","message":"<p>There has been a critical error on your website.<\/p><p><a href=\"https:\/\/wordpress.org\/support\/article\/debugging-in-wordpress\/\">Learn more about debugging in WordPress.<\/a><\/p>","data":{"status":500},"additional_errors":[]}
```

**Comment by johngodley** [comment] 2021-02-17 19:24
The problem is shown above:

https://queenstown.crowneplaza.com/wp-json/

**Comment by mark-smith0439** [comment] 2021-02-17 19:26
What does that mean?

**Comment by johngodley** [comment] 2021-02-17 19:27
If you click the link you will see an error. You will need to fix the error before the plugin can work. The plugin is not causing the error.

**Comment by mark-smith0439** [comment] 2021-02-17 19:29
Oh ok, Any idea on how I might fix it?

**Comment by johngodley** [comment] 2021-02-17 19:31
It's a general error message with no detail, so I couldn't say. You can look at your site error log and see if that shows anything else. You might be out of memory, have a bad plugin, etc

**Comment by mark-smith0439** [comment] 2021-02-17 19:33
Ok awesome, thanks for that. :)

**Comment by johngodley** [comment] 2021-02-17 19:33
If you use the 'Site Health' option in WordPress it might also tell you more

**Comment by johngodley** [comment] 2021-03-27 12:58
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-27 12:58 UTC
