### ISSUE TITLE
Problem starting Redirection 5.0.1

### ISSUE THREAD

**Issue by GendalfW** [johngodley/redirection#2809] opened 2021-03-11 16:01 UTC
```
SyntaxError: illegal character U+201A http://seo-gen.org.ua/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3 2,ReferenceError: QTags is not defined http://seo-gen.org.ua/wp-admin/tools.php?page=redirection.php 414
```

Plugin: 5.0.1
WordPress: 5.7 (single)
PHP: 7.2.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0
JavaScript: http://seo-gen.org.ua/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: http://seo-gen.org.ua/wp-json/

**Comment by johngodley** [comment] 2021-03-11 16:08
QTags is not part of Redirection. As the page states the problem is likely caused by something else.

**Comment by GendalfW** [comment] 2021-03-11 16:29
> QTags is not part of Redirection. As the page states the problem is likely caused by something else.

All plugins were disabled and the "Redirection" plugin has been rechecked. I also checked the list of problems.  It's the same. Issue remained.

**Comment by johngodley** [comment] 2021-03-11 16:31
And it still mentions qtags? This is not part of Redirection and something else must be causing it.

I can see you raised the same issue previously: https://github.com/johngodley/redirection/issues/2519

**Comment by johngodley** [comment] 2021-03-27 12:48
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-03-27 12:48 UTC
