### ISSUE TITLE
When you delete a product from woocommerce, it creates the redirections hundreds of times in the plugin

### ISSUE THREAD

**Issue by gevcen** [johngodley/redirection#1967] opened 2019-09-22 11:12 UTC
I have no screenshot anymore because i cleaned up my dashboard of redirections sorry.

### Summary

When you delete a product from woocommerce, it creates the redirections hundreds of times in the plugin

### Actual Behavior

Redirections is created hundreds of times.

### Steps to reproduce

1) go in woocommerce
2) delete product
3) go in plugin redirection

### Environment

WP 5.2
Chrome
Redirection update 22.09.2019

**Comment by johngodley** [comment] 2019-09-26 19:52
I am not able to reproduce this.

I installed Woocommerce and created a product. I then configured Redirection to monitor for deleted posts. I then deleted the product and it created a single disabled redirect.

It is possible this is caused by some specific Woocommerce you have, or maybe a WC extension.

You can disable the automatic creation of redirects from the options page.

**Comment by johngodley** [comment] 2019-10-05 12:06
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-10-05 12:06 UTC
Labels: need-feedback
