### ISSUE TITLE
Problem starting Redirection 4.2.3

### ISSUE THREAD

**Issue by abolffazl** [johngodley/redirection#1847] opened 2019-06-21 13:51 UTC
Plugin: 4.2.3
WordPress: 5.2.2 (single)
PHP: 5.6.38
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
JavaScript: https://spatena.com/wp-content/plugins/redirection/redirection.js
REST API: https://spatena.com/wp-json/

**Comment by johngodley** [comment] 2019-06-23 09:37
Please open your browser's developer console and see if more information is shown. This is likely caused by another plugin.

**Comment by johngodley** [comment] 2019-07-13 14:42
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-07-13 14:42 UTC
Labels: need-feedback
