### ISSUE TITLE
WordPress redirects Export file CSV and JSON is empty

### ISSUE THREAD

**Issue by postapollo** [johngodley/redirection#3855] opened 2024-05-07 15:42 UTC
The Download button for WordPress redirects is not working correctly. The downloaded files are empty. 

I'm trying to download an export of my site's redirects, but the CSV and JSON export files are empty with a size of zero bytes. Maybe there is a max size limit? I'm able to download the `Apache redirects` and `Nginx redirects` without issue, these are under 1MB.
![Screenshot 2024-05-07 at 10 16 44 AM](https://github.com/johngodley/redirection/assets/11970191/d9aea4fb-ce3a-4b6b-86f7-931f981e3b9f)

We have 5,113 redirection items
![Screenshot 2024-05-07 at 10 22 49 AM](https://github.com/johngodley/redirection/assets/11970191/1300e28b-68ff-48b6-a72f-646f22f311ab)
If I go to Export: `Everything, CSV` --> View and paste the window into excel, I get 5,114 rows. Imported into a CSV manually it's 676 KB. 

Options which return an empty file: 
```
Everything, CSV
Everything, JSON
WordPress redirects, JSON
WordPress redirects, CSV
```

WordPress: 6.1
PHP: 8.1
Redirection: 5.4.2 
Browser: Chrome 124.0.6367.119 & Firefox 125.0.3

**Comment by johngodley** [comment] 2024-06-15 05:26
I am unable to reproduce this. Do you have any errors on your server?

**Comment by johngodley** [comment] 2024-11-23 14:27
Closing for now, please reopen with more details.

**Closed as completed by johngodley** 2024-11-23 14:27 UTC
Labels: need-feedback
