### ISSUE TITLE
redirection adding incorrect redirects

### ISSUE THREAD

**Issue by ChrisScottUK** [johngodley/redirection#141] opened 2016-10-18 16:28 UTC
I'm having this strange issue where periodically a post on wordpress will start being redirected to an alternative post.
Upon checking redirect, there will be many many entries all diverting the post to this new one. So far although different posts get redirected, they always redirect to the same post.

I'm at a total loss to explain this behaviour.

Anyone got any ideas?

**Comment by aaronparker** [comment] 2017-03-19 12:55
I think I have something similar as well. After editing a published post, it gets redirected to /layerswp. Layers is the theme used on my site.

**Comment by ChrisScottUK** [comment] 2017-05-08 11:04
For me, this behavior of redirection is caused by a conflict with 'Ozh' Tweet Archiver' plugin. Since deactivated the Ozh plugin there is no longer an issue.

**Comment by johngodley** [comment] 2017-08-08 05:14
Redirection has been changed since this was created and now has additional checks when auto-creating redirects. I've been unable to reproduce a problem with Ozh Tweet Archiver, or with other plugins that also have been known to cause problems. For now I'll close this, but please reopen if it continues

**Closed by johngodley** 2017-08-08 05:14 UTC
Labels: bug
