### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by vguadalupe** [johngodley/redirection#1659] opened 2019-04-12 16:12 UTC
```
Plugin: 4.2.1
WordPress: 4.9.10 (single)
PHP: 7.2.16-1+ubuntu18.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://www.lapintagalapagoscruise.com/wp-content/plugins/redirection/redirection.js
REST API: /wp-json/

Error: Unexpected token < in JSON at position 1 (SyntaxError)
Raw: 	<!DOCTYPE html>
	<html style="height: 100%;">
	<meta charset="UTF-8">
	<head><title>403 Access Forbidden</title></head>
	<body style="height: 100%;">
	<div style="display: flex; align-items: center; justify-content: center; height: 70%;">
		<div style="background-color: #eee; width: 70%; border: solid 3px #ddd; padding: 1.5em 3em 3em 3em; font-family: Arial, Helvetica, sans-serif;">
			<div style="display: table-row;">
				<div style="display: table-cell; font-size: 150px; color: red; vertical-align: middle; padding-right: 50px;">
					&#9995;
				</div>
				<div style="display: table-cell; vertical-align: middle;">
					<h1>We're sorry, you are not allowed to proceed</h1>
					<p>Our server stopped processing your request. Your request looks suspicious or similar to automated
						requests from spam posting software.</p>
					<p>If you believe you should be able to perform this request, please let us know.</p>
				</div>
			</div>
		</div>
	</div>
	</body>
	</html>
	
```

**Comment by johngodley** [comment] 2019-04-12 16:18
The problem is shown in the message:

`Our server stopped processing your request. Your request looks suspicious or similar to automated
						requests from spam posting software.`

**Comment by johngodley** [comment] 2019-04-19 12:38
Closing for now, please reopen with more information

**Closed by johngodley** 2019-04-19 12:38 UTC
Labels: need-feedback
