### ISSUE TITLE
Problem starting Redirection 4.9

### ISSUE THREAD

**Issue by wdlaf** [johngodley/redirection#2525] opened 2020-10-28 10:52 UTC
Plugin: 4.9
WordPress: 5.5.1 (single)
PHP: 7.4.11
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
JavaScript: https://businesscasestudies.co.uk/wp-content/plugins/redirection/redirection.js?ver=4.9-c383de96c0b7e38459253ead4f6e9b10
REST API: https://businesscasestudies.co.uk/wp-json/

**Comment by johngodley** [comment] 2020-10-28 11:43
Can you follow the instructions and look at your developer console to see what the error might be. This is almost certainly caused by another plugin

**Comment by johngodley** [comment] 2020-11-08 17:38
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-08 17:38 UTC
