### ISSUE TITLE
Redirection Error - failed to fetch on staging environment, working fine on production

### ISSUE THREAD

**Issue by rahnolds** [johngodley/redirection#765] opened 2018-02-12 21:36 UTC
```
Plugin: 3.1.1
WordPress: 4.9.4 (single)
PHP: 5.6.33-3+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
REST API: http://staging.beyonce.flywheelsites.com/wp-json/

Error: Failed to fetch

Error: Failed to fetch
```

I just ran into this for the first time on my staging environment, I have always interacted with redirection through my staging site so I'm not sure why it's encountering this "failed to fetch" error now.

The redirection plugin loads/runs just fine on my production site, but it's failing on staging and I'm unable to manage my existing redirects, or create new ones. Any suggestions would be greatly appreciated. Thank you!

**Comment by rahnolds** [comment] 2018-02-12 21:44
Plugin status: https://www.dropbox.com/s/cbubm9e6xs786pj/Screenshot%202018-02-12%2013.42.47.png?dl=0

**Comment by johngodley** [comment] 2018-02-12 22:28
Can you try version 3.2? There are extra options you can configure that will probably help with the error. In particular, there error message will show some settings you can change.

Also, if you open your browsers developer console and reload the page it should show you what the error is. Some people with same error found that it was caused by SSL certificate problems.

**Comment by johngodley** [comment] 2018-02-25 14:51
Closing for now, please reopen with more details

**Closed by johngodley** 2018-02-25 14:51 UTC
