### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by marketcalls** [johngodley/redirection#1747] opened 2019-05-10 02:57 UTC
```
Plugin: 4.2.3
WordPress: 5.0.4 (single)
PHP: 5.6.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
JavaScript: https://www.marketcalls.in/wp-content/plugins/redirection/redirection.js
REST API: https://www.marketcalls.in/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 500 Internal Server Error
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
 rajandran@marketcalls.in and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache Server at www.marketcalls.in Port 443</address>
</body></html>

```

**Comment by johngodley** [comment] 2019-05-11 14:11
Your REST API is returning a 500 error. As the plugin indicates, this may be caused by a security plugin

**Comment by johngodley** [comment] 2019-05-18 12:15
Closing for now, please reopen with more details.

**Closed by johngodley** 2019-05-18 12:15 UTC
Labels: need-feedback
