### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by WebFerrante** [johngodley/redirection#1694] opened 2019-04-22 15:10 UTC
```
Plugin: 4.1.1
WordPress: 5.1.1 (single)
PHP: 7.1.28
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://www.tantralove.biz/wp-content/plugins/redirection/redirection.js
REST API: https://www.tantralove.biz/wp-json/

Error: Unexpected token < in JSON at position 1
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 503 Service Unavailable
Raw: 	<!DOCTYPE html>
	<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>In manutenzione.</title>

	</head>
	<body>
		<h1>Momentaneamente non disponibile per manutenzione. Riprovare fra un minuto.</h1>
	</body>
	</html>
	
```

**Comment by johngodley** [comment] 2019-04-27 14:05
Your WordPress REST API is returning a 503 error. This is likely caused by a security plugin.

https://redirection.me/support/problems/rest-api/

**Comment by johngodley** [comment] 2019-05-04 14:05
Closing for now, please reopen with more details

**Closed by johngodley** 2019-05-04 14:05 UTC
Labels: need-feedback
