### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by jsconcepts** [johngodley/redirection#1744] opened 2019-05-09 11:16 UTC
```
Plugin: 4.2.3
WordPress: 5.2 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
JavaScript: http://alloverindia.in/wp-content/plugins/redirection/redirection.js
REST API: http://alloverindia.in/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Action: redirection/v1/redirect/?orderby=id GET
Code: 503 Service Unavailable
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<p>Additionally, a 503 Service Unavailable
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

```

**Comment by johngodley** [comment] 2019-05-11 14:11
Your REST API is returning a 503 error. As the plugin indicates, this may be caused by a security plugin

**Comment by johngodley** [comment] 2019-05-18 12:15
Closing for now, please reopen with more details.

**Closed by johngodley** 2019-05-18 12:15 UTC
Labels: need-feedback
