### ISSUE TITLE
Non "Redirection" redirects bug

### ISSUE THREAD

**Issue by engelsit** [johngodley/redirection#2545] opened 2020-11-04 11:39 UTC
Hello. My problem was:

0. Before I installed the REDIRECTION plugin:
1. I made a page, called "/newgroup/"
2. Then, a made a copy of this page to "newgroup-2", using the Yoast Duplicate Post
3. I returned to "/newgroup/" and made changes to it. 
4. Then, a made a copy of this page to "newgroup-3", using the Yoast Duplicate Post
And so on. 
I have a lot of /newgroup-XXX/ pages. And every time the NEWEST "/newgroup/" page.

5. I installed the REDIRECTION 
Now, my page "/newgroup/" redirects to "newgroup-2".  And visitors cannot access "/newgroup/"  page. 

6. When I disabled REDIRECTION plugin, my page /newgroup/ became visible!
7. When i enabled REDIRECTION plugin, 
the test result is:

HTTP 301 moved permanently - This and all future requests should be directed to the given URI

URL-адрес не перенаправляется с помощью Redirection (url does not redirects with Redirection)

Цель: https://<<<mysite>>>:443/newgroup

8. But "/newgroup/" is really redirects to  "/newgroup-2/"

My email: engelsit@gmail.com

**Comment by johngodley** [comment] 2020-11-04 11:41
Redirection doesn't redirect anything unless you configure it to do so. The URL you supplied is being redirected by WordPress itself, not Redirection. Also, it isn't visible, it's just redirecting.

**Comment by engelsit** [comment] 2020-11-04 11:42
Wordpress did not make any redirects of this page, before I installed Redirection plugin.

**Comment by johngodley** [comment] 2020-11-04 11:43
I can see that WordPress is redirecting it right now. Redirection is not involved in the URL.

**Comment by johngodley** [comment] 2020-11-04 11:44
The key information is `(url does not redirects with Redirection)`

**Comment by engelsit** [comment] 2020-11-04 11:49
Yes. But BEFORE i installed Redirection plugin, it worked great. And now, i cannot access the "newgroup" page.


OH! Now a have new DIAG!

HTTP 301 moved permanently - This and all future requests should be directed to the given URI

URL-адрес не перенаправляется с помощью Redirection

Цель: https://swclub-vintage.ru/**newgroup-2/**

Disabling the plugin, and enabling, does not help.

**Comment by engelsit** [comment] 2020-11-04 11:49
How can i delete this wordpress redirect?

**Comment by johngodley** [comment] 2020-11-04 11:53
You will need to use another plugin to help delete the WordPress redirect. This is not something that Redirection does.

It is very unlikely that Redirection caused the change in that original URL as it does not have the ability to do this. It is more likely that you were seeing a cached page, or that it was caused by something else you did after.

**Comment by engelsit** [comment] 2020-11-08 16:25
I am sorry, but this plugin makes this error.

1. I deleted Redidecrion, and recreated the "/newgroup/" page. It works perfetlty. 
2. I reinstalled Redirection. It makes "/newgroup/" redirect to "/newgroup-2/". And nothing helped, but deleting the plugin.

**Comment by johngodley** [comment] 2020-11-08 16:31
The only way Redirection would do that is if you have created a redirect for `/newgroup/`. It does not do this on its own, and it does not redirect things unless you have told it to do so.

Based on your previous URL, Redirection was not involved.

If you can provide an example URL that is redirecting, and a screenshot of your redirects, then I will be able to investigate.

**Comment by johngodley** [comment] 2020-11-14 10:20
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-11-14 10:20 UTC
