### ISSUE TITLE
Plugin causing pages to load as WP critical error

### ISSUE THREAD

**Issue by mtsweir** [johngodley/redirection#2969] opened 2021-07-04 20:50 UTC
### Summary

After setting all the 301 redirects prior to launch the site started showing a default WordPress error message (see below), I set up redirect examples like:
- Regular redirect: `/biomag-care/` => `/faq/`
- Regex redirect: `/from-merino-with-love.*` => `/shop/`

Plus the client has Google Ads which I updated various URLs to the new structure. Google validated the URLs and failed them even though they were the correct new ones, not sure if the google bot is getting the same error page and failing the ads on that basis.

### Actual Behavior

I get this message when visiting pages: “There has been a critical error on your website” I then have to refresh the page in order for it to load.

### Steps to reproduce

I've had to turn the plugin off since the site was unstable.

### Environment

| Item | Version |
| ---- | ---- |
| WordPress | 5.7.2 |
| Redirection plugin | 5.1.1 |
| Chrome | 91.0.4472.114 |
| PHP | 7.4.20 |

**Comment by johngodley** [comment] 2021-07-04 21:05
Why do you think this is caused by Redirection? A critical error that fixes itself after refresh would indicate another problem, maybe with Redirection being incidental. For example, out of memory. Your server log may provide more information

**Comment by mtsweir** [comment] 2021-07-04 22:16
@johngodley thanks I'll try and grab a server log and post to this thread what findings there are.

**Comment by johngodley** [comment] 2021-07-17 06:08
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-07-17 06:08 UTC
