### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by dgPehrson** [johngodley/redirection#1096] opened 2018-07-30 17:54 UTC
Hey,

I just closed out my last ticket because I logged out and logged back in which sincerely fixed the issue and I was able to see all the redirects that I've created again.

I've acted too hastily in closing out that ticket.  I returned to redirection tab and the old issue wasted no time in returning.  I logged out again and logged back in but this time, the error is staying around.

I don't know what's going on.  All plugins have been deactivated and reactivated.  I kept them all off and only worked with redirection but this error keeps showing up.

I sincerely need help, fast would be appreciated.

Thanks,
Dave

```
Plugin: 3.4
WordPress: 4.9.7 (multi)
PHP: 7.2.6
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0
JavaScript: http://ibscharlotte.contractjolt.com/wp-content/plugins/redirection/redirection.js
REST API: http://ibscharlotte.contractjolt.com/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/group/ GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/redirect/?orderby=id GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

**Comment by johngodley** [comment] 2018-07-30 19:17
Note that your redirects will still work, this only affects your ability to access the admin interface.

I don't know why this message keeps appearing. Logging out and logging in usually fixes it. Whenever I try and log into a site where the problem is occurring, the problem disappears. I suspect it's something to do with caching, but this is just a guess.

If you are able/willing to provide a login I could try and see if I'm able to reproduce the problem on your site.

**Comment by johngodley** [comment] 2018-08-26 15:57
Closing for now, please reopen with more details

**Closed by johngodley** 2018-08-26 15:57 UTC
