### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by qcmiao1998** [johngodley/redirection#2181] opened 2020-02-15 07:36 UTC
```
Plugin: 4.7
WordPress: 5.3.2 (single)
PHP: 7.2.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 Edg/80.0.361.50
JavaScript: https://qcmiao.cn/wp-content/plugins/redirection/redirection.js
REST API: https://qcmiao.cn/wp-json/

Error: Failed to fetch
```

And when I set site alias, it causes ERR_TOO_MANY_REDIRECTS error.

**Comment by johngodley** [comment] 2020-02-15 07:38
Yes, as indicated on the site page it can cause problems if you don't configure your site correctly. What site alias did you set?

**Comment by qcmiao1998** [comment] 2020-02-15 07:45
I set my old domain. But it causes problems including visiting the new domain directly.

I have stopped the WP Super Cache plugin, and I have no CDN in use.

**Comment by johngodley** [comment] 2020-02-15 07:47
Your site appears to still be working. What problem is it causing?

How is a CDN involved in this?

**Comment by qcmiao1998** [comment] 2020-02-15 07:52
I delete the site alias setting, so the site back to work.
I said I have no CDN just for you to rule out CDN's suspicion.

**Comment by johngodley** [comment] 2020-02-15 07:54
Ok. A CDN won't have any effect.

Can you add a screenshot of what you changed? Without being able to see what you did, and to see the problem happening, it's hard for me to do anything.

**Comment by qcmiao1998** [comment] 2020-02-15 08:07
The browser give an error.
```
Failed to fetch
message @ redirection.js?ver=4.7-2ca80703d3d905fb590f039ab6403588:61
(anonymous) @ redirection.js?ver=4.7-2ca80703d3d905fb590f039ab6403588:12
b @ redirection.js?ver=4.7-2ca80703d3d905fb590f039ab6403588:12
(anonymous) @ redirection.js?ver=4.7-2ca80703d3d905fb590f039ab6403588:61
(anonymous) @ redirection.js?ver=4.7-2ca80703d3d905fb590f039ab6403588:61
dispatch @ redirection.js?ver=4.7-2ca80703d3d905fb590f039ab6403588:12
(anonymous) @ redirection.js?ver=4.7-2ca80703d3d905fb590f039ab6403588:61
```
And my setting is like this:
![Annotation 2020-02-15 155950](https://user-images.githubusercontent.com/14857045/74584427-30b22680-500d-11ea-9ad8-adb8d4328cda.png)

**Comment by johngodley** [comment] 2020-02-15 08:13
I can't reproduce a problem.

Can you enable this again so I can see the problem happening?

**Comment by qcmiao1998** [comment] 2020-02-15 08:16
You can see it now.

**Comment by johngodley** [comment] 2020-02-15 08:20
Ok, yes, your site is redirecting to itself. What other settings and redirects do you have enabled? Is this single site or multi site? What URLs do you have listed on the Settings > General page?

**Comment by qcmiao1998** [comment] 2020-02-15 08:30
![image](https://user-images.githubusercontent.com/14857045/74584732-6278bc80-5010-11ea-8dda-f05c5efc4856.png)
It is in endless 301 to itself.

**Comment by johngodley** [comment] 2020-02-15 08:31
> Ok, yes, your site is redirecting to itself. What other settings and redirects do you have enabled? Is this single site or multi site? What URLs do you have listed on the Settings > General page?

**Comment by qcmiao1998** [comment] 2020-02-15 08:33
I just install your plugin today, so I did not do any other setting. It is a single site and I set the site URLs are both https://qcmiao.cn

**Comment by johngodley** [comment] 2020-02-15 08:38
Ok, I'm just trying to understand why this is happening. I cannot reproduce the problem and so there must be something different about your site. Could you post the Site Health report, either here or directly to me (contact info on the plugin support page).

**Comment by qcmiao1998** [comment] 2020-02-15 08:42
Just 2 recommended improvements. Ask me to remove plugins and themes which are not enabled.

**Comment by johngodley** [comment] 2020-02-15 08:43
Can you post it here or send it though? It may help me understand your site

**Comment by qcmiao1998** [comment] 2020-02-15 08:46
My site set in Chinese, I think maybe you cannot read it. What information do you want to know? I can tell you in English.

**Comment by qcmiao1998** [comment] 2020-02-15 08:48
```
### wp-core ###

version: 5.3.2
site_language: zh_CN
user_language: zh_CN
timezone: Asia/Shanghai
permalink: /archives/%post_id%.html
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /www/wwwroot/www_moonhe_com
wordpress_size: 107.97 MB (113216785 bytes)
uploads_path: oss://qc-wordpress-oss-2018/uploads
uploads_size: 131.10 MB (137467147 bytes)
themes_path: /www/wwwroot/www_moonhe_com/wp-content/themes
themes_size: 8.32 MB (8725697 bytes)
plugins_path: /www/wwwroot/www_moonhe_com/wp-content/plugins
plugins_size: 63.52 MB (66607005 bytes)
database_size: 11.08 MB (11616256 bytes)
total_size: 321.99 MB (337632890 bytes)

### wp-active-theme ###

name: Kratos（Kratos-2.5.8）
version: 2.5.8
author: Vtrois
author_website: https://www.vtrois.com/
parent_theme: none
theme_features: post-formats, post-thumbnails, menus, widgets
theme_path: /www/wwwroot/www_moonhe_com/wp-content/themes/Kratos-2.5.8

### wp-themes-inactive (3) ###

Dobby: version: 1.0.0, author: Vtrois
Twenty Nineteen: version: 1.4, author: WordPress团队
Twenty Twenty: version: 1.1, author: WordPress团队

### wp-plugins-active (9) ###

Gutenberg: version: 7.5.0, author: Gutenberg Team
Kill 429: version: 1.0.0, author: wbolt
MathJax-LaTeX: version: 1.3.11, author: Phillip Lord, Simon Cockell, Paul Schreiber
OSS Upload: version: 4.8.7, author: Link
reCaptcha by BestWebSoft: version: 1.55, author: BestWebSoft
UpdraftPlus - Backup/Restore: version: 1.16.21, author: UpdraftPlus.Com, DavidAnderson
WP Acceleration for China: version: 1.6, author: Lomu
WP Mail SMTP: version: 1.8.1, author: WPForms
WP Statistics: version: 12.6.12, author: VeronaLabs

### wp-plugins-inactive (6) ###

Akismet Anti-Spam: version: 4.1.3, author: Automattic
Crayon Syntax Highlighter: version: 2.8.4, author: Aram Kocharyan
Flowplayer HTML5 for WordPress: version: 3.1.1, author: Flowplayer ltd.
Redirection: version: 4.7, author: John Godley
TinyMCE Advanced: version: 5.3.0, author: Andrew Ozz
WP Super Cache: version: 1.7.1, author: Automattic

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: 1656
imagemagick_version: ImageMagick 6.7.8-9 2019-08-08 Q16 http://www.imagemagick.org
gd_version: bundled (2.1.0 compatible)
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 3.10.0-1062.9.1.el7.x86_64 x86_64
httpd_software: nginx/1.17.8
php_version: 7.3.14 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 0
memory_limit: 256M
max_input_time: 120
upload_max_size: 2048M
php_post_max_size: 50M
curl_version: 7.62.0 OpenSSL/1.0.2l
suhosin: false
imagick_availability: true

### wp-database ###

extension: mysqli
server_version: 10.1.26-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /www/wwwroot/www_moonhe_com/wp-content
WP_PLUGIN_DIR: /www/wwwroot/www_moonhe_com/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

```

**Comment by johngodley** [comment] 2020-02-15 09:05
Thanks. Could you post a screenshot of your Settings > General page?

**Comment by qcmiao1998** [comment] 2020-02-15 09:17
![image](https://user-images.githubusercontent.com/14857045/74585381-efbf0f80-5016-11ea-9d1a-ecf47edb061b.png)

**Comment by johngodley** [comment] 2020-02-15 20:22
There's something strange happening on your site.

Could you do the following two things:
- Post a screenshot of the entire Site page
- Download [canonical.php.zip](https://github.com/johngodley/redirection/files/4208966/canonical.php.zip), unzip it, and copy the `canonical.php` file to your `wp-content/plugins/redirection/models/` directory

The new file should output some debug information to your server log file. If you then activate the plugin and access your site it should redirect. You can then disable the plugin.

If you can then find your server log file you should see some log entries that start `redirection: `. If you send them to me (either here or https://redirection.me/contact/) hopefully it will give me enough information to figure out what is happening.

**Comment by johngodley** [comment] 2020-02-23 15:12
Closing for now, please reopen with more information.

**Closed by johngodley** 2020-02-23 15:12 UTC
