### ISSUE TITLE
Bulk select fails on Safari

### ISSUE THREAD

**Issue by ErinPo** [johngodley/redirection#383] opened 2017-09-12 19:15 UTC
Clicking the checkbox for bulk selection has no effect. Hovering over it does show the hand.

Current version Safari. 
Redirection 2.7.3

**Comment by johngodley** [comment] 2017-09-21 18:55
The bulk checkbox works for me in Safari.

Can you open Safari's developer console and see if any errors appear? It is possible that another plugin is interfering with the bulk selection action.

**Comment by johngodley** [comment] 2017-09-30 09:33
Closing for now, please reopen if you have more details

**Comment by ErinPo** [comment] 2017-10-12 18:13
I finally got around to creating a fresh wp install with redirection plugin as the only plugin and default twenty seventeen theme. Bulk selection has no effect in Safari 11.0 without browser plugins on any of the redirection plugin's tabs, while working fine in all the native wp areas. No errors in developer console.
![2017-10-12_bulk_selection_fails](https://user-images.githubusercontent.com/25776184/31512029-db9fe69e-af89-11e7-8782-e15872da0636.jpeg)

**Comment by johngodley** [comment] 2017-10-14 08:49
I'm unable to reproduce this. Can you disable all other WordPress plugins and see if that changes anything?

**Comment by ErinPo** [comment] 2017-10-15 11:19
As stated, I am testing on a fresh WP install with redirection as the only plugin installed.

However, I have a more detailed error description for you. When I click the bulk selection check box after having selected some individual items, this will deselect all of those items. When I select all items on a page manually, the bulk selection check box becomes selected. However, clicking it then has no effect. Only unchecking one of the items results in the bulk selection check box also becoming unselected. Clicking it again then, deselects all the other checkboxes as described in my first observation.

**Comment by johngodley** [comment] 2017-10-19 17:17
Sorry, I'm still unable to reproduce this in Safari. Would it be possible to try it out on the site itself?

**Comment by ErinPo** [comment] 2017-10-19 17:46
No problem. I was going to give you an access but I just noticed that I can no longer reproduce the issue. Maybe because I finally updated to High Sierra, I don't know, but you can close the issue for now.

**Comment by johngodley** [comment] 2017-10-19 18:22
Ok!

**Closed by johngodley** 2017-10-19 18:22 UTC
