### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by vs777** [johngodley/redirection#3064] opened 2021-09-18 02:19 UTC
As soon as I enable the plugin the website becomes inaccessible.
The error message is "Too many redirects" and the plugin settings page is showing everything in error state.

```
Plugin: 5.1.3 4.2
WordPress: 5.7.3 (single)
PHP: 7.3.27-9+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
JavaScript: https://www.moldex.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://www.moldex.com/wp-json/
Query: ?page=redirection.php&sub=support

Error: Failed to fetch
```

**Comment by johngodley** [comment] 2021-09-18 06:27
If it says too many redirects then you have created a redirect loop. You should remove the redirect causing the loop.

**Comment by vs777** [comment] 2021-09-18 06:45
There are no loops for sure, the plugin was working fine, the only problem was that it was not redirecting when the request URL was using http instead of https. I tried to change its settings to force https, and this new issue happened.  
I can access the back end of the website but the front end is what is not working.

**Comment by vs777** [comment] 2021-09-18 06:59
Is there a way to reset the settings on back end?

**Comment by johngodley** [comment] 2021-09-18 20:28
If your browser says there are too many redirects then you have created a loop, either directly through a redirect or by changing one of the settings. You say you have changed a setting so that seems likely to be the cause of the problem.

From the support site:

https://redirection.me/support/disable-redirection/

**Comment by vs777** [comment] 2021-09-18 21:14
Thanks, I was able to access plugins settings by adding a redirections-disabled.txt file.
Can you please help me to resolve my initial issue: why wouldn't these redirections work, while all the others work?

https://www.moldex.com/national-safety/      ->     https://try.moldex.com/national-safety/
https://www.moldex.com/nationalsafety/        ->     https://try.moldex.com/national-safety/

**Comment by johngodley** [comment] 2021-09-19 06:05
Initial issue?

You can see those URLs here, both of which are redirecting:
https://redirect.li/http/?url=https%3A%2F%2Fwww.moldex.com%2Fnational-safety%2F - not Redirection
https://redirect.li/http/?url=https%3A%2F%2Fwww.moldex.com%2Fnationalsafety%2F - Redirection

**Comment by vs777** [comment] 2021-09-19 06:24
that is the problem; I dont have any other redirection plugins installed other than Redirection. 
The link https://www.moldex.com/national-safety/ is being redirected to the wrong URL for some reason. Is that because of WP engine?

**Comment by johngodley** [comment] 2021-09-19 06:28
I cannot say. It is being redirected by something else.

**Comment by vs777** [comment] 2021-09-19 06:30
it seems it is redirecting properly when I don't use the last backslash
https://www.moldex.com/national-safety

**Comment by johngodley** [comment] 2021-09-19 06:31
> it seems it is redirecting properly when I don't use the last backslash

Your redirect does not have a trailing slash. The URL must match.

**Comment by johngodley** [comment] 2022-01-09 16:49
Closing for now, please reopen with more information.

**Closed by johngodley** 2022-01-09 16:49 UTC
Labels: need-feedback
