### ISSUE TITLE
Red_Source_Flags not found???

### ISSUE THREAD

**Issue by jjxtra** [johngodley/redirection#1822] opened 2019-06-12 22:51 UTC
Seeing this in my logs after adding this plugin:

PHP Fatal error:  Class 'Red_Source_Flags' not found 

Any idea where Red_Source_Flags is defined?

**Comment by johngodley** [comment] 2019-06-13 04:49
It is included in the plugin. The problem is likely that your plugin is not installed properly. Please remove it and re-install.

**Comment by johngodley** [comment] 2019-06-20 17:46
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-06-20 17:46 UTC
Labels: need-feedback

**Comment by jjxtra** [comment] 2019-06-20 18:05
It was a file permission issue. Some of the include files could not be opened.
