### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by abubaker-cs** [johngodley/redirection#1805] opened 2019-06-09 10:16 UTC
```
Plugin: 4.3.1
WordPress: 5.2.1 (single)
PHP: 7.1.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
JavaScript: http://www.systemoflife.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.systemoflife.com/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Action: redirection/v1/redirect/ POST
Params: {"id":0,"url":"http://www.systemoflife.com/articles/tawassul/186-badaee-tawassul-refutation-series-tawassul-on-grave-of-imam-bukhari","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":false,"flag_case":false,"flag_query":"exact"}},"match_type":"url","action_type":"url","position":0,"group_id":2,"action_code":301,"action_data":{"url":"http://www.systemoflife.com/badaee-tawassul-refutation-series-tawassul-on-grave-of-imam-bukhari/"}}
Code: 500 Internal Server Error
Raw: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<style type="text/css">
body{background-color:#f4f9fa}
.centered{text-align:center}
.container{border:1px solid #e2e2e2;width:750px;margin:50px auto}
.header{height:100px;background-color:#fff;padding-top:50px;background:url(/error_page.gif) top repeat-x}
.header h1{font: bold 150% Arial, Helvetica, sans-serif; color:#5278af;margin:0;padding:0}
.header h2{font: bold 80% Tahoma, Verdana, sans-serif; color:#5278af;margin:0;padding:0}
.line{height:15px;background-color:#eef6f7}
.error-container{background-color:#fff;font:normal 80% Tahoma, Verdana, sans-serif;color:#000;text-align:justify;padding:30px}
.error-container li{padding-bottom:10px}
</style><title>500 - Internal Server Error</title>

</head>

<body>
<div class="centered">
<div class="container">
<div class="header">
<h1>500 - Internal Server Error</h1>
<h2>&nbsp;This is a temporary server error.&nbsp;</h2>
<h2>Please try to reload the webpage later.&nbsp;</h2>
</div>
<div class="line"></div>
<div class="error-container">
<p>If you are the webmaster of this site please log in to Cpanel
and check the Error Logs. You will find the exact reason for this error
there.</p>
<p>Common reasons for this error are:</p>
<ul>
<li>Incorrect file/directory permissions: Above 755.
<p>In order files to be processed by the webserver, their
permissions have to be equal or below 755. You can update file
permissions with a FTP client or through cPanel's File Manager.</p>
</li>
<li>Incorrect Apache directives inside .htaccess file.
<p>Make sure you have not specified unsupported directives inside the
local .htaccess file. Such include PHP settings and Apache module
settings. </p>
</li>
</ul>
</div>
</div>
</div>
</body></html>

```

**Comment by burdyga** [comment] 2019-06-10 07:07
@abubaker-cs Check rewrite_rules in wp_options table. Is it empty ?

**Comment by johngodley** [comment] 2019-06-10 07:08
This is not related to rewrite rules. The plugin error message should provide information about how to proceed with this and it is likely caused by a security plugin.

**Comment by johngodley** [comment] 2019-06-14 05:34
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-06-14 05:34 UTC
Labels: need-feedback
