### ISSUE TITLE
Problem starting Redirection 5.3.8

### ISSUE THREAD

**Issue by William-Haflidson** [johngodley/redirection#3535] opened 2023-01-24 14:37 UTC
```
Uncaught TypeError: Cannot read properties of undefined (reading 'hooks') https://aixsafety.com/wp-includes/js/dist/i18n.min.js?ver=9e794f35a71bb98672ae 2,Uncaught ReferenceError: wp is not defined https://aixsafety.com/wp-admin/tools.php?page=redirection.php&sub=options 296,Uncaught ReferenceError: wp is not defined https://aixsafety.com/wp-admin/js/common.min.js?ver=6.1.1 2,Uncaught ReferenceError: wp is not defined https://aixsafety.com/wp-content/plugins/redirection/redirection.js?ver=5.3.8-2fe1525b965f0dad5e09e733bfb52ddc 2
```

Plugin: 5.3.8 4.2
WordPress: 6.1.1 (single)
PHP: 8.0.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
JavaScript: https://aixsafety.com/wp-content/plugins/redirection/redirection.js?ver=5.3.8-2fe1525b965f0dad5e09e733bfb52ddc
REST API: https://aixsafety.com/wp-json/

**Comment by johngodley** [comment] 2023-03-04 14:00
This is probably caused by another plugin. You should follow the instructions and look at your browser developer console.

**Comment by johngodley** [comment] 2023-04-15 13:37
Closing for now, please reopen with more details.

**Closed as completed by johngodley** 2023-04-15 13:37 UTC
Labels: need-feedback
