### ISSUE TITLE
Problem starting Redirection 4.3

### ISSUE THREAD

**Issue by matthewcharlesworth** [johngodley/redirection#1794] opened 2019-06-04 09:59 UTC
```
Uncaught SyntaxError: missing ) after argument list http://www.jesuitinstitute.org.za/wp-content/plugins/redirection/redirection.js?ver=4.3-360758b71dd62f46abf52e4615e7b875 62
```

Plugin: 4.3
WordPress: 5.2.1 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
JavaScript: http://www.jesuitinstitute.org.za/wp-content/plugins/redirection/redirection.js
REST API: http://www.jesuitinstitute.org.za/index.php/wp-json/

**Comment by johngodley** [comment] 2019-06-04 10:13
Please open your browser's developer console and see if any other information is shown. This is likely caused by another plugin.

**Comment by matthewcharlesworth** [comment] 2019-06-04 10:36
Hi,

This is what the console says:
Can you tell me what plugin? Because I haven't added any plugin in a
while...

Matthew

====begin console======
Navigated to
http://www.jesuitinstitute.org.za/wp-admin/tools.php?page=redirection.php
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:8
JQMIGRATE: Migrate is installed, version 1.4.1
tools.php?page=redirection.php:469 Uncaught SyntaxError: missing ) after
argument list
window.onerror @ tools.php?page=redirection.php:469
error (async)
(anonymous) @ tools.php?page=redirection.php:468
redirection.js?ver=4.3-360758b71dd62f46abf52e4615e7b875:62 Uncaught
SyntaxError: missing ) after argument list
pixel.wp.com/g.gif?v=wpcom-no-pv&x_notes-menu-impressions=zero-jetpack&baba=0.5198875526803268:1
GET
http://pixel.wp.com/g.gif?v=wpcom-no-pv&x_notes-menu-impressions=zero-jetpack&baba=0.5198875526803268
net::ERR_BLOCKED_BY_CLIENT
Image (async)
bumpStat @ notes-common-v2.js?ver=7.3.1-201923:26
initialize @ admin-bar-v2.js?ver=7.3.1-201923:30
b.View @ backbone.min.js?ver=1.2.3:1
N.d @ backbone.min.js?ver=1.2.3:1
(anonymous) @ admin-bar-v2.js?ver=7.3.1-201923:70
i @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:2
fireWith @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:2
ready @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:2
J @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:2
pixel.wp.com/g.gif?x_stats-initial-visibility=visible&v=wpcom-no-pv&rand=0.7414799201206086:1
GET
https://pixel.wp.com/g.gif?x_stats-initial-visibility=visible&v=wpcom-no-pv&rand=0.7414799201206086
net::ERR_BLOCKED_BY_CLIENT
Image (async)
_loadGif @ w.js?60:2
extra @ w.js?60:2
trackInitialVisibilityState @ w.js?60:5
(anonymous) @ w.js?60:6
(anonymous) @ w.js?60:6
pixel.wp.com/boom.gif?v=0.9&u=https://public-api.wordpress.com/pinghub&json={%22beacons%22:[%22pinghub.restproxy.ws_supported.unknown:1|c%22]}:1
GET
https://pixel.wp.com/boom.gif?v=0.9&u=https://public-api.wordpress.com/pinghub&json={%22beacons%22:[%22pinghub.restproxy.ws_supported.unknown:1|c%22]}
net::ERR_BLOCKED_BY_CLIENT
Image (async)
y @ ?v=2.0:6
_ @ ?v=2.0:6
o @ ?v=2.0:6
pixel.wp.com/boom.gif?v=0.9&u=https://public-api.wordpress.com/pinghub&json={%22beacons%22:[%22pinghub.restproxy.cookie.unknown:1|c%22]}:1
GET
https://pixel.wp.com/boom.gif?v=0.9&u=https://public-api.wordpress.com/pinghub&json={%22beacons%22:[%22pinghub.restproxy.cookie.unknown:1|c%22]}
net::ERR_BLOCKED_BY_CLIENT
Image (async)
y @ ?v=2.0:6
_ @ ?v=2.0:6
o @ ?v=2.0:6
pixel.wp.com/boom.gif?v=0.9&u=https://public-api.wordpress.com/pinghub&json={%22beacons%22:[%22pinghub.conn_open_dc.dca.unknown:377|ms%22]}:1
GET
https://pixel.wp.com/boom.gif?v=0.9&u=https://public-api.wordpress.com/pinghub&json={%22beacons%22:[%22pinghub.conn_open_dc.dca.unknown:377|ms%22]}
net::ERR_BLOCKED_BY_CLIENT
Image (async)
y @ ?v=2.0:6
a.onopen @ ?v=2.0:6
?v=2.0:6 XHR finished loading: GET "
https://public-api.wordpress.com/rest/v1.1/me?http_envelope=1&fields=ID%2Cusername
".
h @ ?v=2.0:6
o @ ?v=2.0:6
?v=2.0:6 XHR finished loading: GET "
https://public-api.wordpress.com/rest/v1.1/notifications/?http_envelope=1&fields=id%2Ctype%2Cunread%2Cbody%2Csubject%2Ctimestamp%2Cmeta%2Cnote_hash&number=10
".
h @ ?v=2.0:6
o @ ?v=2.0:6
pixel.wp.com/g.gif?v=wpcom-no-pv&x_notes-empty-message=all_shown&baba=0.4445721449229856:1
GET
https://pixel.wp.com/g.gif?v=wpcom-no-pv&x_notes-empty-message=all_shown&baba=0.4445721449229856
net::ERR_BLOCKED_BY_CLIENT
Image (async)
ze @ build.min.js?db22c4aaa2aa2155e18f:77
value @ build.min.js?db22c4aaa2aa2155e18f:77
ci @ build.min.js?db22c4aaa2aa2155e18f:33
No @ build.min.js?db22c4aaa2aa2155e18f:33
Do @ build.min.js?db22c4aaa2aa2155e18f:33
Ba @ build.min.js?db22c4aaa2aa2155e18f:33
$a @ build.min.js?db22c4aaa2aa2155e18f:33
Ps @ build.min.js?db22c4aaa2aa2155e18f:33
Cs @ build.min.js?db22c4aaa2aa2155e18f:33
ks @ build.min.js?db22c4aaa2aa2155e18f:33
Xa @ build.min.js?db22c4aaa2aa2155e18f:33
enqueueSetState @ build.min.js?db22c4aaa2aa2155e18f:33
b.setState @ build.min.js?db22c4aaa2aa2155e18f:41
s.onStateChange @ build.min.js?db22c4aaa2aa2155e18f:77
p @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
E @ build.min.js?db22c4aaa2aa2155e18f:25
load (async)
t.bind @ build.min.js?db22c4aaa2aa2155e18f:77
t.default @ build.min.js?db22c4aaa2aa2155e18f:25
t.default @ build.min.js?db22c4aaa2aa2155e18f:25
a.get @ build.min.js?db22c4aaa2aa2155e18f:77
Re @ build.min.js?db22c4aaa2aa2155e18f:77
wi.getNotes @ build.min.js?db22c4aaa2aa2155e18f:77
bi @ build.min.js?db22c4aaa2aa2155e18f:77
wi.setVisibility @ build.min.js?db22c4aaa2aa2155e18f:77
value @ build.min.js?db22c4aaa2aa2155e18f:77
ci @ build.min.js?db22c4aaa2aa2155e18f:33
No @ build.min.js?db22c4aaa2aa2155e18f:33
Do @ build.min.js?db22c4aaa2aa2155e18f:33
Ba @ build.min.js?db22c4aaa2aa2155e18f:33
$a @ build.min.js?db22c4aaa2aa2155e18f:33
Ps @ build.min.js?db22c4aaa2aa2155e18f:33
Cs @ build.min.js?db22c4aaa2aa2155e18f:33
ks @ build.min.js?db22c4aaa2aa2155e18f:33
Xa @ build.min.js?db22c4aaa2aa2155e18f:33
enqueueSetState @ build.min.js?db22c4aaa2aa2155e18f:33
b.setState @ build.min.js?db22c4aaa2aa2155e18f:41
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
E @ build.min.js?db22c4aaa2aa2155e18f:25
load (async)
t.bind @ build.min.js?db22c4aaa2aa2155e18f:77
t.default @ build.min.js?db22c4aaa2aa2155e18f:25
value @ build.min.js?db22c4aaa2aa2155e18f:77
ci @ build.min.js?db22c4aaa2aa2155e18f:33
No @ build.min.js?db22c4aaa2aa2155e18f:33
Do @ build.min.js?db22c4aaa2aa2155e18f:33
Ba @ build.min.js?db22c4aaa2aa2155e18f:33
$a @ build.min.js?db22c4aaa2aa2155e18f:33
Ps @ build.min.js?db22c4aaa2aa2155e18f:33
Cs @ build.min.js?db22c4aaa2aa2155e18f:33
ks @ build.min.js?db22c4aaa2aa2155e18f:33
Xa @ build.min.js?db22c4aaa2aa2155e18f:33
js @ build.min.js?db22c4aaa2aa2155e18f:33
Rs @ build.min.js?db22c4aaa2aa2155e18f:33
qs.render @ build.min.js?db22c4aaa2aa2155e18f:33
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:33
Ds @ build.min.js?db22c4aaa2aa2155e18f:33
Ws @ build.min.js?db22c4aaa2aa2155e18f:33
render @ build.min.js?db22c4aaa2aa2155e18f:33
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
n @ build.min.js?db22c4aaa2aa2155e18f:1
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:1
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:1
pixel.wp.com/g.gif?v=wpcom-no-pv&x_notes-empty-message=all_shown&baba=0.4113940615130174:1
GET
https://pixel.wp.com/g.gif?v=wpcom-no-pv&x_notes-empty-message=all_shown&baba=0.4113940615130174
net::ERR_BLOCKED_BY_CLIENT
Image (async)
ze @ build.min.js?db22c4aaa2aa2155e18f:77
value @ build.min.js?db22c4aaa2aa2155e18f:77
Va @ build.min.js?db22c4aaa2aa2155e18f:33
Ya @ build.min.js?db22c4aaa2aa2155e18f:33
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:33
t.unstable_runWithPriority @ build.min.js?db22c4aaa2aa2155e18f:49
Ms @ build.min.js?db22c4aaa2aa2155e18f:33
Ps @ build.min.js?db22c4aaa2aa2155e18f:33
Cs @ build.min.js?db22c4aaa2aa2155e18f:33
ks @ build.min.js?db22c4aaa2aa2155e18f:33
Xa @ build.min.js?db22c4aaa2aa2155e18f:33
enqueueSetState @ build.min.js?db22c4aaa2aa2155e18f:33
b.setState @ build.min.js?db22c4aaa2aa2155e18f:41
s.onStateChange @ build.min.js?db22c4aaa2aa2155e18f:77
p @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
E @ build.min.js?db22c4aaa2aa2155e18f:25
load (async)
t.bind @ build.min.js?db22c4aaa2aa2155e18f:77
t.default @ build.min.js?db22c4aaa2aa2155e18f:25
t.default @ build.min.js?db22c4aaa2aa2155e18f:25
a.get @ build.min.js?db22c4aaa2aa2155e18f:77
Re @ build.min.js?db22c4aaa2aa2155e18f:77
wi.getNotes @ build.min.js?db22c4aaa2aa2155e18f:77
bi @ build.min.js?db22c4aaa2aa2155e18f:77
wi.setVisibility @ build.min.js?db22c4aaa2aa2155e18f:77
value @ build.min.js?db22c4aaa2aa2155e18f:77
ci @ build.min.js?db22c4aaa2aa2155e18f:33
No @ build.min.js?db22c4aaa2aa2155e18f:33
Do @ build.min.js?db22c4aaa2aa2155e18f:33
Ba @ build.min.js?db22c4aaa2aa2155e18f:33
$a @ build.min.js?db22c4aaa2aa2155e18f:33
Ps @ build.min.js?db22c4aaa2aa2155e18f:33
Cs @ build.min.js?db22c4aaa2aa2155e18f:33
ks @ build.min.js?db22c4aaa2aa2155e18f:33
Xa @ build.min.js?db22c4aaa2aa2155e18f:33
enqueueSetState @ build.min.js?db22c4aaa2aa2155e18f:33
b.setState @ build.min.js?db22c4aaa2aa2155e18f:41
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
E @ build.min.js?db22c4aaa2aa2155e18f:25
load (async)
t.bind @ build.min.js?db22c4aaa2aa2155e18f:77
t.default @ build.min.js?db22c4aaa2aa2155e18f:25
value @ build.min.js?db22c4aaa2aa2155e18f:77
ci @ build.min.js?db22c4aaa2aa2155e18f:33
No @ build.min.js?db22c4aaa2aa2155e18f:33
Do @ build.min.js?db22c4aaa2aa2155e18f:33
Ba @ build.min.js?db22c4aaa2aa2155e18f:33
$a @ build.min.js?db22c4aaa2aa2155e18f:33
Ps @ build.min.js?db22c4aaa2aa2155e18f:33
Cs @ build.min.js?db22c4aaa2aa2155e18f:33
ks @ build.min.js?db22c4aaa2aa2155e18f:33
Xa @ build.min.js?db22c4aaa2aa2155e18f:33
js @ build.min.js?db22c4aaa2aa2155e18f:33
Rs @ build.min.js?db22c4aaa2aa2155e18f:33
qs.render @ build.min.js?db22c4aaa2aa2155e18f:33
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:33
Ds @ build.min.js?db22c4aaa2aa2155e18f:33
Ws @ build.min.js?db22c4aaa2aa2155e18f:33
render @ build.min.js?db22c4aaa2aa2155e18f:33
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
n @ build.min.js?db22c4aaa2aa2155e18f:1
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:1
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:1
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:4
XHR finished loading: GET "
http://www.jesuitinstitute.org.za/index.php/wp-json/jetpack/v4/jitm?message_path=wp%3Atools_page_redirection%3Aadmin_notices&query=page%253Dredirection.php&_wpnonce=438edf69e0
".
send @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:4
ajax @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:4
n.<computed> @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:4
(anonymous) @ jetpack-jitm.min.js?ver=7.3.1:2
each @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:2
each @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:2
e @ jetpack-jitm.min.js?ver=7.3.1:2
(anonymous) @ jetpack-jitm.min.js?ver=7.3.1:2
i @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:2
fireWith @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:2
ready @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:2
J @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.2.1:2
=====end console======

**Comment by johngodley** [comment] 2019-06-23 09:55
There is no way for me to tell you which plugin - another one installed on your site. The problem could be caused by a plugin being updated.

**Comment by johngodley** [comment] 2019-07-13 14:41
Closing for now, please reopen with more information.

**Closed by johngodley** 2019-07-13 14:41 UTC
Labels: need-feedback
